### ISSUE TITLE
Request: automatic clipboard download

### ISSUE THREAD

**Issue by Efreak** [firedm/FireDM#115]
Please add a feature to automatically download all URLs added to the clipboard. Ideally, this should be time-limited (ie, reset after ~1/2 hour) to prevent forgetting such a feature is turned on, as well as possibly having a configurable filter based on url and file type (fetch header first, if simple enough to implement).

Use case: I'm downloading a series of images from the browser. Sure, they're already local in my cache, but that's hardly accessible. Sure, I could use a purpose-built download manager to download an entire gallery, but I don't want *all* the images in the gallery, I only want *some* of them. Occasionally I'm downloading a series of files stuff from moddb (game mods), github (project releases), desktop wallpapers, or memes. Two clicks (right click, copy image address) is *far* faster than copying the url and pasting it into another file for later import into a download manager queue.

**Comment by pyIDM** [comment]
@Efreak 
will consider this feature to be added to PyIDM todo-list

**Comment by Harshil783** [comment]
Please Close this issue If it's done?

**Comment by firedm** [comment]
with new Batch download feature, you can click on BAT button, batch window will open, and listen to clipboard, it will add all copied urls automatically, then when finished you can click download
