### ISSUE TITLE
Feature request: Google drive support. 

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#144]
Hi,

It seems PyIDM can't retrieve the correct URL of file resided on Google drive, say, [this file](
https://drive.google.com/file/d/1tnRtS8N9-mc3hsZNsh0s3UCMTDrALwuf/view). Is it possible to add this feature into PyIDM?

**Comment by pyIDM** [comment]
@hongyi-zhao 
will put this feature in my todo list

Below is some info for future reference to work on this issue
There is 2 routes to implement this feature:
1- Thru google API,  https://developers.google.com/drive/v2/reference/files/get#examples which requires authentication
2- using technique described in this post https://stackoverflow.com/a/39225039 for public files and doesn't need authentication

both require file id which can be extracted from the link using regex as below example:
```
example urls:
# https://drive.google.com/file/d/1tnRtS8N9-mc3hsZNsh0s3UCMTDrALwuf/view
# https://drive.google.com/uc?id=1tnRtS8N9-mc3hsZNsh0s3UCMTDrALwuf&export=download

base_url = "https://drive.google.com/uc?export=download"
# extract id
match = re.findall(r'/.*[^\w]([-\w]{25,})[^\w]?.*', url) 
if match:
    id_=match[-1]
    new_url = base_url + '&id=' + id_
```

example of number2 method:
```
#taken from this StackOverflow answer: https://stackoverflow.com/a/39225039
import requests

def download_file_from_google_drive(id, destination):
    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    save_response_content(response, destination)    

def get_confirm_token(response):
    print(response.cookies)
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value

    return None

def save_response_content(response, destination):
    CHUNK_SIZE = 32768

    with open(destination, "wb") as f:
        for chunk in response.iter_content(CHUNK_SIZE):
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)

file_id = '0B63gyvEOCH-5N1F3NVlUV0F5cmM'
destination = '/home/mahmoud/Downloads/5/vid.mp4'
download_file_from_google_drive(file_id, destination)
```

**Comment by hongyi-zhao** [comment]
IDM hasn't this feature also. If PyIDM can do the trick, it will be great.

**Comment by firedm** [comment]
@hongyi-zhao 
looking thru all available options to download files from google drive, found out i can get direct link using the technique mentioned in above script

After a lot of testing found a problem which is:
google server doesn't send information about the file size in headers, which make it impossible to make a multi-segment file which means no multi-connection will be available, 
with these restrictions, FireDM will offer no advantage over any web-browser while downloading google drive file.

sorry, i have to discard this feature entirely
closing these issue

**Comment by hongyi-zhao** [comment]
I'm not sure if the sparse file technique can be used as a workaround for this case. I mean, you can first build a large sparse file as the template of the want-to-be downloaded file, and then do the segmentation and let FireDM remember the position for each segment. Just my flash of speculation without knowing its feasibility through.

Regards,
HY

**Comment by firedm** [comment]
> I'm not sure if the sparse file technique can be used as a workaround for this case. I mean, you can first build a large sparse file as the template of the want-to-be downloaded file, then do the segmentation and let FireDM remember the position of each segment. After the file has been downloaded successfully, of course, some additional logic is needed to do the reasonable judgment, truncate the template to its real size. Just my flash of speculation without knowing its feasibility through.
> 
> Regards,
> HY

Thanks for sharing
unfortunately there is no way to tell when "**file has been downloaded successfully**," except checking the remote file size vs the size of the actual downloaded data on the disk, without knowing the remote file size, we are like shooting in the dark.

what we do for unknown file sizes is running one connection for downloading the file and mark file completed when server drop connection "unfortunately, server connection can be dropped due to a lot of factors, e.g. unstable network, internal server error, exceed quota, etc..., which leave you with a corrupted file"

**Comment by Blocked** [comment]
@firedm The file size can be retrieved from the api you mentioned: https://developers.google.com/drive/v2/reference/files/get#examples

It usually doesn't require authorization/authentication for  public files

**Comment by firedm** [comment]
@Blocked 

if you try to get file metadat using below link
https://www.googleapis.com/drive/v2/files/file-id        note: file-id is a placeholder try it with a public file id

you get the following:

{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

in the link you provided 
https://developers.google.com/drive/v2/reference/files/get#examples

you can try google api from "Try This API" form on the right of the page and it will ask you to authenticate and enable "Google Drive API" then you will get a nice jason output with everything you need about the file including size

conclusion: google api requires authentication  **"Google account with Google Drive enabled"**.

back to block zero: still can't automate this without authentication, let me know if you have a way to do it

**Comment by Blocked** [comment]
@firedm It's not that hard to create a apikey. It is possible to create your own app key. Or It can also be left to end users to supply their own apikey for gdrive downloads. The key only identifies the user, but drive scopes are not needed. Furthermore, the error states that there indeed was a free quota/daily limit without authentication, but that it was exceeded. 

FWIW, You can open that page in a incognito tab > check "API KEY"(uncheck oauth) >  Click Execute to get full details of the file on that page without logging in or any authentication or authorization. Also checkout https://github.com/tanaikech/goodls

**Comment by hongyi-zhao** [comment]
Another tool is [gdown](https://github.com/wkentaro/gdown). But I encountered [this error](https://github.com/wkentaro/gdown/issues/111) while trying the tool.

**Comment by firedm** [comment]
@hongyi-zhao thanks for testing

**Comment by firedm** [comment]
@Blocked 

>  It can also be left to end users to supply their own apikey for gdrive downloads

i think this is the best bad option, i will give it a shot
