### ISSUE TITLE
Add a full terminal control?

### ISSUE THREAD

**Issue by ThePhoenix78** [firedm/FireDM#170]
Can you please add a full terminal control for pyidm?
It could be like :
pyidm url --folder linkToFolder --format mp3-128 --login (if necessary) login --password (if necessary) password ect...
Thank you!

**Comment by pyIDM** [comment]
@ThePhoenix78 

> Can you please add a full terminal control for pyidm?
> It could be like :
> pyidm url --folder linkToFolder --format mp3-128 --login (if necessary) login --password (if necessary) password ect...
> Thank you!

work already in progress for cmd line interface, will submit once finished
