### ISSUE TITLE
Not start on W7 x64

### ISSUE THREAD

**Issue by gitdarktable** [firedm/FireDM#186]
Extract file and run PyIDM.exe but splash window:

![2](https://user-images.githubusercontent.com/57431523/98646568-d80d8100-2333-11eb-8183-f5da766a3c4f.png)

With version 2020.3.31 ok but with later versions it fails.

Installed Python v3.7.6150.0 on w7 x64.

**Comment by gitdarktable** [comment]
Sorry, 
PyIDM version 2020.10.28

**Comment by pyIDM** [comment]
@gitdarktable 
the link you provided is not working
if you're trying to upload a screenshot, you can drag and drop a photo into a new comments in this page

**Comment by gitdarktable** [comment]
It is done.

**Comment by pyIDM** [comment]
@gitdarktable 
please check if latest release is working for you or close this issue if this is no longer a problem for you

**Comment by gitdarktable** [comment]
Hi, PyIDM version 2021.2.7 similar error:

![pyIDM](https://user-images.githubusercontent.com/57431523/107246133-3976e600-6a30-11eb-9bc2-7310179efc4a.jpg)

Thanks!

**Comment by gitdarktable** [comment]
Hi, I have solved it uninstalling python v3.7.6 and install windows6.1-kb2533623-x64.msu and python v3.8.10.

Today works correctly FireDM v2021.07.25 

Thanks!!

**Comment by firedm** [comment]
@gitdarktable 
this is good news it works for you
