### ISSUE TITLE
Interface - Download list problems and suggestions

### ISSUE THREAD

**Issue by quamt** [firedm/FireDM#187]
In the new Pyidm I've noticed

1. There is no longer an option to select all videos at once. Each video has to be selected one by one. 

2. The download status always jumps to the last download in the list after a task has been performed. 
If there are many downloads in the Q it can be very difficult as everytime need to scroll up again.

3. If in any case the app gets closed all downloads show canceled.
It would be great to have the option to restart them, else each download has to be clicked one by one. With problem mentioned in point 2 this is very tedious.

**Comment by pyIDM** [comment]
> 
> 
> In the new Pyidm I've noticed
> 
>     1. There is no longer an option to select all videos at once. Each video has to be selected one by one.

No problem will add select all check button

> 
>     2. The download status always jumps to the last download in the list after a task has been performed.
>        If there are many downloads in the Q it can be very difficult as everytime need to scroll up again.
> 

I agree it is sometimes annoying will fix this

>     3. If in any case the app gets closed all downloads show canceled.
>        It would be great to have the option to restart them, else each download has to be clicked one by one. With problem mentioned in point 2 this is very tedious.

will make a button to resume all cancelled downloads

**Comment by quamt** [comment]
@pyIDM 

Thank you.

4. Sometimes download stuck at 99% and wont finish

`>> Seg video_seg_721.ts start, size: ... - range: None  - worker 3
>> downloaded segment:  video_seg_721.ts None 470 KB - worker 3
>> Seg video_seg_721.ts.key start, size: ... - range: None  - worker 3
>> downloaded segment:  video_seg_721.ts.key None 16 bytes - worker 3
>> Seg video_seg_722.ts start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> downloaded segment:  video_seg_717.ts None 1.0 MB - worker 1
>> Seg video_seg_722.ts.key start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  video_seg_722.ts.key None 16 bytes - worker 1
>> Seg video_seg_723.ts start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  video_seg_722.ts None 291 KB - worker 3
>> Seg video_seg_723.ts.key start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> downloaded segment:  video_seg_723.ts.key None 16 bytes - worker 3
>> Seg video_seg_724.ts start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> downloaded segment:  video_seg_724.ts None 200 KB - worker 3
>> Seg video_seg_724.ts.key start, size: ... - range: None- minimum speed= 20480, timeout=10  - worker 3
>> downloaded segment:  video_seg_724.ts.key None 16 bytes - worker 3
>> downloaded segment:  video_seg_723.ts None 1.2 MB - worker 1
>> downloaded segment:  video_seg_720.ts None 306 KB - worker 0
>> downloaded segment:  video_seg_718.ts None 1.0 MB - worker 4
>> downloaded segment:  video_seg_719.ts None 717 KB - worker 2
`

![image](https://user-images.githubusercontent.com/64795789/99026659-7143ce00-25a6-11eb-8ab2-e30a798b264a.png)


Normally they would need to be canceled and reload via refresh URL.
Is it possible to auto cancel and refresh url / downlad that specific video again?

5. For fiels that error out would it be possible to do the same as per point 4? or try to download again a 2nd time beofe do like in point 4, if possible at all.

**Comment by pyIDM** [comment]
@quamt 
i didn't see any error in the above log, which means the download link still valid
just be aware that at 99% all segments should be downloaded completely and then ffmpeg starts processing segments, and sometimes ffmpeg takes a time as for the example you showed above, the video is encrypted hls with 1448 segments, it will take time in decryption and processing all these segments into one file

still your request is a good idea to auto refresh expired url, but this is not an easy thing to implement which will take a time to do it

**Comment by quamt** [comment]
@pyIDM The problem is that it sticks at 99%. I let it run for 2 hours and still the same.
There is no message in the log except the once above. 
Checking in the Task manager there is nothing either. 
Only thing that helps is cancel, refresh url and try redownload.
Anywhere else I can check what's *frozen*?

**Comment by pyIDM** [comment]
@quamt 
what was the video status when it gets stuck? is it "processing" or downloading?
status is marked below
![image](https://user-images.githubusercontent.com/58998813/99144416-9fd0b000-265d-11eb-9eea-345a331fa6b1.png)

**Comment by quamt** [comment]
@pyIDM It shows downloading.
