### ISSUE TITLE
Feature request: Clearer button for Playlist Download Window

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#210]
**Problem:**
The Playlist Download Window is hard to find because the button is nowhere near the playlist, has no label, and looks like a standard 'options' button that has nothing to do with a playlist.

**Solution:**
I think the button should be over on the left next to the playlist (just above or below) and should have a text label like "Playlist options".

**Comment by pyIDM** [comment]
@Mr-Personality 
Thanks for this suggestion, will think of an appropriate solution

**Comment by firedm** [comment]
Done in release 2021.3.18
