### ISSUE TITLE
AppImage - Linux portable release [follow up]

### ISSUE THREAD

**Issue by firedm** [firedm/FireDM#211]
This issue is made to keep tracking of making AppImage 

advantages as quoted from https://github.com/AppImage/AppImageKit:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others).
- One app = one file = super simple for users: just download one AppImage file, make it executable, and run.
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with appimaged
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the AppImageHub central directory of available AppImages
- Can double as a self-extracting compressed archive with the --appimage-extract parameter

**Comment by pyIDM** [comment]
Started with a ready made python AppImage from https://github.com/niess/python-appimage

get python 3.8 and unpack it:
```
wget https://github.com/niess/python-appimage/releases/download/python3.8/python3.8.6-cp38-cp38-manylinux2014_x86_64.AppImage
chmod +x ./python3.8.6-cp38-cp38-manylinux1_x86_64.AppImage
./python3.8.6-cp38-cp38-manylinux1_x86_64.AppImage --appimage-extract
mv squashfs-root python3.8
export PATH="$(pwd)/python3.8/usr/bin:$PATH"
```

install packages:
`pip install --prefix="./python3.8/opt/python3.8" --ignore-installed  pyidm`

this will install all required packages inside extracted AppImage

rebuild AppImage again:
```
#!/usr/bin/env bash

# Grab AppImageTools
wget -nc "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
wget -nc "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
chmod +x linuxdeploy-x86_64.AppImage appimagetool-x86_64.AppImage

# Deploy
./linuxdeploy-x86_64.AppImage \
   --appdir AppDir \
    -i ./icon.png \
    -d ./pyidm.desktop \
    --custom-apprun ./AppRun \
    --output appimage
```

Problems:
- tk version bundled in Python3.8xx.AppImage is 8.5 which is buggy and doesn't work as expected with pyidm, however i managed to copy tkinter, tk, tcl files version 8.6 from my production Arch linux to replace version 8.5 in extracted appiamge with some tweaking it works.
- after build the extracted AppImage again and try to execute on fresh installed ubuntu , it complained it can not find libcurl, still can't solve this problem.


will look into https://appimage-builder.readthedocs.io/en/latest/index.html

**Comment by pyIDM** [comment]
to solve missing libcurl problem, i copied libcurl.so.4 from /usr/lib to AppDir/usr/lib and set environmental variable for libcurl in AppRun shell script

```
# libcurl path
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/"
```

full AppRun script:
```
#! /bin/bash

# Export APPRUN if running from an extracted image
self="$(readlink -f -- $0)"
here="${self%/*}"
APPDIR="${APPDIR:-${here}}"

# Export TCl/Tk
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcl8.6"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tk8.6"
export TKPATH="${TK_LIBRARY}"

#path
echo "${APPDIR}"

export PATH="${APPDIR}/python3.8/usr/bin:${APPDIR}/python3.8/usr/lib:/home/mahmoud/python-appimage/working/AppDir/python3.8/opt/python3.8/lib/python3.8/site-packages/:$PATH"

# libcurl path
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/"


# Export SSL certificate
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

# Call the entry point
for opt in "$@"
do
    [ "${opt:0:1}" != "-" ] && break
    if [[ "${opt}" =~ "I" ]] || [[ "${opt}" =~ "E" ]]; then
        # Environment variables are disabled ($PYTHONHOME). Let's run in a safe
        # mode from the raw Python binary inside the AppImage
        "$APPDIR/opt/python3.8/bin/python3.8" "$@"
        exit "$?"
    fi
done

# Get the executable name, i.e. the AppImage or the python binary if running from an
# extracted image
executable="${APPDIR}/opt/python3.8/bin/python3.8"
if [[ "${ARGV0}" =~ "/" ]]; then
    executable="$(cd $(dirname ${ARGV0}) && pwd)/$(basename ${ARGV0})"
elif [[ "${ARGV0}" != "" ]]; then
    executable=$(which "${ARGV0}")
fi

# Wrap the call to Python in order to mimic a call from the source
# executable ($ARGV0), but potentially located outside of the Python
# install ($PYTHONHOME)
(PYTHONHOME="${APPDIR}/opt/python3.8" exec -a "${executable}" "$APPDIR/opt/python3.8/bin/pyidm" "$@")
exit "$?"

```

built a new AppImage and tried on ubuntu 20.04, now it gives new error, more tests to be done

link of latest PyIDM appimage at: https://github.com/pyIDM/PyIDM/releases/download/extra/PyIDM-x86_64_19.1.2021.AppImage

**Comment by pyIDM** [comment]
used https://appimage-builder.readthedocs.io/en/latest/index.html and managed to build an AppImage and run successfully on ubuntu and Manjaro

https://github.com/pyIDM/PyIDM/releases/download/2021.1.7/PyIDM-2021.1.7-x86_64.AppImage

**Comment by wada3n** [comment]
Just want to honestly say the software is incredibly special!
It is a masterpiece, especially after the release of the portable AppImage on Linux.

**In short it is amazing!**

thank you very much.

**Comment by pyIDM** [comment]
> Just want to honestly say the software is incredibly special!
> It is a masterpiece, especially after the release of the portable AppImage on Linux.
> 
> **In short it is amazing!**
> 
> thank you very much.

Thanks a lot @wada3n  :+1:

**Comment by tazihad** [comment]
this is truly great app. Alll we need is an extension like IDM on windows which can detects and download file from net

**Comment by pyIDM** [comment]
> this is truly great app. Alll we need is an extension like IDM on windows which can detects and download file from net

Thanks @tazihad 
agree, an extension is required, hope to make one soon
