### ISSUE TITLE
Faile to refresh url for Proxmox VE 6.3 ISO Installer.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#218]
If I stopped the downloading of [Proxmox VE 6.3 ISO Installer](https://www.proxmox.com/en/downloads/category/iso-images-pve) and let FireDM refresh the URL after a period of time to download it again. I find that [an error URL](https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=551&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=903917154b5591e9fed49cefd37c0fea) and filename will be generated. See the following screenshot for detailed info:

![image](https://user-images.githubusercontent.com/11155854/107747995-53c40300-6d53-11eb-9921-d03e1820fab8.png)

**Comment by firedm** [comment]
@hongyi-zhao 
This because the link became expired, 
i think the server create a temporary link that expires after a period of time 
i believe there is nothing FireDM can do
