### ISSUE TITLE
How to download 2 or more videos not in a playlist?

### ISSUE THREAD

**Issue by deepinsource** [firedm/FireDM#219]
https://www.youtube.com/watch?v=pRPvbma9meA
https://www.youtube.com/watch?v=f7MzFfuNOtY

How to download 2 or more videos not in a playlist without needing to add one by one?

**Comment by firedm** [comment]
@deepinsource 
if you mean batch download, this will be added to FireDM in future release, e.g. by adding multiple urls or pass a text file with multiple urls,

**Comment by firedm** [comment]
Added batch download feature to [latest release of FireDM](https://github.com/firedm/FireDM/releases/tag/2021.7.25)
