### ISSUE TITLE
Feature request: monitor URLs on clipborad for all protocols supported by libcurl.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#220]
I noticed that FireDM can't capture the ftp link from the clipboard, e.g., this one: ftp://imgs.mpdn.fun/imgs/lede/x86.plus/2021-02-15__03-21-29--daily/openwrt-x86-64-generic-squashfs-combined-efi.img.gz. So, I recommend monitoring URLs on the clipboard for all the protocols that `libcurl` supports.

Regards,
HY

**Comment by firedm** [comment]
@hongyi-zhao 
This is because it monitor only links starts with http
i should expand this to include different url patterns

will add this feature soon

**Comment by hongyi-zhao** [comment]
Thanks. I suggest monitoring all protocols supported by libcurl.

**Comment by firedm** [comment]
> Thanks. I suggest monitoring all protocols supported by libcurl.

Agree

**Comment by firedm** [comment]
Done,
included http, https, ftp, ftps, and file schemes
