### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 10

### ISSUE THREAD

**Issue by flyingcatt3** [firedm/FireDM#222]
I ran the command `pip install -r requirements.txt` and received this following error:
`Collecting pycurl (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/50/1a/35b1d8b8e4e23a234f1b17a8a40299fd550940b16866c9a1f2d47a04b969/pycurl-7.43.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Please specify --curl-dir=/path/to/built/libcurl
`
`
Command "python setup.py egg_info" failed with error code 10 in C:\Users\jones\AppData\Local\Temp\pip-install-xoa3ssys\pycurl\`

BTW I use the latest release of FireDM and Python 3.6.8.

**Comment by firedm** [comment]
@flyingcatt3 

this error caused by pycurl not installed correctly, please follow steps in below link to install it
https://github.com/firedm/FireDM#note-for-pycurl-
