### ISSUE TITLE
yt-dlp Support

### ISSUE THREAD

**Issue by zettimetti** [firedm/FireDM#224]
Drop youtube-dlc support and add support for yt-dlp, it's a good idea

Becuase the last release of youtube-dlc is 2020.11.11-3 and the last release of yt-dlp is 2021.03.03.2

Link to yt-dlp github: https://github.com/yt-dlp/yt-dlp

**Comment by nero-0** [comment]
+1 for this.

**Comment by firedm** [comment]
No problem adding yt-dlp
I am still not sure about youtube-dlc if it will be discontinued or not
