### ISSUE TITLE
Completion auto-actions feature!

### ISSUE THREAD

**Issue by wada3n** [firedm/FireDM#225]
Salam 3alaykom,
Thank you, dear brother, for this wonderful achievement.
I have a simple request which is to add "On Downloads done" feature.
Such as exiting the App, running a certain commond and most importantly Shutdown.

Sometimes I put certain downloads and go out or go to sleep at night, so I need to turn off the device right after the downloads finishes.

**Comment by firedm** [comment]
@wada3n 
wa3alaykom alsalam,
thanks a lot.
No problem, i will try to add this feature in future releases

**Comment by wada3n** [comment]
This is a very nice addition, my dear brother @firedm.
Actually I think adding a Checkbox is better than scheduling shutdown and canceling it in current implementation.
Thanks again.

**Comment by firedm** [comment]
> This is a very nice addition, my dear brother @firedm.
> Actually I think adding a Checkbox is better than scheduling shutdown and canceling it in current implementation.  
> Also, I think that adding such a feature in the settings will be easier for general use than in the right-click menu!
> What do you think?

i will consider this, have to do some testing first

**Comment by firedm** [comment]
@wada3n 
Added shutdown-pc and on completion command to Settings, Note this will only executed if all items in Downloads tab completed downloading
if any item have another status, e.g. cancelled it won't shutdown pc
![image](https://user-images.githubusercontent.com/58998813/112970107-25a55180-914e-11eb-877b-2de696d057f9.png)

on other hand i left the right click menu options to set individual items independently, e.g. shutdown computer when an item completes downloading regardless other items completed or not.
![100](https://user-images.githubusercontent.com/58998813/112971230-4f12ad00-914f-11eb-8cc0-5483ee97ce26.png)

**Comment by firedm** [comment]
Great, closing this issue
