### ISSUE TITLE
Contrats.... again!

### ISSUE THREAD

**Issue by PySimpleGUI** [firedm/FireDM#228]
Hiya!

Hey, more congratulations are in order, clearly!

I like the new brand name.

Is the icon on the account an official logo?  You might want to put it on your readme so that it's visible when someone goes to your repo.  Just a suggestion.  Nothing more nor less.

I'm so happy to see you're getting some rewards for your investment of time and energy.

**Comment by firedm** [comment]
@PySimpleGUI 
Thanks a lot for your nice words, wish you the best in your life

> Is the icon on the account an official logo? You might want to put it on your readme so that it's visible when someone goes to your repo. Just a suggestion. Nothing more nor less.

good idea :+1:

**Comment by PySimpleGUI** [comment]
Thank you for the system tray help!  It was very valuable and I've made some great progress thanks to your aid.  I really appreciate it Mahmoud.

**Comment by firedm** [comment]
you're most welcomed :+1:
