### ISSUE TITLE
Various interface improvements

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#229]
First of all, I LOVE this program! Thank you for it! Also I'm SO pleased that you changed the name! I've said before that I hated the name "PyIDM"!

Some humble suggestions for improvements to the user interface:

**Problem 1:**
I sometimes want to quickly turn off clipboard monitoring, just while I'm doing other stuff

Solution:
Nice big button on the Home screen to toggle clipboard monitoring.

**Problem 2:**
In the Downloads screen, the only way to select multiple items is by clicking the checkboxes in the thumbnail. But this seems a little unusual and doesn't look neat. I expect to click on them anywhere and have them select.

Solution:
It would feel more natural and easy (and attractive) to remove the checkboxes, and let you select items simply by left-clicking anywhere on the items and they turn blue, using the shift key to select

**Problem 3:**
I'm not sure how to delete multiple items. I can select multiple, but when I right click, there's no option to "Delete selected"

Solution:
There should be an option when you right-click to "Delete selected items"

**Problem 4:**
The scrollbar in the Download screen is very thin, making scrolling unnecessarily difficult to get hold of

Solution:
Can it be wider please?

**Problem 5:**
There is no way to "queue" multiple downloads. I have to paste each one and wait for each one to parse before copying the next

Solution:
On the Home screen, add the word "Mode:" with two options below:
  ☑ Single URL (allows playlists)
  ☐ Queue multiple URLS

If "Queue" mode is selected, the area on the left changes from showing playlists, to showing a queue of individual videos. These disappear from the queue when you click "Download".

**Problem 6:**
I've mentioned this before but for me (and others) the destination folder is a really important field that I want to be able to change quickly. Everything I download goes to a different place. The button to change it is currently too small.

Solution:
Destination Folder is an important field and should go at the top under the URL. You can edit it by clicking anywhere on it

**Problem 7:**
Only a minor issue but when you "Clear completed", the scrollbar stays where it was and you have to manually scroll up through blank space to get to the remaining items

Solution:
After "Clear completed", automatically scroll back to the top

Thanks! :-)

Also, I'm a logo/graphic designer. If you need a logo or graphics I'd be happy to help.

**Comment by firedm** [comment]
@Mr-Personality 
these are great suggestions :+1: 
 

> Problem 3:
I'm not sure how to delete multiple items. I can select multiple, but when I right click, there's no option to "Delete selected"

after selecting items you can click on the delete button on top-right corner of downloads tab, popup will show to write the word "delete" to confirm deletion
however,  it is more natural to let options in right click menu to work on all selected items

> Problem 7:
Only a minor issue but when you "Clear completed", the scrollbar stays where it was and you have to manually scroll up through blank space to get to the remaining items

this just recently fixed, didn't push changes yet to github

for other suggestion, will work on them and reference this issue number in commit messages

**Comment by Mr-Personality** [comment]
Thanks so much! :-) It's a great application!

**Comment by firedm** [comment]
@Mr-Personality 
check latest version 2021.4.3 for some interface changes:
Folder has an icon to choose location, also you can click and modify path directly, and there is a button to show recent locations.
you can naturally select items in downloads tab by clicking an item, also multiple selection using control and shift keys are supported.

**Comment by Mr-Personality** [comment]
This is GREAT! Thank you! :-)

Only a minor problem with the change: The blue color used for the selection doesn't match my theme. Perhaps it could use the 'side button' color or 'progressbar' color of whatever the theme is? (Or  the Windows theme selection color?)

The controls for the destination folder are a lot better. I still wish it was at the top, or perhaps under the Name? It feels like the Name and Folder should be together because these two are changeable options, while the other two are just information.

**Comment by Mr-Personality** [comment]
Also, I like how you can change the 'Folder' by just clicking in the box. Could this also be done for the 'Name' box? That's the one I would want to change manually more often.

**Comment by Mr-Personality** [comment]
While I'm here, a few other (very minor) issues, not very important...

1. When items are selected in the list, I would love to be able to hit the DELETE key to delete them.
2. I found that items I deleted in the list kept reappearing over and over. However, I solved this problem by forcing the program to Run as Administrator (Win 7) and that no longer happens.
3. It would be great if the buttons had a 'rollover' state. Only a very minor detail but this makes it clear that a button can be pressed. The simplest form of a rollover is just a colored rectangle behind the button. A good color to use would be the 'side button' theme color only made 70% more light. (White could be overlayed with 70% transparency?)

**Comment by firedm** [comment]
> Only a minor problem with the change: The blue color used for the selection doesn't match my theme. Perhaps it could use the 'side button' color or 'progressbar' color of whatever the theme is? (Or the Windows theme selection color?)

sure, it should be added to themes color to prevent interfering with other widgets' colors

> The controls for the destination folder are a lot better. I still wish it was at the top, or perhaps under the Name? It feels like the Name and Folder should be together because these two are changeable options, while the other two are just information.

Moving folder under name will be more natural.

**Comment by firedm** [comment]
> Also, I'm getting a lot of YT videos that won't download as they appear as html files. I'm sure you willl update youtube-dl soon.

youtube-dl included with every release is the latest version at the time of the release, also you can check for update from settings it will find the newest version and install it for you

also, can you mention any youtube link doesn't work for testing, there might be a problem with certain links and needs to be fixed

> I found that items I deleted in the list kept reappearing over and over. However, I solved this problem by forcing the program to Run as Administrator (Win 7) and that no longer happens.

i guess setting files are located in a folder that needs admin power, maybe if you put FireDM in another folder away from c: drive it will be ok

**Comment by Mr-Personality** [comment]
Thanks!

The YouTube videos that don't download at the moment seems to be anything in a playlist. Random example:
https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10

**Comment by firedm** [comment]
> Thanks!
> 
> The YouTube videos that don't download at the moment seems to be anything in a playlist. Random example:
> https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10

Just test it and it works:
![image](https://user-images.githubusercontent.com/58998813/113506385-e0659300-9544-11eb-9fc2-d726f7493bd9.png)

**Comment by Mr-Personality** [comment]
This is what I get when I try:

![what i get](https://user-images.githubusercontent.com/18085936/113786798-ca68f580-9731-11eb-8437-c57cae3d5fcd.png)

**Comment by firedm** [comment]
@Mr-Personality 
I guess most of problems here and features already set in latest release, closing this issue
regarding youtube links that doesn't work, it is better to open new issue and copy the log to be able to solve it
