### ISSUE TITLE
Confirm multiple Warning with one click

### ISSUE THREAD

**Issue by quamt** [firedm/FireDM#231]
At the moment if there are warning they have to be confirmed one by one.

Is it possible to confirm all at once instead?

**Comment by firedm** [comment]
> At the moment if there are warning they have to be confirmed one by one.
> 
> Is it possible to confirm all at once instead?

I agree, it is too annoying, will try to combine these warning together if possible

**Comment by firedm** [comment]
options will be available in next release:

disable popup windows in settings

![image](https://user-images.githubusercontent.com/58998813/121303256-2a7b4400-c8fb-11eb-8dfc-3ba872395a56.png)

Also added "Don't show this message again" checkbox
![image](https://user-images.githubusercontent.com/58998813/121303377-4a126c80-c8fb-11eb-8b4d-b02468502651.png)
