### ISSUE TITLE
system tray icon in plasma

### ISSUE THREAD

**Issue by ahmed-tasaly** [firedm/FireDM#232]
the system tray icon doesn't appear but only a small empty spacing which doesn't respond on click or right click

Distro:Arch-based

thanks in advance

**Comment by firedm** [comment]
@ahmed-tasaly 
systray icon require GTK+3 to run properly, which is not installed by default on plasma KDE

**Comment by ahmed-tasaly** [comment]
@firedm 
gtk3 is installed

**Comment by wada3n** [comment]
Same here in manjaro with Gnome desktop environment!

**Comment by firedm** [comment]
@ahmed-tasaly 
@wada3n 
will try to find an alternative systray icon package for linux

**Comment by ahmed-tasaly** [comment]
@wada3n 
Assalam Alaykom
Try using this extension 
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by wada3n** [comment]
> @wada3n
> Assalam Alaykom
> Try using this extension
> https://extensions.gnome.org/extension/615/appindicator-support/


Wa3alykom assalam, Ahlan Akhi,
I'm already using this extension, and the systray icon never appears.

**Comment by ahmed-tasaly** [comment]
@firedm 
I was using the appimage version.
I thought to try the py version using pip as you stated .
and the icon did appear in kde plasma.

**Comment by firedm** [comment]
@ahmed-tasaly 

> I was using the appimage version.
> I thought to try the py version using pip as you stated .
> and the icon did appear in kde plasma.

Good to know it is the AppImage problem, maybe there is an easy fix for that, will do some more troubleshooting

**Comment by ipkpjersi** [comment]
I'm experiencing this issue on Ubuntu 20.04 with Xfce 4.14 which definitely does have GTK3. This happens with `python3 -m firedm` as well as the AppImage version.

Not really a huge problem as it works fine without the tray icon but it would be nice to have. :+1:

**Comment by firedm** [comment]
> The tray icon works for me on Ubuntu 20.04 with Xfce 4.14 which does have GTK3. It works with `python3 -m firedm` as well as the AppImage version.

@ipkpjersi 
great news AppImage works for you, thanks for reporting

**Comment by PySimpleGUI** [comment]
I'm using Mint to test my releases.  I was using WinFx but have run into a snag where my shared folder ha stopped working when using VMWare, so back to Mint I've gone.

I've been successful in getting pystray working under windows, but I've still not managed to get a Linux implementation working.  Do you have any tips for a direction I should go?

BTW, I solved the "click the icon" crash by adding this line of code:

```python
        pystray.Icon.__call__ = default_action_callback
```

where `default_action_callback` is the function I would like called when the tray icon is clicked.  It would be ideal to detect double click within pystray, but I don't see how to do that at the moment, so I'll add the detect to my code.

**Comment by firedm** [comment]
@PySimpleGUI 
running below code on ubuntu based distros (pop os in my case) will result in ValueError: signal only works in main thread
but after batching file: .../site-packages/pystray/_util/gtk.py,

just by removing or commenting line no.68 :
`signal.signal(signal.SIGINT, signal.SIG_DFL)`

 it works with no issues

```
import tkinter as tk
import threading
from pystray import Icon, Menu, MenuItem
from PIL import Image, ImageDraw

# create a transparent image
img = Image.new(size=(32, 32), mode='RGBA', color='#0000')

# draw circle
draw = ImageDraw.Draw(img)
draw.ellipse([0, 0, 32, 32], outline='blue', fill='red', width=5)

icon = None
root = tk.Tk()


def st():
    # icon.stop must be called from main thread, will use root.after for this 
    options_map = {'Show': lambda: print('show_main_window'), 'Quit': lambda: root.after(1, quit)}
    
    items = []
    for option, callback in options_map.items():
        items.append(MenuItem(option, callback, default=True if option == 'Show' else False))

    menu = Menu(*items)
    global icon
    icon = Icon('myAPP', img, menu=menu)
    icon.run()
    
def quit():
    print('quitting')
    icon.stop()
    root.destroy()

threading.Thread(target=st).start()

root.protocol("WM_DELETE_WINDOW", quit)
  
root.mainloop()
```
hope this could help

**Comment by firedm** [comment]
also if you still need to handle interrupt switch properly (ctrl-c from terminal to quit your application), you can register a signal handler in your main thread

adding below lines before root.mainloop() in the above code

```
import signal
signal.signal(signal.SIGINT, lambda *args: quit())
```
