### ISSUE TITLE
pre_process_hls()> error

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#233]
I've been using FireDM with www.bbc.co.uk/iplayer and it's worked great.

Today I get two errors when I try it:

`pre_process_hls()> error: 'NoneType' object has no attribute '_downloader'`

Then

```
controller: too many connection errors
maybe network problem or expired link
```

**Comment by firedm** [comment]
@Mr-Personality 
this is a bug, it happen if you use yt-dlp, please select youtube-dl from 
Settings> Video / Audio>select video extractor engine>youtube_dl
then try again and let me know if it works for you

**Comment by Mr-Personality** [comment]
Oh cool! This simple change fixed the problem! Thanks dude! :-)

**Comment by firedm** [comment]
Fixed in latest release, both youtube-dl yt-dlp are working fine now
