### ISSUE TITLE
PyIDM和FireDM能否增加中文简体版和插件以代替浏览器的下载

### ISSUE THREAD

**Issue by chyd8899** [firedm/FireDM#234]
感谢作者制作这么好用的PyIDM和FireDM！
因不是每个人的英文都很好，使用起来有点雾里看花，因此，希望能增加简体中文；
另外，希望作者能在软件中增加一个插件，像IDM一样代替浏览器的下载；能支持ed2k和磁力链接就可以完全替代迅雷和IDM了。
衷心的感谢作者！再接再厉！

**Comment by 0x5c0f** [comment]
提问之前希望还是能看下历史的Issues, 国际化：#227 ，扩展： #109

**Comment by firedm** [comment]
Duplicate for issue #227
