### ISSUE TITLE
Improve the use of the program

### ISSUE THREAD

**Issue by JohnPlanetary** [firedm/FireDM#235]
1. Be able to paste the URL using the right click of the mouse.
2. Be able to click some icon and clear the URL pasted/ copied from clipboard without confirmation dialogue.
3. Have a new lateral option "Update" instead being buried in the settings.
4. Be able to delete the file from the screen on the "Downloads" by just clicking in some delete icon there in the screen near to the file. And have a option to be able to delete without the confirmation dialogue.

Thanks for these great program!

**Comment by firedm** [comment]
@JohnPlanetary 
These are good suggestions, will try to add them in next releases

**Comment by JohnPlanetary** [comment]
@firedm
Thanks for reading and accepting to take these suggestion into account in further improvements.

**Comment by firedm** [comment]
features already added to the latest version
