### ISSUE TITLE
Native File Chooser Dialog

### ISSUE THREAD

**Issue by wada3n** [firedm/FireDM#236]
Hello, brother.
Can the File Chooser Native be added to the App, instead of the implemented here?
Especially since this latter does not support Arabic (RTL), for example,
and the theme appears somewhat foreign to the system theme.
![hfh](https://user-images.githubusercontent.com/13304792/114059197-087a2c80-988c-11eb-8b10-fe865834bc85.png)

Thanks again and again for your great job.

**Comment by firedm** [comment]
@wada3n 
I agree
the builtin file chooser for tkinter looks horrible plus the RTL support problem
i will try to find a better way to do it.

**Comment by firedm** [comment]
Done in latest release:
used alternative file choosers (GTK, zenity, or kdialog) on linux instead of tkinter filechooser
