### ISSUE TITLE
Date and time are wrong for saved files

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#237]
For many of the videos I downloaded (perhaps all) I've noticed the date and time are wrong.

Instead of showing today's date, it shows some older date - sometimes just a few weeks ago, sometimes last year, or two years ago.

ver2021.4.3
Windows 7 x64

**Comment by firedm** [comment]
@Mr-Personality 
this is the file timestamp on the server, you can disable this behavior by unchecking option at: 
Settings>General>write "last modified" timestamp to downloaded file

![image](https://user-images.githubusercontent.com/58998813/114624441-fa277880-9cb0-11eb-8c88-4011d4632518.png)

**Comment by Mr-Personality** [comment]
Ah, thank you for explaining this. I would really love this feature if the date always matched the upload date, but sadly it doesn't and often just seems random. Maybe this should not be the default behavior? Just a suggestion.

**Comment by firedm** [comment]
corrected "timestamp" default behavior
