### ISSUE TITLE
Support TikTok Videos

### ISSUE THREAD

**Issue by JohnPlanetary** [firedm/FireDM#238]
It would be nice for the FireDM to also support the download of TikTok videos.

Thanks for the great program!

**Comment by Dauth** [comment]
@firedm 

i could help to extend this feature. Just wanted to know where is logic code for recognition of url?

**Comment by firedm** [comment]
@Dauth 
FireDM depend on youtube-dl to fetch video information from a website, after that it uses multi-connection libcurl to download video files.

and regarding how the url get processed, it is as follows:
1- user write url in gui's url entry
2- gui call [_process_url](https://github.com/firedm/FireDM/blob/2fbf04c33b7b95cb24db25eb22aab8ae9779428d/firedm/controller.py#L244) method from "controller.py" file.
3- process_url method will call [_create_video_playlist](https://github.com/firedm/FireDM/blob/2fbf04c33b7b95cb24db25eb22aab8ae9779428d/firedm/controller.py#L450) method, which in turn ask youtube-dl to look for videos and if videos available it will get processed.
4- controller will send a list of available videos back to gui to display them.
5- user will select a video and a stream quality and hit download
6- [_download ](https://github.com/firedm/FireDM/blob/2fbf04c33b7b95cb24db25eb22aab8ae9779428d/firedm/controller.py#L940)method in "controller.py file" will handle the download

**Comment by Dauth** [comment]
@firedm 

sure thanks look to me it is more of adding additional extractors in youtube-dl instead. will work from there instead.
