### ISSUE TITLE
Low volume for youtube videos

### ISSUE THREAD

**Issue by Kunumi-Gab** [firedm/FireDM#239]
Hello!

I downloaded some videos using FireDM, they have a pretty love volume compared to the youtube one, tryed with the manual audio select setting but i get same results.

**Comment by firedm** [comment]
@Kunumi-Gab 
thanks for reporting this broken link, 
are you running exe version of FireDM or from open source?


This is the link of ffmpeg 32 bit version which already included in FireDM windows release and it works on both windows 32 and 64 bit
https://github.com/firedm/FireDM/releases/download/extra/ffmpeg_32bit.exe


and this is the link for ffmpeg 64 bit version:
https://github.com/firedm/FireDM/releases/download/extra/ffmpeg_64bit.exe

if you have a problem with newer versions, a bug report should be reported at https://www.ffmpeg.org/ or trying their forums

**Comment by Kunumi-Gab** [comment]
Hello! Thanks for the ffmpeg link, but i get the same problem, low volume, gonna try asking in ffmpeg forums
