### ISSUE TITLE
Various interface improvements for the Downloads screen

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#240]
1. Ability to delete selected items by hitting the delete key

2. The delete confirmation requires you to type 'delete'. This seems excessive since you're not actually deleting files. I would change the confirmation to a simple click 'OK' or hit Enter.

3. The percentage complete on the right is quite small and hard to see. Could it be made bigger?

4. It would also be useful if the percentage was also added on the left, to the left of the information showing downloaded data/filesize. It's usually the first thing users want to see.

5. When you roll over the pause button, it doesn't change, this makes it not very clear if it's actually even a button. I'm still not sure if the icon to the left of it is a button or what it does. Rollover tooltips would also help.

6. When you've paused an item with the pause button and want to resume, you would expect to be able to click the same button again to resume, but actually this doesn't work and you have to right click > Resume. It would be useful if when you pause, the pause button turns into a 'Resume' button, perhaps with a 'play' icon.

7. It would be great to have a MASTER PAUSE/RESUME button somewhere, to pause EVERYTHING. (Either on the Downloads screen or on the Home screen.) Why? One reason is sometimes you want the bandwidth free for other things. But also, some sites (like iPlayer) only allow you to access 1 video at a time - this means that if you want to add multiple videos, you have to keep going to the Download screen and pausing each one then reurning to the Home screen to add the next item, then finally you have to resume them all when you're ready to begin downloading.

**Comment by firedm** [comment]
good suggestions @Mr-Personality, will try to implement them in future releases

**Comment by Mr-Personality** [comment]
Great, thanks for taking the time to read it! :-)

**Comment by firedm** [comment]
All Done in the latest release
