### ISSUE TITLE
System Tray Use...... 

### ISSUE THREAD

**Issue by PySimpleGUI** [firedm/FireDM#241]
Hi there!  Congrats on the smashing success!

I've played with pystray a few times and keep running into the problem of it needing to be run in the main thread.  It would be ideal if I could run it as a thread and then have it communicate with my mainthread.

I'm curious how you've integrated tkinter and pystray together.  Was there any particular magic involved?

**Comment by firedm** [comment]
@PySimpleGUI 
on windows, there is nothing special, you can run from a thread but you should terminate systray icon from main thread 

unfortunately pystray doesn't run on linux or mac from a thread, i just used [Gtk statusIcon](https://github.com/firedm/FireDM/blob/2fbf04c33b7b95cb24db25eb22aab8ae9779428d/firedm/systray.py#L61) if installed on the system,

here is a minimal code to run on windows:

```
import tkinter as tk
import threading
from pystray import Icon, Menu, MenuItem
import io, base64
from PIL import Image

i = b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAeCAYAAABNChwpAAAACXBIWXMAAAd0AAAHdAHxbc2KAAAA\nGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAfpJREFUSInVlj1LW1EYx383L6aD\nFPwCXQKi30KwBedOxaUUh0opCkYUt3boKmpoqJLWNGIbLSUR3yYlcwf7CTpUEIeAk+JgXjrcc+Dw\n5Nzk5PbG0gf+Q56X8/uf3JdzIVw8BqrAtVIVmAi5Vs/xGqgDLaEmkBG9Y8ApUAAeRgGft4Clloz+\nX0b+TT/gP5Rk/q2auTVyK1HDD4CU0qGlvix+r0YJ31dgHSmV63Rp1sLA5ywLHQEPLL0DQLmDgWyv\n8IxlkYoCAXjAO/zr7Rkm9gIMvO8FPmNZoGzA48Bno7YuTNj+iS+u8Cn8Z9oc/g4kA+BaH4GY6kmq\nGdmz2A3+AmiIoW8OcJuJOLBt6VkIgj+3wHeAhCNc65NhIgHsinoTeCXhk7S/Xr8a8JgjXGtTmCiJ\nekNtGICnwJ1oKBlwD/8mc4XbTMSBoqjXgWcANVEoqgG983wIuFZemNgS9RrATyNRMOAesPEXcNsj\nKu+jM4A08AH/2dduPSAXAVwrZ5iIAbP4Z0OagMhGCNdyPgum+wDXeilhMZkARl2dhogRFwOeJRdV\ntK2dcGkS0QJOAmrjXebbNhzGQBN4ElBrOMx3dnTfYTPQ6iOv8V8YaP5rA5d9NPDbpWkIuCD4bVbv\nMCs/aEydA4OuToeBY+BKyfxY6cXADf6RWwEe2Qb+AP3yZGXPWUKPAAAAAElFTkSuQmCC\n'

icon = None
root = tk.Tk()

fp = io.BytesIO(base64.b64decode(i))
img = Image.open(fp)

def st():
    # icon.stop must be called from main thread, will use root.after for this 
    options_map = {'Show': lambda: print('show_main_window'), 'Quit': lambda: root.after(1, quit)}
    
    items = []
    for option, callback in options_map.items():
        items.append(MenuItem(option, callback, default=True if option == 'Show' else False))

    menu = Menu(*items)
    global icon
    icon = Icon('myAPP', img, menu=menu)
    icon.run()
    
def quit():
    print('quitting')
    icon.stop()
    root.destroy()

threading.Thread(target=st).start()
  
root.mainloop()

```

**Comment by PySimpleGUI** [comment]
Thank you!  A GitHub feature addition of another emoticon for a comments reaction:
![image](https://user-images.githubusercontent.com/46163555/119226842-2072dc00-bad9-11eb-8b67-94758ab006a2.png)

Should include your avatar as a choice!

![image](https://user-images.githubusercontent.com/46163555/119226863-308abb80-bad9-11eb-9b1a-0e864db5d96b.png)
