### ISSUE TITLE
Feature Request : Custom File Name : Download video with 'channel Id' and 'uploader name' in video title. 

### ISSUE THREAD

**Issue by mohitmeanslove** [firedm/FireDM#247]
Please give option  to download video with title which includes channel URL, uploader name etc. This option does exist in other softwares. Thank You

**Comment by firedm** [comment]
@mohitmeanslove 
to understand your request, please post an example url / link and give further explanation

**Comment by mohitmeanslove** [comment]
OKAY. Let me make you understand  . In other software like Mediahuman youtube downloader ,one can download video with **custom FILENAME** i.e Channel URL and Channel Name whose video you are downloading ,   but there is no option like this in Firedm.
If you still don't understand then check this screenshot. Hope it will make you understand.


1)**Screenshot of Free Youtube downloader by DVDVIDEOSOFT**

![DVDSOFT](https://user-images.githubusercontent.com/84594515/120201020-99450700-c242-11eb-8529-767cdea7a815.png)

2)**Screenshot of Youtube downloader by MEDIAHUMAN**

![mediahuman](https://user-images.githubusercontent.com/84594515/120201026-9a763400-c242-11eb-8f1e-d9291fbbb7ba.png)

**Comment by mohitmeanslove** [comment]
> @mohitmeanslove
> to understand your request, please post an example url / link and give further explanation

OKAY. Let me make you understand  . In other software like Mediahuman youtube downloader ,one can download video with **custom FILENAME** i.e Channel URL and Channel Name whose video you are downloading ,   but there is no option like this in Firedm.
If you still don't understand then check this screenshot. Hope it will make you understand.


1)**Screenshot of Free Youtube downloader by DVDVIDEOSOFT**

![DVDSOFT](https://user-images.githubusercontent.com/84594515/120201020-99450700-c242-11eb-8529-767cdea7a815.png)

2)**Screenshot of Youtube downloader by MEDIAHUMAN**

![mediahuman](https://user-images.githubusercontent.com/84594515/120201026-9a763400-c242-11eb-8f1e-d9291fbbb7ba.png)
