### ISSUE TITLE
Running on command line

### ISSUE THREAD

**Issue by soulsucka** [firedm/FireDM#248]
Question: Is there a command line version of firedm?
Thanks

**Comment by firedm** [comment]
@soulsucka 

there is an option to run firedm without gui, in shell but still interactive to get user selections
try: `firedm --help` for available options

try this Example from shell:
`firedm 'https://www.youtube.com/watch?v=D_Vc_yDvU24' --nogui`

it will fetch all available quality streams from this video and ask you to select video and audio quality

example output:
![image](https://user-images.githubusercontent.com/58998813/120920146-b0aa4700-c6bd-11eb-9e98-d5e877a6fff5.png)

![image](https://user-images.githubusercontent.com/58998813/120920197-f6ffa600-c6bd-11eb-8d68-3c55784a763f.png)

There is a plan in future to download files with preset options without user intervention to be more suitable for firedm to run in a cron job

**Comment by firedm** [comment]
@candrapersada 
if you are using portable version for windows, 
run command line window "cmd.exe"
then `cd "path to firedm Folder"`
then try this:
`firedm --help`

it will show you available options 

example:
`firedm https://examplewebsit.com/examplefile`
file will be saved at your standard download folder, or last folder used by FireDM

you can use `"--output pathTomyfolder"` option to use "myfolder" as a download target or `"--output ."` to use current folder

**Comment by candrapersada** [comment]
but why error
![image](https://user-images.githubusercontent.com/36833664/132957384-9d67107e-86d9-4d97-8853-080f1353d18b.png)

**Comment by firedm** [comment]
> 
> 
> but why error
> ![image](https://user-images.githubusercontent.com/36833664/132957384-9d67107e-86d9-4d97-8853-080f1353d18b.png)



@candrapersada 
i confirm this is a bug, will try to solve it

**Comment by candrapersada** [comment]
how to use for playlist and quality video+audio?

**Comment by firedm** [comment]
> how to use for playlist and quality video+audio?

for playlist in command line:
- in interactive mode you can select one video, video quality, and audio quality thru interactive env like in [here](https://github.com/firedm/FireDM/issues/248#issuecomment-855372405)
example: `firedm -o . https://myvideoplaylisturl  --interactive`   
note: `-o .` used to select current folder as a download folder
- if you don't use --interactive flag like above, it will select the first video in playlist automatically, you can choose video quality only
  example: `firedm -o . https://myvideoplaylisturl  --quality 720p`

there might be some options added in the future to handle playlists properly

**Comment by candrapersada** [comment]
how to use select dash audio in command line
