### ISSUE TITLE
List of some features : Custom filename with channel ID/Uploader name and Add ''Download Automatically'' option

### ISSUE THREAD

**Issue by mohitmeanslove** [firedm/FireDM#253]
I'm making this thread to make developer understand in a much better way.

1)**Custom filename with channel ID/Uploader name** : Kindly provide the custom filename option so that uploader name and channel id etc will be added in file name.. This option has already existed in Mediahuman Youtube downloader.

Screenshot of  Mediahuman Youtube downloader
![120201026-9a763400-c242-11eb-8f1e-d9291fbbb7ba](https://user-images.githubusercontent.com/84594515/121128781-90a78e80-c849-11eb-9cce-1cfc465ddd28.png)

2) **Download Automatically** : Whenever someone copy a youtube link then file should be download automatically without any prompt. This option has already existed in Byclick Youtube downloader and Mediahuman youtube downloader.

Screenshot of Byclick youtube downloader.
![120233028-74688800-c272-11eb-9772-cacc8d29b88a](https://user-images.githubusercontent.com/84594515/121129039-f8f67000-c849-11eb-9bf1-e4964b8c47c5.png)

**Comment by firedm** [comment]
@mohitmeanslove 
we might add these features in future releases

**Comment by mohitmeanslove** [comment]
> @mohitmeanslove
> we might add these features in future releases

Waiting for future updates

**Comment by firedm** [comment]
Done adding custom video name templates in current version
auto file download with ctr-c will not be added
