### ISSUE TITLE
Detected as trojan/malware when scanned [FireDM version 2021.6.4.post1]

### ISSUE THREAD

**Issue by ArC1010** [firedm/FireDM#255]
While scanning FireDM version 2021.6.4.post1 exe file or the whole zip file for windows with antiviruses, some of them are detecting it as a malware/trojan. Can you or other contributors explain the reason ?
And what about the other versions ? Are all of them safe actually? 
Many of my known people are facing the same result while scanning with antivirus.
Please clarify the issue so that we can install safely. 
I am attaching the pictures and links of the scan results.
https://tinyurl.com/yz6wdrp3
![Screenshot 2021-06-13 184641](https://user-images.githubusercontent.com/85833084/121809398-3e67d280-cc7a-11eb-995e-e8502319f1ca.jpg)
![Screenshot 2021-06-13 184730](https://user-images.githubusercontent.com/85833084/121809401-40319600-cc7a-11eb-84d3-d63f89aa30a0.jpg)

**Comment by firedm** [comment]
@ArC1010 
from your attached [report](https://www.virustotal.com/gui/file/df6fc9940b6fe376d53ce5e5b45c264aa8f04eedf3351647afd7ac08092a509f/detection/f-df6fc9940b6fe376d53ce5e5b45c264aa8f04eedf3351647afd7ac08092a509f-1623091702), it is only [ONE] antivirus vendors that detect FireDM as a virus out of 69 other vendors.

Why this happens?
Think about it, if the whole 68 other vendors  report it as a clean file including big names like Kaspersky, Macafee, Symantec, etc..., this means it is simply a "FALSE POSITIVE" case, which means this antivirus engines mistakenly identify it as a virus which is not true.

How to solve this problem:
like what we did in the past, anyone can send a false positive report with attached FireDM sample to this vendor thru their website and they hopefully inspect the contents manually, then they will update their database to identify FireDM file signature as a safe content, but the problem will arise again with every new release " it will have different signature" and will be identified mistakenly as a virus again, and we have to report again and again, ...

or simply ignore it, and this is the route we prefer to take

if you still not comfortable to run exe version, you can run directly from source code it is just need to install python programming language on windows with some other stuff, you can find more details in readme file [here](https://github.com/firedm/FireDM#dependencies)

**Comment by ArC1010** [comment]
I understand the issue. Thanks a lot. @firedm
