### ISSUE TITLE
FireDM take longer time to load with every run as time goes on (Linux)

### ISSUE THREAD

**Issue by firedm** [firedm/FireDM#256]
Running FireDM on linux normally takes 3 seconds to fully load, however when closing application and run it again too many times it takes more time to load and adds up delay time with every run, e.g: it takes 3 sec. on first time, then 6 sec. on second time, then 9 sec, and it goes on to several minutes for FireDM to fully load gui and become responsive

if i restart linux system, FireDM load faster 3 sec. max, then again as time goes on it gets slow.

Root cause:
Spent a lot of time try to figure out the main cause and looking for a memory leak in FireDM, and found nothing wrong with the code
Fortunately, after long investigation, found a weird thing happen on my linux machine, there is 2 processes eats up 25 to 50% of my cpu when starting FireDM , both are (ibus-daemon, ibus-x11), the strange thing is FireDM doesn't call or use any of these processes
looking for a solution on internet, and found reports from users complaining about ibus, see here https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1766503

what is [ibus](https://help.ubuntu.com/community/ibus):

> The Intelligent Input Bus (IBus) is an input method framework for multilingual input in Unix-like operating systems. It's called "Bus" because it has a bus-like architecture.
You can use IBus to type in your own language in most GUI applications.

what and how to use ibus: http://www.studymongolian.net/technical/how-to-create-linux-input-method-editor/

ibus homepage on github: https://github.com/ibus/ibus
more on how ibus work as an input method: https://en.wikipedia.org/wiki/Input_method
example [video](https://upload.wikimedia.org/wikipedia/commons/6/6b/TypingChineseCharactersWithCangjieGedit383Ubuntu1310Screencast.webm) on typing chinease in Gedit ubuntu

temporarily fix:
killing both processes ibus-daemon, and ibus-x11  solved the problem

disable in gnome:
In Terminal:  `gnome-language-selector`
Open the Language tab, and there you can choose IBus or None.

https://askubuntu.com/questions/426094/is-ibus-necessary-on-ubuntu-13-10

system info:
operating system: Os: Linux - Platform: Linux-5.11.0-7614-generic-x86_64-with-glibc2.32 - Machine: x86_64
Distribution: ('Pop!_OS', '20.10', 'groovy')
Python version: 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0]

**Comment by firedm** [comment]
found related issue at: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2674

**Comment by firedm** [comment]
opened an issue at: https://github.com/ibus/ibus/issues/2324

**Comment by ipkpjersi** [comment]
@firedm Can you make the workaround for ibus in FireDM toggleable in Settings? I haven't noticed any slowdown and I'd be afraid restarting the ibus daemon could cause some issues when working around an issue I don't have.

**Comment by firedm** [comment]
@ipkpjersi 
you're right, it shouldn't be applied for everyone, will have an option to control this workaround and it will be disabled by default, only people who suffer from FireDM slow startup have to enable it.

**Comment by firedm** [comment]
as a follow up on this issue, will report the following for future reference

running ibus-workaround from a thread might raise:
```
  X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x80000b
  Serial number of failed request:  637
  Current serial number in output stream:  638
```
and it will prevent Application from starting properly, 
will have to apply workaround from main thread and use root.after to schedule an ibus restart

**Comment by firedm** [comment]
will close this issue as the applied workaround will be enough for now
