### ISSUE TITLE
alternative file choosers (error)

### ISSUE THREAD

**Issue by ahmed-tasaly** [firedm/FireDM#257]
**Aloha there** , **Assalam Alykom**

Since you added support for **zenity** and **kdialog** 

I can't use **browse** button anymore 
on pressing browse button the application stops

_NB : I use **archlinux** with **KDE-plasma** desktop environment -- I have both **zenity** and kdialog installed_

Thanks in advance

**Comment by firedm** [comment]
@ahmed-tasaly 
sorry to hear this, i will try to test it on Manjaro kde and see why this is happening

**Comment by firedm** [comment]
@ahmed-tasaly 
i just run FireDm AppImage on fresh installed Manjaro kde plasma version 5.15.2, kernel version 4.19.28-1-MANJARO, and it works, zenity already installed and found no application freeze

how are you running FireDm? from pip, opensource, or AppImage?

run this command in terminal and see if it works: `zenity --file-selection --directory --filename="non existing folder"`

**Comment by ahmed-tasaly** [comment]
@firedm 
I have tried it and no error 
**but** I have found something related 

the app force close only happen when **I change the theme** except for the default **dark** one

**Comment by firedm** [comment]
@ahmed-tasaly
wa-alykom alsalam

i will do more tests to investigate this problem

**Comment by firedm** [comment]
After more testing found out the following:
choosing another theme will restart gui, and it will create another mainloop, at this stage if we call gtk file chooser it will raise an error like: `Gdk-Message: FireDM.py: Fatal IO error 0 (Success) on X server :1` and application will crash, 
also when closing application it will quit the second loop only and the first one will still running causing application refuse to quit

fix:
already fixed both problems by removing the offending code in gui restart, also removed gtk file chooser and depend only on "zenity or kdialog" if installed

fix will be available on coming release

**Comment by ahmed-tasaly** [comment]
السلام عليكم 
شكرا شكرا جزيلا و جزاك الله خيرا على تعبك و برنامجك الرائع

**Comment by firedm** [comment]
العفو حبيبي تسلم

**Comment by candrapersada** [comment]
```
$ which zenity

which: no zenity in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
$ which kdialog
/usr/bin/kdialog
$ 
```
https://github.com/firedm/FireDM/issues/412#issuecomment-1001828114
