### ISSUE TITLE
Controller: too many connections errors, maybe network problem or expired link

### ISSUE THREAD

**Issue by rogerwindberg** [firedm/FireDM#259]
This error is happening to me several times. What I did to solve it was delete it from the queue and put it to download again.

![Screenshot_1](https://user-images.githubusercontent.com/69870624/123518736-a3a9c380-d67d-11eb-9be2-7ddc47c14144.png)

**Comment by firedm** [comment]
@rogerwindberg 
Thanks for reporting this,
this happening if there is a network problem at the time of download, if you have a look at "Log" tab at the time of downloading this file you might find more info on what actually happened.

if this happen again please copy text in the "Log" tab and paste it here to help identify the problem
