### ISSUE TITLE
Some themes , If you would like to add

### ISSUE THREAD

**Issue by ahmed-tasaly** [firedm/FireDM#261]
### السلام عليكم

I took this from my user_themes file then added bold to the names

{"**Gainsboro-SandyBrown-Teal**": {"MAIN_BG": "#DDDDDD", "SF_BG": "#F5A962", "SF_BTN_BG": "#3C8DAD", "PBAR_FG": "#125D98", "MAIN_FG": "black", "SF_FG": "#125D98", "SF_CHKMARK": "#125D98", "THUMBNAIL_BG": "#F5A962", "THUMBNAIL_FG": "#125D98", "THUMBNAIL_BD": "black", "PBAR_BG": "#d3d3d3", "PBAR_TXT": "#125D98", "ENTRY_BD_COLOR": "#F5A962", "BTN_BG": "#3C8DAD", "BTN_FG": "#DDDDDD", "BTN_HBG": "#F5A962", "BTN_ABG": "#F5A962", "BTN_AFG": "white", "HDG_BG": "#3C8DAD", "HDG_FG": "#DDDDDD", "SBAR_BG": "#DDDDDD", "SBAR_FG": "#125D98", "RCM_BG": "#DDDDDD", "RCM_FG": "#125D98", "RCM_ABG": "#3C8DAD", "RCM_AFG": "#DDDDDD", "TITLE_BAR_BG": "#3C8DAD", "TITLE_BAR_FG": "#125D98", "SEL_BG": "#F5A962", "SEL_FG": "black"}, "**Black_Grey_Shade-of-Pink**": {"MAIN_BG": "#444444", "SF_BG": "#171717", "SF_BTN_BG": "#EDEDED", "PBAR_FG": "#DA0037", "MAIN_FG": "#EDEDED", "SF_FG": "#EDEDED", "SF_CHKMARK": "#DA0037", "THUMBNAIL_BG": "#171717", "THUMBNAIL_FG": "#DA0037", "THUMBNAIL_BD": "white", "PBAR_BG": "#4e4e4e", "PBAR_TXT": "#DA0037", "ENTRY_BD_COLOR": "#171717", "BTN_BG": "#EDEDED", "BTN_FG": "black", "BTN_HBG": "#171717", "BTN_ABG": "#171717", "BTN_AFG": "#DA0037", "HDG_BG": "#EDEDED", "HDG_FG": "black", "SBAR_BG": "#171717", "SBAR_FG": "#DA0037", "RCM_BG": "#444444", "RCM_FG": "#EDEDED", "RCM_ABG": "#EDEDED", "RCM_AFG": "#DA0037", "TITLE_BAR_BG": "#EDEDED", "TITLE_BAR_FG": "black", "SEL_BG": "#171717", "SEL_FG": "#EDEDED"}, "**OffWhite-Blue**": {"MAIN_BG": "#DDDDDD", "SF_BG": "#DDDDDD", "SF_BTN_BG": "#125D98", "PBAR_FG": "#F5A962", "MAIN_FG": "black", "SF_FG": "#125D98", "SF_CHKMARK": "#F5A962", "THUMBNAIL_BG": "#DDDDDD", "THUMBNAIL_FG": "#F5A962", "THUMBNAIL_BD": "#125D98", "PBAR_BG": "#d3d3d3", "PBAR_TXT": "#125D98", "ENTRY_BD_COLOR": "#125D98", "BTN_BG": "#125D98", "BTN_FG": "#DDDDDD", "BTN_HBG": "#3C8DAD", "BTN_ABG": "#F5A962", "BTN_AFG": "#125D98", "HDG_BG": "#125D98", "HDG_FG": "#DDDDDD", "SBAR_BG": "#DDDDDD", "SBAR_FG": "#F5A962", "RCM_BG": "#DDDDDD", "RCM_FG": "#125D98", "RCM_ABG": "#F5A962", "RCM_AFG": "#125D98", "TITLE_BAR_BG": "#125D98", "TITLE_BAR_FG": "black", "SEL_BG": "#DDDDDD", "SEL_FG": "black"}, "**Blue-White**": {"MAIN_BG": "#FFFFFF", "SF_BG": "#FFFFFF", "SF_BTN_BG": "#004fff", "PBAR_FG": "#CD4631", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "#CD4631", "THUMBNAIL_BG": "#FFFFFF", "THUMBNAIL_FG": "#CD4631", "THUMBNAIL_BD": "black", "PBAR_BG": "#FFFFFF", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#FFFFFF", "BTN_BG": "#004fff", "BTN_FG": "#FFFFFF", "BTN_HBG": "#004fff", "BTN_ABG": "#FFFFFF", "BTN_AFG": "#CD4631", "HDG_BG": "#004fff", "HDG_FG": "#FFFFFF", "SBAR_BG": "#FFFFFF", "SBAR_FG": "#CD4631", "RCM_BG": "#FFFFFF", "RCM_FG": "black", "RCM_ABG": "#004fff", "RCM_AFG": "#FFFFFF", "TITLE_BAR_BG": "#004fff", "TITLE_BAR_FG": "black", "SEL_BG": "#FFFFFF", "SEL_FG": "black"}, "**White-YellowShade**": {"MAIN_BG": "#FFFFFF", "SF_BG": "#FFFFFF", "SF_BTN_BG": "#d5a021", "PBAR_FG": "#cd4631", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "#cd4631", "THUMBNAIL_BG": "#FFFFFF", "THUMBNAIL_FG": "#cd4631", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#FFFFFF", "BTN_BG": "#d5a021", "BTN_FG": "black", "BTN_HBG": "#FFFFFF", "BTN_ABG": "#FFFFFF", "BTN_AFG": "black", "HDG_BG": "#d5a021", "HDG_FG": "black", "SBAR_BG": "#FFFFFF", "SBAR_FG": "#cd4631", "RCM_BG": "#FFFFFF", "RCM_FG": "black", "RCM_ABG": "#d5a021", "RCM_AFG": "black", "TITLE_BAR_BG": "#d5a021", "TITLE_BAR_FG": "black", "SEL_BG": "#FFFFFF", "SEL_FG": "black"}, "**White-Red**": {"MAIN_BG": "#FFFFFF", "SF_BG": "#FFFFFF", "SF_BTN_BG": "#CD4631", "PBAR_FG": "#D5A021", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "#D5A021", "THUMBNAIL_BG": "#FFFFFF", "THUMBNAIL_FG": "#D5A021", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#FFFFFF", "BTN_BG": "#CD4631", "BTN_FG": "#FFFFFF", "BTN_HBG": "#FFFFFF", "BTN_ABG": "#D5A021", "BTN_AFG": "white", "HDG_BG": "#CD4631", "HDG_FG": "#FFFFFF", "SBAR_BG": "#FFFFFF", "SBAR_FG": "#D5A021", "RCM_BG": "#FFFFFF", "RCM_FG": "white", "RCM_ABG": "#CD4631", "RCM_AFG": "black", "TITLE_BAR_BG": "#CD4631", "TITLE_BAR_FG": "black", "SEL_BG": "#FFFFFF", "SEL_FG": "black"}}

**Comment by firedm** [comment]
@ahmed-tasaly 
وعليكم السلام 

Thanks for sharing these themes, just tried them and they look nice 
will add some of them to default themes
Nice work :+1:

**Comment by ahmed-tasaly** [comment]
@firedm 

**Some More with _diffrent tastes_**

{"**Green-Brown**": {"MAIN_BG": "#3A6351", "SF_BG": "#F2EDD7", "SF_BTN_BG": "#A0937D", "PBAR_FG": "#5F939A", "MAIN_FG": "white", "SF_FG": "black", "SF_CHKMARK": "#A0937D", "THUMBNAIL_BG": "#F2EDD7", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#446d5b", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#F2EDD7", "BTN_BG": "#A0937D", "BTN_FG": "black", "BTN_HBG": "#F2EDD7", "BTN_ABG": "#446d5b", "BTN_AFG": "white", "HDG_BG": "#A0937D", "HDG_FG": "black", "SBAR_BG": "#3A6351", "SBAR_FG": "white", "RCM_BG": "#3A6351", "RCM_FG": "white", "RCM_ABG": "#A0937D", "RCM_AFG": "black", "TITLE_BAR_BG": "#A0937D", "TITLE_BAR_FG": "black", "SEL_BG": "#F2EDD7", "SEL_FG": "black"}, "**Blue-Beige-Orange**": {"MAIN_BG": "#125D98", "SF_BG": "#DDDDDD", "SF_BTN_BG": "#F5A962", "PBAR_FG": "#3C8DAD", "MAIN_FG": "#DDDDDD", "SF_FG": "black", "SF_CHKMARK": "#3C8DAD", "THUMBNAIL_BG": "#DDDDDD", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#1c67a2", "PBAR_TXT": "#DDDDDD", "ENTRY_BD_COLOR": "#DDDDDD", "BTN_BG": "#F5A962", "BTN_FG": "black", "BTN_HBG": "#DDDDDD", "BTN_ABG": "#DDDDDD", "BTN_AFG": "#1c67a2", "HDG_BG": "#F5A962", "HDG_FG": "black", "SBAR_BG": "#125D98", "SBAR_FG": "#DDDDDD", "RCM_BG": "#3C8DAD", "RCM_FG": "#DDDDDD", "RCM_ABG": "#F5A962", "RCM_AFG": "black", "TITLE_BAR_BG": "#F5A962", "TITLE_BAR_FG": "black", "SEL_BG": "#DDDDDD", "SEL_FG": "black"}, "**Yellow-Foil-covered Sneakers**": {"MAIN_BG": "#333652", "SF_BG": "#90adc6", "SF_BTN_BG": "#fad02c", "PBAR_FG": "#e9eaec", "MAIN_FG": "#e9eaec", "SF_FG": "black", "SF_CHKMARK": "#e9eaec", "THUMBNAIL_BG": "#90adc6", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#3d405c", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#90adc6", "BTN_BG": "#fad02c", "BTN_FG": "black", "BTN_HBG": "#e9eaec", "BTN_ABG": "#90adc6", "BTN_AFG": "white", "HDG_BG": "#fad02c", "HDG_FG": "black", "SBAR_BG": "#333652", "SBAR_FG": "#90adc6", "RCM_BG": "#333652", "RCM_FG": "#e9eaec", "RCM_ABG": "#fad02c", "RCM_AFG": "black", "TITLE_BAR_BG": "#fad02c", "TITLE_BAR_FG": "black", "SEL_BG": "#90adc6", "SEL_FG": "black"}, "**Red_Black**": {"MAIN_BG": "#000000", "SF_BG": "#000000", "SF_BTN_BG": "#960000", "PBAR_FG": "#e09f3e", "MAIN_FG": "white", "SF_FG": "white", "SF_CHKMARK": "#e09f3e", "THUMBNAIL_BG": "#000000", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#0a0a0a", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#000000", "BTN_BG": "#960000", "BTN_FG": "white", "BTN_HBG": "#000000", "BTN_ABG": "#000000", "BTN_AFG": "white", "HDG_BG": "#960000", "HDG_FG": "white", "SBAR_BG": "#000000", "SBAR_FG": "#960000", "RCM_BG": "#000000", "RCM_FG": "white", "RCM_ABG": "#960000", "RCM_AFG": "white", "TITLE_BAR_BG": "#960000", "TITLE_BAR_FG": "black", "SEL_BG": "#000000", "SEL_FG": "white"}, "**Orange_Black**": {"MAIN_BG": "#000000", "SF_BG": "#000000", "SF_BTN_BG": "#e09f3e", "PBAR_FG": "#FFFFFF", "MAIN_FG": "white", "SF_FG": "white", "SF_CHKMARK": "white", "THUMBNAIL_BG": "#000000", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#0a0a0a", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#000000", "BTN_BG": "#e09f3e", "BTN_FG": "black", "BTN_HBG": "#000000", "BTN_ABG": "#000000", "BTN_AFG": "white", "HDG_BG": "#e09f3e", "HDG_FG": "black", "SBAR_BG": "#000000", "SBAR_FG": "#e09f3e", "RCM_BG": "#000000", "RCM_FG": "white", "RCM_ABG": "#e09f3e", "RCM_AFG": "black", "TITLE_BAR_BG": "#e09f3e", "TITLE_BAR_FG": "black", "SEL_BG": "#000000", "SEL_FG": "white"}, "**Black & White**": {"MAIN_BG": "white", "SF_BG": "Black", "SF_BTN_BG": "White", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "White", "THUMBNAIL_BG": "Black", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "Black", "BTN_BG": "White", "BTN_FG": "black", "BTN_HBG": "Black", "BTN_ABG": "Black", "BTN_AFG": "white", "HDG_BG": "White", "HDG_FG": "black", "SBAR_BG": "white", "SBAR_FG": "black", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "black", "RCM_AFG": "white", "TITLE_BAR_BG": "White", "TITLE_BAR_FG": "black", "SEL_BG": "Black", "SEL_FG": "white"}, "**White_BlueCryola**": {"MAIN_BG": "white", "SF_BG": "white", "SF_BTN_BG": "#2d82b7", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "black", "THUMBNAIL_BG": "white", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "white", "BTN_BG": "#2d82b7", "BTN_FG": "white", "BTN_HBG": "black", "BTN_ABG": "white", "BTN_AFG": "#2d82b7", "HDG_BG": "#2d82b7", "HDG_FG": "white", "SBAR_BG": "white", "SBAR_FG": "#2d82b7", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#2d82b7", "RCM_AFG": "white", "TITLE_BAR_BG": "#2d82b7", "TITLE_BAR_FG": "white", "SEL_BG": "#2d82b7", "SEL_FG": "white"}, "**White_RoyalePurple**": {"MAIN_BG": "white", "SF_BG": "#7d5ba6", "SF_BTN_BG": "white", "PBAR_FG": "#7d5ba6", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "white", "THUMBNAIL_BG": "#7d5ba6", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#7d5ba6", "BTN_BG": "white", "BTN_FG": "black", "BTN_HBG": "#7d5ba6", "BTN_ABG": "#7d5ba6", "BTN_AFG": "white", "HDG_BG": "white", "HDG_FG": "black", "SBAR_BG": "#7d5ba6", "SBAR_FG": "white", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#7d5ba6", "RCM_AFG": "white", "TITLE_BAR_BG": "white", "TITLE_BAR_FG": "black", "SEL_BG": "#7d5ba6", "SEL_FG": "white"}, "**White & Black**": {"MAIN_BG": "white", "SF_BG": "white", "SF_BTN_BG": "black", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "black", "THUMBNAIL_BG": "white", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "white", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "black", "BTN_BG": "black", "BTN_FG": "white", "BTN_HBG": "white", "BTN_ABG": "white", "BTN_AFG": "black", "HDG_BG": "black", "HDG_FG": "white", "SBAR_BG": "white", "SBAR_FG": "black", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "black", "RCM_AFG": "white", "TITLE_BAR_BG": "black", "TITLE_BAR_FG": "white", "SEL_BG": "black", "SEL_FG": "white"}}

**Comment by firedm** [comment]
@ahmed-tasaly 
Just added some of your themes to [new FireDM release](https://github.com/firedm/FireDM/releases/tag/2021.7.25), also added your name to [contributors' list](https://github.com/firedm/FireDM/blob/master/contributors.md)
good job! :+1:

**Comment by ahmed-tasaly** [comment]
> @ahmed-tasaly
> Just added some of your themes to [new FireDM release](https://github.com/firedm/FireDM/releases/tag/2021.7.25), also added your name to [contributors' list](https://github.com/firedm/FireDM/blob/master/contributors.md)
> good job! +1

@firedm 

Thank you brother
شكرا جزيلا
Merci beaucoup
😂😂😂😂😂😂

**Comment by ahmed-tasaly** [comment]
> @ahmed-tasaly
> Just added some of your themes to [new FireDM release](https://github.com/firedm/FireDM/releases/tag/2021.7.25), also added your name to [contributors' list](https://github.com/firedm/FireDM/blob/master/contributors.md)
> good job! +1

@firedm 

Assalam Alaykom

I have noticed that you didn't use the last themes : **Black & White** / **White_BlueCryola** / **White_RoyalePurple**

`"Black & White": {"MAIN_BG": "white", "SF_BG": "Black", "SF_BTN_BG": "White", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "White", "THUMBNAIL_BG": "Black", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "Black", "BTN_BG": "White", "BTN_FG": "black", "BTN_HBG": "Black", "BTN_ABG": "Black", "BTN_AFG": "white", "HDG_BG": "White", "HDG_FG": "black", "SBAR_BG": "white", "SBAR_FG": "black", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "black", "RCM_AFG": "white", "TITLE_BAR_BG": "White", "TITLE_BAR_FG": "black", "SEL_BG": "Black", "SEL_FG": "white"}, "White_BlueCryola": {"MAIN_BG": "white", "SF_BG": "white", "SF_BTN_BG": "#2d82b7", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "black", "THUMBNAIL_BG": "white", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "white", "BTN_BG": "#2d82b7", "BTN_FG": "white", "BTN_HBG": "black", "BTN_ABG": "white", "BTN_AFG": "#2d82b7", "HDG_BG": "#2d82b7", "HDG_FG": "white", "SBAR_BG": "white", "SBAR_FG": "#2d82b7", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#2d82b7", "RCM_AFG": "white", "TITLE_BAR_BG": "#2d82b7", "TITLE_BAR_FG": "white", "SEL_BG": "#2d82b7", "SEL_FG": "white"}, "White_RoyalePurple": {"MAIN_BG": "white", "SF_BG": "#7d5ba6", "SF_BTN_BG": "white", "PBAR_FG": "#7d5ba6", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "white", "THUMBNAIL_BG": "#7d5ba6", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#7d5ba6", "BTN_BG": "white", "BTN_FG": "black", "BTN_HBG": "#7d5ba6", "BTN_ABG": "#7d5ba6", "BTN_AFG": "white", "HDG_BG": "white", "HDG_FG": "black", "SBAR_BG": "#7d5ba6", "SBAR_FG": "white", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#7d5ba6", "RCM_AFG": "white", "TITLE_BAR_BG": "white", "TITLE_BAR_FG": "black", "SEL_BG": "#7d5ba6", "SEL_FG": "white"}`

**Did you try them ?
or you didn't like them 

both are OK** 
😂😂😂😂😂😂

**Comment by firedm** [comment]
@ahmed-tasaly 
i liked a lot of your themes, the ones i avoided has some problems, if you can fix them, i will add them too

Black & White / White_RoyalePurple: the buttons in main tab (e.g. playlist download, retry, SUB, and BAT buttons) disappeared because they are white on a white background, also progressbar color is black which disappear when selecting a download item

White_BlueCryola: just choose a proper download item "selection color", because if you select a download item small buttons disappear

also try to right click on any download item and check if right click menu shows correctly with your theme

thanks again for good work

**Comment by ahmed-tasaly** [comment]
@firedm 

### these are the themes after editing

{"**Blue-Beige-Orange**": {"MAIN_BG": "#125D98", "SF_BG": "#DDDDDD", "SF_BTN_BG": "#F5A962", "PBAR_FG": "#3C8DAD", "MAIN_FG": "#DDDDDD", "SF_FG": "black", "SF_CHKMARK": "#3C8DAD", "THUMBNAIL_BG": "#DDDDDD", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#1c67a2", "PBAR_TXT": "#DDDDDD", "ENTRY_BD_COLOR": "#DDDDDD", "BTN_BG": "#F5A962", "BTN_FG": "black", "BTN_HBG": "#DDDDDD", "BTN_ABG": "#DDDDDD", "BTN_AFG": "#1c67a2", "HDG_BG": "#F5A962", "HDG_FG": "black", "SBAR_BG": "#125D98", "SBAR_FG": "#DDDDDD", "RCM_BG": "#3C8DAD", "RCM_FG": "#DDDDDD", "RCM_ABG": "#F5A962", "RCM_AFG": "black", "TITLE_BAR_BG": "#F5A962", "TITLE_BAR_FG": "black", "SEL_BG": "#DDDDDD", "SEL_FG": "black"}, "**Black & White**": {"MAIN_BG": "white", "SF_BG": "Black", "SF_BTN_BG": "White", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "White", "THUMBNAIL_BG": "Black", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "Black", "BTN_BG": "White", "BTN_FG": "black", "BTN_HBG": "Black", "BTN_ABG": "Black", "BTN_AFG": "white", "HDG_BG": "White", "HDG_FG": "black", "SBAR_BG": "white", "SBAR_FG": "black", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "black", "RCM_AFG": "white", "TITLE_BAR_BG": "White", "TITLE_BAR_FG": "black", "SEL_BG": "Black", "SEL_FG": "white"}, "**White_BlueCryola**": {"MAIN_BG": "white", "SF_BG": "white", "SF_BTN_BG": "#2d82b7", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "black", "THUMBNAIL_BG": "white", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "white", "BTN_BG": "#2d82b7", "BTN_FG": "white", "BTN_HBG": "black", "BTN_ABG": "white", "BTN_AFG": "#2d82b7", "HDG_BG": "#2d82b7", "HDG_FG": "white", "SBAR_BG": "white", "SBAR_FG": "#2d82b7", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#2d82b7", "RCM_AFG": "white", "TITLE_BAR_BG": "#2d82b7", "TITLE_BAR_FG": "white", "SEL_BG": "#58a7d6", "SEL_FG": "white"}, "**White_RoyalePurple**": {"MAIN_BG": "white", "SF_BG": "#7d5ba6", "SF_BTN_BG": "white", "PBAR_FG": "#7d5ba6", "MAIN_FG": "black", "SF_FG": "white", "SF_CHKMARK": "white", "THUMBNAIL_BG": "#7d5ba6", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "#f5f5f5", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "#7d5ba6", "BTN_BG": "#dcd1e7", "BTN_FG": "black", "BTN_HBG": "#7d5ba6", "BTN_ABG": "#7d5ba6", "BTN_AFG": "white", "HDG_BG": "white", "HDG_FG": "black", "SBAR_BG": "white", "SBAR_FG": "#7d5ba6", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "#7d5ba6", "RCM_AFG": "white", "TITLE_BAR_BG": "white", "TITLE_BAR_FG": "black", "SEL_BG": "#7d5ba6", "SEL_FG": "white"}, "**White & Black**": {"MAIN_BG": "white", "SF_BG": "white", "SF_BTN_BG": "black", "PBAR_FG": "black", "MAIN_FG": "black", "SF_FG": "black", "SF_CHKMARK": "black", "THUMBNAIL_BG": "white", "THUMBNAIL_FG": "black", "THUMBNAIL_BD": "black", "PBAR_BG": "white", "PBAR_TXT": "black", "ENTRY_BD_COLOR": "black", "BTN_BG": "black", "BTN_FG": "white", "BTN_HBG": "white", "BTN_ABG": "white", "BTN_AFG": "black", "HDG_BG": "black", "HDG_FG": "white", "SBAR_BG": "white", "SBAR_FG": "black", "RCM_BG": "white", "RCM_FG": "black", "RCM_ABG": "black", "RCM_AFG": "white", "TITLE_BAR_BG": "black", "TITLE_BAR_FG": "white", "SEL_BG": "#d8d8d8", "SEL_FG": "black"}, "**My_Orange_Black**": {"MAIN_BG": "#000000", "SF_BG": "#000000", "SF_BTN_BG": "#e09f3e", "PBAR_FG": "#FFFFFF", "MAIN_FG": "white", "SF_FG": "white", "SF_CHKMARK": "white", "THUMBNAIL_BG": "#000000", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#0a0a0a", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#000000", "BTN_BG": "#e09f3e", "BTN_FG": "black", "BTN_HBG": "#000000", "BTN_ABG": "#000000", "BTN_AFG": "white", "HDG_BG": "#e09f3e", "HDG_FG": "black", "SBAR_BG": "#000000", "SBAR_FG": "#e09f3e", "RCM_BG": "#000000", "RCM_FG": "white", "RCM_ABG": "#e09f3e", "RCM_AFG": "black", "TITLE_BAR_BG": "#e09f3e", "TITLE_BAR_FG": "black", "SEL_BG": "white", "SEL_FG": "black"}, "**My_Red_Black**": {"MAIN_BG": "#000000", "SF_BG": "#000000", "SF_BTN_BG": "#960000", "PBAR_FG": "#e09f3e", "MAIN_FG": "white", "SF_FG": "white", "SF_CHKMARK": "#e09f3e", "THUMBNAIL_BG": "#000000", "THUMBNAIL_FG": "white", "THUMBNAIL_BD": "white", "PBAR_BG": "#0a0a0a", "PBAR_TXT": "white", "ENTRY_BD_COLOR": "#000000", "BTN_BG": "#960000", "BTN_FG": "white", "BTN_HBG": "#000000", "BTN_ABG": "#000000", "BTN_AFG": "white", "HDG_BG": "#960000", "HDG_FG": "white", "SBAR_BG": "#000000", "SBAR_FG": "#960000", "RCM_BG": "#000000", "RCM_FG": "white", "RCM_ABG": "#960000", "RCM_AFG": "white", "TITLE_BAR_BG": "#960000", "TITLE_BAR_FG": "black", "SEL_BG": "#e09f3e", "SEL_FG": "white"}}

### _Themes -->_

**my_orange_black** and **my_red_black** are the fixed versions of orange_black and red_black "color of selection bar"

**Black & White** / **White_RoyalePurple** : are fixed by adding some grey and light pink

**White_BlueCryola** : is fixed by adding lighter color as "selection bar"

**Comment by firedm** [comment]
@ahmed-tasaly 
الســـــــــــــــــــــلام عليــــــــــــــــكم
just tested your last themes and found:

**Black & White**: need to change buttons' color (buttons are white on white background)
**White_RoyalePurple**: : need to change buttons' color (no enough contrast, and they looks "inactive or disabled")

**Blue-Beige-Orange**: progressbar active ring color has no enough contrast with Main background color

**my_orange_black and my_red_black**: problem (selection bar color is the same as progressbar color), the original orange_black and red_black has a black selection color which is not bad

below themes are ok:
- **White_BlueCryola**
- **White & Black**
