### ISSUE TITLE
Small feature suggestion

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#262]
Hi, I love that you can now automatically download thumbnails.

But I only want to download thumbnails for AUDIO not video, usually to get the cover art for a song.

In the settings, would it be possible to split the "**Download Video Thumbnail**" into TWO options:

"**Download thumbnail for videos**" and "**Download thumbnail for audio**"

Thank you! : - )

**Comment by firedm** [comment]
@Mr-Personality 
post any audio url,  that have a thumbnail for testing

**Comment by Mr-Personality** [comment]
Just an example...

https://www.youtube.com/watch?v=W95qh5hiI0E&list=OLAK5uy_nrPMJ07OOXVhFNwA7Oeq1cKfgdqt7CNIw

**Comment by Mr-Personality** [comment]
Hi, I love all the development you've made with FireDM, it just gets better and better! :-)

Could you please consider fixing this issue? Currently, FireDM only seems to download thumbnails for videos, but not for audio files.

I want it to do the opposite - download thumbnails for audio, but not for video!

**Comment by firedm** [comment]
@Mr-Personality 
when i enable option "write thumbnail to disk" then tried to download audio stream from a youtube link, after file downloaded, thumbnail image will also be downloaded (as a separate file, with same name and .png extension), no matter it is a video or audio file

![image](https://user-images.githubusercontent.com/58998813/142950860-5ce8d221-a152-4e08-9789-07f3bf2d9031.png)


or do you mean "Embedding/hardcoding" thumbnail into audio file??

**Comment by Mr-Personality** [comment]
My apologies. I have checked and you're right. It does always download the thumbnail, for video and audio. I thought it didn't, my mistake.

It would be useful to disable thumbnail downloading for videos, but I guess that's not too important. Thanks for all your work on this fantastic app! :-)

**Comment by firedm** [comment]
Great !
