### ISSUE TITLE
Multiple links feature suggestion

### ISSUE THREAD

**Issue by ipkpjersi** [firedm/FireDM#263]
Hi,

I think it would be nice to be able to paste multiple links at once to download multiple videos at once. I know there's playlists but that's not quite the same thing. Right now you can only download videos individually, having to manually enter every video link one at a time.

Thanks.

**Comment by firedm** [comment]
@ipkpjersi 
There is multiple requests asking for this feature 
it is already in todo list as a batch download feature, will try to work on it soon

**Comment by ipkpjersi** [comment]
Ah, I didn't know there was already a request and it's todo. I will now close this issue.
