### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by ahmed-tasaly** [firedm/FireDM#264]
### السلام عليكم
@firedm 
### for example 
`https://drive.google.com/file/d/1NUGCY22Yas6vOIjHAdiNU6dwwRJFgYXg/view `

**Comment by firedm** [comment]
وعليكم السلام
There is no support for google drive because of below reason as quoted from issue #144 :

> google server doesn't send information about the file size in headers, which make it impossible to make a multi-segment file which means no multi-connection will be available,
> with these restrictions, FireDM will offer no advantage over any web-browser while downloading google drive file.

so there is no plan to add google support in the future
