### ISSUE TITLE
Re-implement command-line options based on more powerful libraries.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#271]
The current command-line options of firedm are implemented using argparse. I suggest the following more powerful command-line parsing libraries to have more abundant and the full expansion space in the future:

https://github.com/google/python-fire
https://github.com/pallets/click

Regards,
HY

**Comment by firedm** [comment]
@hongyi-zhao 
Thanks for your good suggestions
both python-fire and click look great, with a lot of good features

in my opinion, argparse is currently doing the job just fine, and more arguments and options can be added easily in the future, plus it is part of python standard library i.e. no need to install 3rd party libraries

anyhow, in case in the future argparse fails to do the job, i will consider rewriting the code using one of (python-fire or click)
