### ISSUE TITLE
what about this theme

### ISSUE THREAD

**Issue by ahmed-tasaly** [firedm/FireDM#273]
السلام عليكم

"Black & White & Midnight": {
        "MAIN_BG": "white",
        "SF_BG": "Black",
        "SF_BTN_BG": "White",
        "PBAR_FG": "black",
        "MAIN_FG": "black",
        "SF_FG": "white",
        "SF_CHKMARK": "White",
        "THUMBNAIL_BG": "Black",
        "THUMBNAIL_FG": "black",
        "THUMBNAIL_BD": "black",
        "PBAR_BG": "#f5f5f5",
        "PBAR_TXT": "black",
        "ENTRY_BD_COLOR": "Black",
        "BTN_BG": "#631d76",
        "BTN_FG": "white",
        "BTN_HBG": "white",
        "BTN_ABG": "Black",
        "BTN_AFG": "white",
        "HDG_BG": "White",
        "HDG_FG": "black",
        "SBAR_BG": "white",
        "SBAR_FG": "black",
        "RCM_BG": "white",
        "RCM_FG": "black",
        "RCM_ABG": "black",
        "RCM_AFG": "white",
        "TITLE_BAR_BG": "White",
        "TITLE_BAR_FG": "black",
        "SEL_BG": "white",
        "SEL_FG": "#631d76"
    }
![image](https://user-images.githubusercontent.com/64969309/132256683-7cd31152-a9c1-42fb-bb6c-b110d50e22b6.png)

**Comment by firedm** [comment]
@ahmed-tasaly 
وعليكم السلام 
good work!
just tested your theme, it looks ok, but need to change SEL_BG "Download Item Selection Background" with a proper color that contrast with background, since it doesn't stand well with a white color same as the background, you can't tell if you actually selected an item when you click on it

**Comment by ahmed-tasaly** [comment]
> @ahmed-tasaly
> وعليكم السلام
> good work!
> just tested your theme, it looks ok, but need to change SEL_BG "Download Item Selection Background" with a proper color that contrast with background, since it doesn't stand well with a white color same as the background, you can't tell if you actually selected an item when you click on it

yes but I thought the font color change is not that enough to indicate a change

any way 

"Black & White & Midnight": {
        "MAIN_BG": "white",
        "SF_BG": "Black",
        "SF_BTN_BG": "White",
        "PBAR_FG": "black",
        "MAIN_FG": "black",
        "SF_FG": "#f2a541",
        "SF_CHKMARK": "White",
        "THUMBNAIL_BG": "Black",
        "THUMBNAIL_FG": "black",
        "THUMBNAIL_BD": "black",
        "PBAR_BG": "#f5f5f5",
        "PBAR_TXT": "black",
        "ENTRY_BD_COLOR": "Black",
        "BTN_BG": "#631d76",
        "BTN_FG": "white",
        "BTN_HBG": "white",
        "BTN_ABG": "Black",
        "BTN_AFG": "white",
        "HDG_BG": "White",
        "HDG_FG": "black",
        "SBAR_BG": "white",
        "SBAR_FG": "black",
        "RCM_BG": "white",
        "RCM_FG": "black",
        "RCM_ABG": "#631d76",
        "RCM_AFG": "white",
        "TITLE_BAR_BG": "White",
        "TITLE_BAR_FG": "black",
        "SEL_BG": "#f2a541",
        "SEL_FG": "black"
    }

![image](https://user-images.githubusercontent.com/64969309/132352122-ed18abc5-8601-4002-aaaa-49cf98136119.png)

**Comment by ahmed-tasaly** [comment]
@firedm 
and this too 

![image](https://user-images.githubusercontent.com/64969309/132359444-1e88cc14-f2ba-4170-9a93-b97dbd8b2f3d.png)


"White_UpsdellRed_Marigold": {
        "MAIN_BG": "white",
        "SF_BG": "white",
        "SF_BTN_BG": "#b10f2e",
        "PBAR_FG": "black",
        "MAIN_FG": "black",
        "SF_FG": "black",
        "SF_CHKMARK": "#eca72c",
        "THUMBNAIL_BG": "white",
        "THUMBNAIL_FG": "black",
        "THUMBNAIL_BD": "black",
        "PBAR_BG": "#f5f5f5",
        "PBAR_TXT": "black",
        "ENTRY_BD_COLOR": "white",
        "BTN_BG": "#b10f2e",
        "BTN_FG": "white",
        "BTN_HBG": "black",
        "BTN_ABG": "white",
        "BTN_AFG": "#b10f2e",
        "HDG_BG": "#b10f2e",
        "HDG_FG": "white",
        "SBAR_BG": "white",
        "SBAR_FG": "#b10f2e",
        "RCM_BG": "white",
        "RCM_FG": "black",
        "RCM_ABG": "#b10f2e",
        "RCM_AFG": "white",
        "TITLE_BAR_BG": "#b10f2e",
        "TITLE_BAR_FG": "white",
        "SEL_BG": "#eca72c",
        "SEL_FG": "black"
    }

**Comment by ahmed-tasaly** [comment]
@firedm 
and then these

![image](https://user-images.githubusercontent.com/64969309/132365098-b96c1bb0-7c0d-4f73-91d0-bc6fbb7be332.png)

"White_DimGrey_BrightYellowCrayola": {
        "MAIN_BG": "white",
        "SF_BG": "#716969",
        "SF_BTN_BG": "#fbb13c",
        "PBAR_FG": "#fbb13c",
        "MAIN_FG": "black",
        "SF_FG": "white",
        "SF_CHKMARK": "white",
        "THUMBNAIL_BG": "#fbb13c",
        "THUMBNAIL_FG": "black",
        "THUMBNAIL_BD": "black",
        "PBAR_BG": "#f5f5f5",
        "PBAR_TXT": "black",
        "ENTRY_BD_COLOR": "#716969",
        "BTN_BG": "black",
        "BTN_FG": "white",
        "BTN_HBG": "#716969",
        "BTN_ABG": "#fbb13c",
        "BTN_AFG": "white",
        "HDG_BG": "white",
        "HDG_FG": "black",
        "SBAR_BG": "white",
        "SBAR_FG": "black",
        "RCM_BG": "white",
        "RCM_FG": "black",
        "RCM_ABG": "#716969",
        "RCM_AFG": "white",
        "TITLE_BAR_BG": "#fbb13c",
        "TITLE_BAR_FG": "black",
        "SEL_BG": "#716969",
        "SEL_FG": "white"
    }

![image](https://user-images.githubusercontent.com/64969309/132365880-24c1e3b4-0241-4aef-84b1-ba90efc2958e.png)

"White_RoyalePurple_GoldFusion": {
        "MAIN_BG": "white",
        "SF_BG": "#7d5ba6",
        "SF_BTN_BG": "white",
        "PBAR_FG": "#7d5ba6",
        "MAIN_FG": "black",
        "SF_FG": "white",
        "SF_CHKMARK": "white",
        "THUMBNAIL_BG": "#72705b",
        "THUMBNAIL_FG": "black",
        "THUMBNAIL_BD": "black",
        "PBAR_BG": "#f5f5f5",
        "PBAR_TXT": "black",
        "ENTRY_BD_COLOR": "#7d5ba6",
        "BTN_BG": "#72705b",
        "BTN_FG": "white",
        "BTN_HBG": "black",
        "BTN_ABG": "#7d5ba6",
        "BTN_AFG": "white",
        "HDG_BG": "white",
        "HDG_FG": "black",
        "SBAR_BG": "white",
        "SBAR_FG": "#7d5ba6",
        "RCM_BG": "white",
        "RCM_FG": "black",
        "RCM_ABG": "#7d5ba6",
        "RCM_AFG": "white",
        "TITLE_BAR_BG": "white",
        "TITLE_BAR_FG": "black",
        "SEL_BG": "black",
        "SEL_FG": "white"
    }

**Comment by firedm** [comment]
@ahmed-tasaly 
Nice, just tested all and found no problem, we'll add them to next release

GREAT WORK!!, thanks for sharing

**Comment by firedm** [comment]
Done!
added themes in latest release
