### ISSUE TITLE
[Request] A compact theme 

### ISSUE THREAD

**Issue by tazihad** [firedm/FireDM#274]
It would be very if you could implement a compact theme similar to traditional download manager. i.e- IDM, FreeDownloadManager. Where the rows are small with only name and size info.

**Comment by firedm** [comment]
@tazihad 
Thanks for your feedback
No problem, will add this as an option in settings tab with coming release

**Comment by firedm** [comment]
Done!
added compact view in latest release

**Comment by firedm** [comment]
@smaragdus 
thanks a lot, i waited for someone to give a feedback regarding the new compact view, and i'm very happy you like it

> The standard view looked so horrible to me

LOL :)    you should say this long time ago, people's suggestions might take time to implement, but eventually it get thru

**Comment by smaragdus** [comment]
Actually, I liked and I still like the "wood" pyIDM interface as I find it very original and I kind of miss it.

As I am back on board I may open a new issue, a kind of discussion one, about the interface and possible refinements, including the program icon. I just need to have a deeper look at the program and to do more thorough tests.

If everything is normal expect to hear from me again soon, this is a warning! ;)

Best regards
