### ISSUE TITLE
how to use command for convert video from webm to mp4

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#275]
how to use command for convert video from webm to mp4
![image](https://user-images.githubusercontent.com/36833664/132934346-84ad58ce-420e-4dfb-a37e-521284facba2.png)

**Comment by firedm** [comment]
@candrapersada 

> how to use command for convert video from webm to mp4

better you submit an example url for a webm file, to check if its a direct download link or a video link to give you a better answer
