### ISSUE TITLE
manually select audio format for dash video can't be used for video playlist and download later

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#276]
why manually select audio format for dash video can't be used for video playlist and download later?
![image](https://user-images.githubusercontent.com/36833664/132934691-3c38b8f4-f232-419b-899a-0035a42b039e.png)

**Comment by firedm** [comment]
@candrapersada 
thanks for reporting this, 
will check for a fix

**Comment by candrapersada** [comment]
and why there is no option `-f bestvideo+bestaudio` and `-f worstvideo+worstaudio` in the playlist?

**Comment by firedm** [comment]
> and why there is no option -f bestvideo+bestaudio and -f worstvideo+worstaudio in the playlist?


if you are talking about cmdline arguments, more options will be added with time

**Comment by candrapersada** [comment]
> if you are talking about cmdline arguments, more options will be added with time


what I mean is the option for FireDM GUI not for cmdline.
to use option for `bestvideo+bestaudio` and `worstvideo+worstaudio` from youtube-dl and yt-dlp.

**Comment by candrapersada** [comment]
whether to add features for video+audio format like this pictured
![133535844-34e8c8f0-7020-433a-9fd5-d4a09d9668aa](https://user-images.githubusercontent.com/36833664/133536109-5c02edc8-fc38-41fd-a126-aab93396a77f.png)
for Video Playlist. and Batch Download.

**Comment by firedm** [comment]
@candrapersada 
i've got your point, will try to add it.

**Comment by candrapersada** [comment]
how to Select all `video+audio` playlist?
![image](https://user-images.githubusercontent.com/36833664/135021022-1b625b73-a24a-47b9-b59d-f13b0bda8825.png)

**Comment by candrapersada** [comment]
and why the download queue is not sequential
for example 1 is below and 5 is above but when I start downloading directly to 3, 2, 5, 4, and 1?

**Comment by firedm** [comment]
> how to Select all dash audio in playlist? ![image](https://user-images.githubusercontent.com/36833664/135021022-1b625b73-a24a-47b9-b59d-f13b0bda8825.png)

you can do this per each video, there is no master button for all videos
![image](https://user-images.githubusercontent.com/58998813/135101083-ca1b3c6c-7cfd-45d7-9709-de6b3a9f57d8.png)

**Comment by firedm** [comment]
> and why the download queue is not sequential for example 1 is below and 5 is above but when I start downloading directly to 3, 2, 5, 4, and 1?

will have a look into this

**Comment by candrapersada** [comment]
> you can do this per each video, there is no master button for all videos
![image](https://user-images.githubusercontent.com/36833664/135974015-b4e23c60-f027-406b-9cb1-e3a299bd2909.png)

add select all audio format for dash video playlist

**Comment by firedm** [comment]
> add select all audio format for dash video playlist

no problem,  will add a master button for audio selection

**Comment by candrapersada** [comment]
add option to select audio format for dash video with one click for playlist.
