### ISSUE TITLE
My 2 color themes

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#279]
It's great to have more color themes bundled with the program.

Here are my own two themes that I use. I name them after myself but call them anything you like.

Lee 1 theme

"MAIN_BG": "#f6f6f6",
"SF_BG": "#d6cebf",
"SF_BTN_BG": "#368ee6",
"PBAR_FG": "#0085ff",

"SF_CHKMARK": "#75cdfd",
"SEL_BG": "#75cdfd",
"SEL_FG": "black",

Button text color = white
Heading title text color = white

Lee 2 theme

"MAIN_BG": "#ffffff",
"SF_BG": "##d0eaff",
"SF_BTN_BG": "#009ddc",
"PBAR_FG": "#009ddc",

"SF_CHKMARK": "#009ddc",
"SEL_BG": "#a9ceef",
"SEL_FG": "black",

Button text color = white
Heading title text color = white

**Comment by firedm** [comment]
@Mr-Personality 
thanks for contribution
just tested your 2 themes, this what i add in  `user_themes.cfg` file

```
{
    "Lee-1": {
        "MAIN_BG": "#f6f6f6",
        "SF_BG": "#d6cebf",
        "SF_BTN_BG": "#368ee6",
        "PBAR_FG": "#0085ff",
        "RCM_FG": "black"
    },
    "Lee-2": {
        "MAIN_BG": "#ffffff",
        "SF_BG": "#d0eaff",
        "SF_BTN_BG": "#009ddc",
        "PBAR_FG": "#009ddc",
        "RCM_FG": "black"
    }
}
```

both look nice, i believe it is a good addition to FireDM, will add both in next release

Great job!

**Comment by Mr-Personality** [comment]
Great, thank you! :-)

**Comment by firedm** [comment]
2 themes already added to latest release, thanks for your addition

[contributors' list](https://github.com/firedm/FireDM/blob/master/contributors.md)
