### ISSUE TITLE
Add support for my.mail.ru

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#280]
Hello, FireDM is wonderful and amazing , thank you very much !

Please I have a suggestion : this streaming site my.mail.ru  is very important because it is a smooth site that has a lot of anime videos and it will be great if our beloved FireDM allows to download them, I tried to download this video but I failed :

https://my.mail.ru/mail/richard1339/video/_myvideo/733.html?from=videoplayer

We konow that this kind of video very difficult to download but when there is a lack of data plan or weak wifi , it becomes essential and crucial to download for offline use......
 Thank you very much for this exceptional downloader :)

**Comment by firedm** [comment]
@trimechee 
just tried the link you provided, and it works with FireDM as below screenshot

![image](https://user-images.githubusercontent.com/58998813/133860377-a6e001a0-4983-4c5d-a5c5-ef7540d1a625.png)


the video has been downloaded completely and played normally 

there is a small issue but you can ignore it, FireDM used only one connection while downloading this video, which might affect the download speed, will check why this is happening and try to fix it.

**Comment by trimechee** [comment]
Yes, FireDM starts downloading part of the video, like 30% or 40% of the video then suddenly the download goes back to 0% and FireDM erases what it downloaded and starts re-downloading the video from the beginning ....

I tried several times to download this whole video but it always fails, so we have to let the video download in full to be able to see this problem because the video does not download in full ... ..there is a loop , a spiral

I went into the FireDM settings changing several options in the hope of solving this problem: I put "connections per donwload" to the value "1",   
I activated captchata workaround and downloaded the page in html. .....but it fails

I have tried many times and the download does not complete completely, FireDM downloads 20% or 40% then the download suddenly stops and the download returns to 0% and FireDm starts downloading the video again from the beginning but the download does not end until the end and stops after a certain moment then FireDm automatically resumes to download from the beginning again...... it is a loop that does not end .....

Certainly there is a complex security on this site that prevents full downloading of the video, maybe FireDm can properly download short videos from this website, but if there is a slightly longer video that lasts  23 minutes oror that lasts longer for exemple 40 minutes,, there is a bug unfortunately and I hope FireDM could fix it in sha Allah :)

If we allow FireDM through the firewall, this problem of uninterrupted download and then restarted could be solved perhaps?

**Comment by firedm** [comment]
@trimechee 
thanks for reporting
i already fixed this problem, and all works fine now

i can send you a test version of FireDM to try it with downloading from this site
how do you use FireDM, i.e. windows portable version, or linux appimage or pypi?

**Comment by trimechee** [comment]
Ohh that's amzing ! thank you very much :)
Yes of course with pleasure, I would download and test the new version in sha Allah, thank you again and congratulations for your wonderful work !
 I tested several downloaders and your software is the best, even better than the paid software and we thank you to offer us this unbelievable donwloader open source ! (sorry for the delay in answering you, I was not connected)

**Comment by trimechee** [comment]
Yes of course , I would be very grateful and happy if you send me this new exclusive version! thanks a lot !
I am using windows 10 64bits, is it possible to make binary version ".exe" of FireDM, because I think that FireDM would be even more efficient if it is installed in the classic way on windows 10 ?

**Comment by firedm** [comment]
@trimechee 
here is a test version at https://github.com/firedm/FireDM/releases/download/extra/FireDM_2021.9.20.beta.zip
you can test it and let me know if it works with my.mail.ru or not

regarding windows installer, we might add a plan for it in the future

**Comment by trimechee** [comment]
Awesome ! thank you very much for your precious help :)

**Comment by trimechee** [comment]
I just tested and it works without problem and I was able to download the video completely! thank you so much !

I have another suggestion please: sometimes the server forbids and cancels the download and even blacklists the IP address if there are many connections per download, so maybe FireDM can automatically lower the number of connections to 3 or 2 and even 1 to try to exceed the limit of authorized connections ...

Thank you again for your help :)

**Comment by firedm** [comment]
@trimechee 
for normal users, they can download standalone version of FireDM, e.g. portable exe version for windows and AppImage for linux.
however, there is still some other options to install firedm which meant for **(experienced)** users only
e.g. install thru python pip or running from source, in this case user has to install all dependencies manually including pycurl

automating dependencies installation requires a lot of complications and unnecessary effort, IMO, user should know what he's doing if he chooses this route otherwise he should stick with ready made versions of FireDM.

**Comment by trimechee** [comment]
Thank you very much for these  clarification :) 
I didn't know that there is exe version for windows 64 bits, I thought the exe version exists just for 32 its!

I hear about dependicies and its problems only in linux os, there is also dependicies in windiws 10 !
Thanks again for your help and  for developing such wonderful software !

**Comment by firedm** [comment]
issue of my.mail.ru is fixed in latest release, thanks again for reporting

**Comment by trimechee** [comment]
Great ! Thank you :)
