### ISSUE TITLE
Add these extensions to FireDm 

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#283]
Hello, except for the site https://www.oreilly.com/ which does not allow downloading of books for users who do not have an account, it will be great if FireDM integrates the rest of these extensions to make FireDM even better efficient and incredible

https://github.com/mhogomchungu/media-downloader/wiki/Extensions

**Comment by firedm** [comment]
@trimechee 
thanks for suggestions

regarding the extensions / app you mentioned
1. Safari books
2. yt-dlp.
3. gallery-dl.
4. wget.

for yt-dlp and youtube-dl already integrated within firedm
wget, there is no extra functionality will be added, firedm used libcurl (the core of curl)

for the rest, unfortunately, it is not possible to integrate these extensions into firedm

**Comment by trimechee** [comment]
Thanks for these clarifications :) the most important thing is that FireDM can download videos and FireDM perform this mission in an extraordinary and beautiful and efficient way, thank you very much for all your efforts :)

Please I have a query, description of FireDM says "for windows users: normal pip install i.e python -m pip install pycurl might fail on windows because you need to build libcurl on your system first which is a headache",

so does FireDM automatically install "python" software that seems important and necessary ? 
and if so, how can we verify and test that python works without issues and bug-free with FireDM?
  because I am ready and I think that many are ready to manually install python to avoid possible issues .....

**Comment by firedm** [comment]
@trimechee 
> Please I have a query, description of FireDM says "for windows users: normal pip install i.e python -m pip install pycurl might fail on windows because you need to build libcurl on your system first which is a headache",

unfortunately, pycurl removed binary versions for windows and this link "https://dl.bintray.com/pycurl/pycurl/" is now dead, and one has to build pycurl from source which is not an easy task
details are here http://pycurl.io/docs/latest/install.html#windows

i'm not sure if pip can install pycurl successfully or not, 

anyhow you can try the following:
- install python
- download rquirements file from here https://github.com/firedm/FireDM/raw/master/requirements.txt
- run this command in cmd  `python -m pip install -r requirements.txt`
- type firedm

firedm should start if everything goes well

> so does FireDM automatically install "python" software that seems important and necessary ?
no, firedm doesn't install anything automatically, it will only offer to download ffmpeg if missing

**Comment by trimechee** [comment]
Great ! Thank you so much ! I would try hoping it will work in sha Allah :)
