### ISSUE TITLE
is it possible to separate temporary directory storage location from download directory like IDM

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#284]
why is the temporary save directory stored in the same directory as the download directory?
![image](https://user-images.githubusercontent.com/36833664/135152086-7f1b7124-3f39-4074-b338-2a0391431e1b.png)
![IDM-temporary-directory-path](https://user-images.githubusercontent.com/36833664/135573750-490250f4-911f-45b4-9b4f-cebe6dce90de.png)

**Comment by firedm** [comment]
> why is the temporary save directory stored in the same directory as the download directory?

why not?, 
it will be removed when download is completed, or when you delete the item from "downloads tab" in gui.

**Comment by candrapersada** [comment]
is it possible to separate the storage location of the temporary directory from the download directory?
for example for windows storage (C:) and (D:). temporary saved in (C:) after the download is complete move it to (D:)

**Comment by firedm** [comment]
@candrapersada 
thanks for suggestion, 
unfortunately, it has some drawbacks,
- let's say user wants to download a big file(e.x. 10 GB) to D: partition (which has plenty space), and he doesn't have enough space on C: partition (where temp folder lives), what should the user do? uninstall applications from program files
- also, if user used a tool to clean up temp while downloading in progress it will crash the application 
- high change of windows freeze or crash if c: drive get filled while downloading

IMO, the cleaner approach is to store everything on the same target download folder, 
if temp folder looks ugly, i will consider give it a "hidden" attribute in next releases

**Comment by candrapersada** [comment]
> let's say user wants to download a big file(e.x. 10 GB) to D: partition (which has plenty space), and he doesn't have enough space on C: partition (where temp folder lives), what should the user do? uninstall applications from program files

but the temporary folder can be put in another place, for example

temporary directory `D:\temp` download directory `E:\download` or temporary directory `D:\temp` download directory `C:\Users\uer\download` or temporary directory `D:\temp` download directory `D:\download`

**Comment by firedm** [comment]
to think of a better solution i need to understand what is the actual problems of temp-folders stored in download folder?

**Comment by candrapersada** [comment]
FireDM breaks a file into multiple parts when you start a download, these parts will be stored in this temporary directory: `D:\FireDM\temp` Once the download is complete, FireDM combines these parts into a single file and moves it into the directory set by the user.
so that video files are not corrupted when stored in the download directory on an `E:\download` External USB.

**Comment by firedm** [comment]
> so that video files are not corrupted when stored in the download directory

still didn't get it, how the files will get corrupted if temp folder stored in same download folder, what is the cause of corruption, did you have any problem before, or you think it might get corrupted

**Comment by candrapersada** [comment]
due to usb overperformance when FireDM breaks a file into multiple parts when you start a download After the download is complete, FireDM combines these parts into one which makes USB slow and crash

**Comment by firedm** [comment]
> due to usb overperformance when FireDM breaks a file into multiple parts when you start a download After the download is complete, FireDM combines these parts into one which makes USB slow and crash

now i understand your actual problem, 
i will try to find a solution that can work on both windows and linux
