### ISSUE TITLE
[Feture Request] Better proxy input

### ISSUE THREAD

**Issue by tazihad** [firedm/FireDM#285]
I liked the previous proxy field with radio button. It was easy to copy and paste. It was more convenient for people like me who uses regular proxies. 
Requesting to make the proxy input field to what was in previous version.

new: 
![new](https://user-images.githubusercontent.com/19417232/135217153-e8e16f69-dc33-47d2-a720-0ed8d8fd3f24.png)

old requested:
![old](https://user-images.githubusercontent.com/19417232/135217189-65a18eac-7dc9-4a34-a711-ad8c1edc5083.png)
:

**Comment by firedm** [comment]
@tazihad 
for simplicity, we'll add one button with drop down menu to add the selected prefix automatically
