### ISSUE TITLE
Setting [use server timestamp] not saved

### ISSUE THREAD

**Issue by smaragdus** [firedm/FireDM#286]
@firedm 

When I go to settings and select check box:

`use server timestamp as a "last modified" property for downloaded file`

exit [FireDM](https://github.com/firedm/FireDM) and then restart it this setting is not saved and I have to select this check box any time I start the program.

**animated screen:**

![FireDM 2021 09 28 - 2021-10-10 - timestamp - 007](https://user-images.githubusercontent.com/9025757/136711480-86c4448b-bf1b-4e21-aa10-8c12880aa6a4.png)

I had a look at the configuration file (`setting.cfg`) and I did not find this option in it.

Can you confirm that **use server timestamp** check box when selected is not preserved after restart?

I think that **use** has to be capitalized- **Use**:

- **Use server timestamp...**

in stead of:

- **use server timestamp...**

for a more unified look of the Settings panel.

I also noticed something else- when I download a file with another download manager, **created** and **modified** times are **equal**:

**screen:**

![FireDM 2021 09 28 - 2021-10-10 - timestamp - 010](https://user-images.githubusercontent.com/9025757/136711690-afa0222a-ba8b-45e7-ace8-539fb4e5c71c.png)

But when I download a file using [FireDM](https://github.com/firedm/FireDM), **created** and **modified** times are **not equal**:

**screen:**

![FireDM 2021 09 28 - 2021-10-10 - timestamp - 011](https://user-images.githubusercontent.com/9025757/136711728-9677a98f-0e6a-45fd-9f12-8661a8d039c0.png)

Is there a way to fix this so that **created** and **modified** times would be **equal**?

Regards

**Comment by firedm** [comment]
by the way, i like your screenshots, and the animated gifs :)
which app you use for this

**Comment by smaragdus** [comment]
@firedm 

> by the way, i like your screenshots, and the animated gifs :)
> which app you use for this

First I took two normal screen shots with the same size (in this case I used commercial [FastStone Capture](https://www.faststone.org/FSCaptureDetail.htm) to edit them but any free tool would do the job) and then used a free and open source tool:

- **APNG Assembler**
  - [Website](http://apngasm.sourceforge.net/)
  - [SourceForge](https://sourceforge.net/projects/apngasm/)
  
to assemble them, first I added the screens via drag&drop, screen:

![APNG Assembler 2 91 - 2021-10-11 - 001](https://user-images.githubusercontent.com/9025757/136718236-7e05485d-8b82-4b1c-9224-3ca1d07dd3b8.png)

and then I set the delays, screen:

![APNG Assembler 2 91 - 2021-10-11 - 002](https://user-images.githubusercontent.com/9025757/136718271-7a63acf9-438e-483b-8370-84fa671f6b8a.png)

This APNG Assembler can assemble PNG files (as many as you'd like) in case they have the same dimensions.

There are more simple and open source tools by [this developer](https://sourceforge.net/u/maxst/profile/).

Regards

**Comment by smaragdus** [comment]
@firedm 

Can you confirm that **use server timestamp** option is not saved?

**Comment by smaragdus** [comment]
@firedm 

> i already fixed this one in code, and it will be available in next release

This was fast! Thanks.

**Comment by smaragdus** [comment]
@jdaniele71 

> I don't know how FireDM works on temp, but the file could be created when the download starts and finalized at the end of the download. That could explain the difference...maybe... :)

I supposed something like that was causing the difference.

**Comment by smaragdus** [comment]
@firedm 

I did some tests using the latest version- [2021.11.4](https://github.com/firedm/FireDM/releases/tag/2021.11.4) and I think that the problem is fixed, so I will close the issue, thanks!

**Comment by smaragdus** [comment]
Actually it turned out that the time stamp that [FireDM](https://github.com/firedm/FireDM) sets is not equal to the original time stamp- there are 2 hour difference, screens:

[FireDM Releases](https://github.com/firedm/FireDM/releases):

![FireDM 2021 11 04 - 2021-11-04 - time stamp - 004](https://user-images.githubusercontent.com/9025757/140424867-0f6ea750-ff35-4666-9a60-ac26d0b7df20.png)

**other download manager - time stamp - 2021-11-04 10:45:**

![FireDM 2021 11 04 - 2021-11-04 - time stamp - 005](https://user-images.githubusercontent.com/9025757/140424992-1bc90106-cf51-4df0-b4d3-e153c5b15baa.png)

**FireDM - time stamp - 2021-11-04 08:45:**

![FireDM 2021 11 04 - 2021-11-04 - time stamp - 006](https://user-images.githubusercontent.com/9025757/140425069-94e049a2-e231-4975-8235-a05d4f7782f9.png)

I was negligent and closed this issue prematurely.

**Comment by firedm** [comment]
Thanks @smaragdus  for these sharp notes, i didn't notice it

I know why this happening,
FireDM use server time with "gmt" and doesn't correct for user timezone

this is what server sent 
'last-modified': 'thu, 04 nov 2021 08:45:26 gmt'

will check this point, and correct it, at least we are half-way done

**Comment by smaragdus** [comment]
@firedm 

It seems that in version [2021.11.18](https://github.com/firedm/FireDM/releases/tag/2021.11.18) this issue is fixed- I downloaded files with [FireDM](https://github.com/firedm/FireDM) and compared their time stamps with the time stamps of the same files downloaded with other download managers and they match!

**Thank you very much!**
