### ISSUE TITLE
Dark theme inspired from IDM

### ISSUE THREAD

**Issue by tazihad** [firedm/FireDM#287]
I have added a dark theme inspired from IDM. Hope you like it.

```
{
    "idm": {
        "MAIN_BG": "#393939",
        "SF_BG": "#202020",
        "SF_BTN_BG": "#7A7A7A",
        "PBAR_FG": "#06B025",
        "SF_CHKMARK": "#C6C6C6",
        "THUMBNAIL_FG": "#797979",
        "THUMBNAIL_BD": "#797979",
        "BTN_FG": "white",
        "BTN_HBG": "#C6C6C6",
        "BTN_ABG": "#C6C6C6",
        "HDG_FG": "white",
        "SBAR_BG": "#171717",
        "SBAR_FG": "#4D4D4D",
        "RCM_ABG": "#414141",
        "RCM_AFG": "white",
        "SEL_BG": "#004D8A"
    }
}
```

**Comment by candrapersada** [comment]
why is there only a share theme button with the clipboard and why there is no paste or import theme button.
![image](https://user-images.githubusercontent.com/36833664/137219680-4485f66e-e07c-4282-b22a-610ec54f4190.png)

**Comment by firedm** [comment]
> why there is no paste or import theme button. ![image](https://user-images.githubusercontent.com/36833664/137219680-4485f66e-e07c-4282-b22a-610ec54f4190.png)

@candrapersada 
good idea, will add it
