### ISSUE TITLE
Stream quality and default stream

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#294]
Hi, 
when accessing the stream quality section of a Youtube video, I can see a lot of streams, and sometime I can't tell what the difference is.
For example, in the following image which is the difference between mp4 - 1080, webm 1080 and extra streams mp4 - 1080?
![FireDM_Stream_Quality](https://user-images.githubusercontent.com/69006279/138173896-600cff25-f52e-48c0-9cb3-4f3a954b3982.PNG)

**Feature request**:
Could you please add an option in the settings to choose the preferred:
- quality section (video streams, audio streams, extra streams)
- file format (mp4, webm, aac, mp3....etc)
- resolution (2160, 1080, 720....) 

It would be nice to have it also as options to choose when downloading a Youtube channel.
For example, let's say i set the settings as [Video stream, mp4, 720], i could live it as is click the button download all, or for this specific channel, i could change the resolution to 1080, or change the file type [audio stream, mp3] before downloading.

Even if i select one video a time, i will see the preferred stream quality option already selected, so I have just to click "Download".

Thanks

**Comment by firedm** [comment]
@jdaniele71 
thanks for reporting

> Feature request:
Could you please add an option in the settings to choose the preferred:
 quality section (video streams, audio streams, extra streams)
 file format (mp4, webm, aac, mp3....etc)
resolution (2160, 1080, 720....)

sound a good idea, will be added in todo list

> For example, in the following image which is the difference between mp4 - 1080, webm 1080 and extra streams mp4 - 1080?

mp4 - 1080 has mp4 extension, and webm 1080 has webm extension

to explain the extra streams section lets first mention the following:
- Normal video: is a video file which has both video and audio in one file.
- Dash video: is a video file with no audio

downloading normal video is straight forward like any single file 
downloading a dash video requires downloading video stream + a proper audio from available audio streams, then after downloading, both video and audio will be merged together in one file container

in case we have normal video and dash video with same specs we put normal video under "video streams" and dash video under "extra streams"

**Comment by firedm** [comment]
done in new playlist window

**Comment by joshatt** [comment]
> in case we have normal video and dash video with same specs we put normal video under "video streams" and dash video under "extra streams"

Good to know. Maybe change "video streams" to "video+audio", and "extra streams" to "video without audio"? would be much easier for newbies to understand.

**Comment by Aboghazala** [comment]
> Good to know. Maybe change "video streams" to "video+audio", and "extra streams" to "video without audio"? would be much easier for newbies to understand.

@joshatt 
"video streams" category has normal and dash videos also, only repeated dash will be put under "extra streams"

and to explain further, you will get video file with audio whether you select normal or dash, the difference is just technical, i.e. there is extra steps done by FireDM like downloading proper audio and merge it with the dash video file

after all
i believe we should remove these "extra streams" category since it has no benefit at all

**Comment by joshatt** [comment]
> > Good to know. Maybe change "video streams" to "video+audio", and "extra streams" to "video without audio"? would be much easier for newbies to understand.
> 
> @joshatt "video streams" category has normal and dash videos also, only repeated dash will be put under "extra streams"
> 
> and to explain further, you will get video file with audio whether you select normal or dash, the difference is just technical, i.e. there is extra steps done by FireDM like downloading proper audio and merge it with the dash video file
> 
> after all i believe we should remove these "extra streams" category since it has no benefit at all

Thanks.
