### ISSUE TITLE
Broken download list

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#295]
I have more than 500 items in the download list and scrolling it down, I can see that...
![FireDM_broken_list](https://user-images.githubusercontent.com/69006279/138183313-19ebd681-9d42-47bf-83e1-86455ac716f0.PNG)

Thanks
Daniele

**Comment by jdaniele71** [comment]
Thanks a lot!
Daniele

**Comment by jdaniele71** [comment]
Hi,

sorry to write again in this issue but the workaround you implemented will not work.
As far i can see, the "mix" view shows full sized video items until they are completed.
If i add 500 videos, in the first instance they will be all showed as full sized items, getting the broken list issue again.

I would suggest you to reopen this issue, and follow one of the options below:
- make "compact" the default (easy but poor solution)
- change the way how mix works: mix will show full sized items only after started and before completed (and paused as well). Everything not yet started or already completed, will get a compact sized item.
- create a new "active-mix" view doing as described above, and set it as default.

Thanks
Daniele

**Comment by firedm** [comment]
Thanks Daniele for this suggestion, will check this out

**Comment by jdaniele71** [comment]
> Thanks Daniele for this suggestion, will check this out

You are welcome, thanks to you. 😀

**Comment by firedm** [comment]
@jdaniele71 
please check if problem resolved with compact or mix view

**Comment by jdaniele71** [comment]
Hi @firedm 

I made a progressive test, adding items to the download list:

100 items, no issues
200 items, no issues
300 items, compact/mix ok. bulk made the application crash and CLOSE after few seconds, while still redrawing the window!

More over, after crashing and reloaded, it LOST ALL THE CHANGES i did to the download list:
- I deleted all the items before the test, and they reappeared (**ZOMBIES!!!!** #325 )
- I added 300 downloads and they disappeared 

To fight zombies, first, watch this video [https://www.youtube.com/watch?v=OsEtxdLM-cY](url) 😂, than, try to save to file the downloads list content as soon as it changes... 😉

Thanks
Daniele

**Comment by firedm** [comment]
> To fight zombies, first, watch this video [https://www.youtube.com/watch?v=OsEtxdLM-cY](url) , than, try to save to file the downloads list content as soon as it changes...

:laughing: I think we should restrict bulk view to 100 items, it is so heavy already
also will consider saving dlist on every change.

**Comment by jdaniele71** [comment]
> 😆 I think we should restrict bulk view to 100 items, it is so heavy already also will consider saving dlist on every change.

Yes, or you could paginate the view, with no more than 100 items.🙄

Saving is very important. I lost the time and the items in the list i wanted to start.
I really hate to do things twice because of a failure! 🤬😅😅
