### ISSUE TITLE
Add video/audio duration to the bottom panel

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#296]
Hi,

am i blind or there is no video duration info when we select a video / audio in the main screen (home)?

![FireDM_missing_duration](https://user-images.githubusercontent.com/69006279/138183778-48769019-ffe0-4b6c-b60e-2a75f29e2956.PNG)

That's very strange.

**Feature request:**
Could you please add it in the bottom panel?

Thanks
Daniele

**Comment by fidele000** [comment]
@firedm 
@jdaniele71 
Should i help on this?

**Comment by firedm** [comment]
@fidele000 

> Should i help on this?

sure, go ahead, and let me know if you need help to clarify anything in firedm code

**Comment by firedm** [comment]
@fidele000 
please don't forget to pull first to get latest files updates before issuing your PR (to prevent conflict)

**Comment by fidele000** [comment]
@firedm  sure, got it

**Comment by fidele000** [comment]
I created a this PR #338 about this issue, @firedm help to understand how GUI work to add it on view, i thought about adding a callback function to check if it's audio or video file before calling the function to prevent some erros too

**Comment by jdaniele71** [comment]
@fidele000 
@firedm 
@Aboghazala 
So good! Thanks for the effort! 👍
