### ISSUE TITLE
Download list selection filter should help me more and not get unresponsive

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#297]
Hi,

when i select not completed video, and there are many video in the list, there is no way to see only them.
I have to scroll down the list up to find them one by one.

**Feature request:**
It would be nice have a ckeckbox on the side of the little menu, to show only the selected.

![image](https://user-images.githubusercontent.com/69006279/138184535-197ff09b-8054-4203-b48a-035b1a222b52.png)

**Feature request:**
Could you add more options to the filter?
- Failed
- Paused
- Cancelled
- Scheduled
- Downloading

**Bug:**
While selecting many items by filter, the interface takes many seconds, counter goes but at a certain point, the entire UI becomes unresponsive:

![image](https://user-images.githubusercontent.com/69006279/138184642-65ce5e67-ed9e-445c-b611-3cd52fc4f36e.png)

Thanks
Daniele

**Comment by firedm** [comment]
@jdaniele71 
in latest firedm version "2021.9.28" there is a filter button that you can select different criteria

![image](https://user-images.githubusercontent.com/58998813/138372577-8f9ad2d3-82ae-4f99-866d-18c834011a34.png)

> Bug:
While selecting many items by filter, the interface takes many seconds, counter goes but at a certain point, the entire UI becomes unresponsive:

for this behavior, will investigate the problem and see what is the cause

**Comment by jdaniele71** [comment]
Great, thanks! 
Daniele
