### ISSUE TITLE
Annoying page switch at every download button click!

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#299]
Hi, 

imagine you have a Youtube channel with 200 videos and you wanna download all, selecting the proper video resolution that is not the best available, ok?
Every time I select the video in the list, the resolution and then click the "Download" button, the page switch to the download page...
It could be good for just one video, but for 200, you have to click back to home 200 times, and start again.
It double the time for selecting the videos.

**Feature request:**
Could you please make an option like "Do not show download list on download" in the settings?

**Feature request:**
Could you also keep the last download mode on the button?
For example, if i wanna just add 200 video to the download list without starting them, i have to select for 200 time the "Download later" option on the button. 
I would like the button changes to "Download later" after the first time, so i will have just to click it, and that is faster!

Thanks

**Comment by firedm** [comment]
@jdaniele71 

> but for 200, you have to click back to home 200 times, and start again.

No!, you don't have to do this, for downloading channels/playlist you should use download playlist button
![image](https://user-images.githubusercontent.com/58998813/138373288-b587d9d0-c555-4a3c-8051-3f0f12edf7dd.png)

and here is a screenshot of playlist example
![image](https://user-images.githubusercontent.com/58998813/138373389-888010f7-7319-49d3-a364-6c4d7e5fe946.png)

you can select Quality for all videos, select individual videos and download later if you want

**Comment by jdaniele71** [comment]
Ok, thanks, I will try it!
