### ISSUE TITLE
UI Becomes Unresponsive After 10 Minutes

### ISSUE THREAD

**Issue by AndrewISampson** [firedm/FireDM#305]
Hi,

No matter what combination of "Concurrent downloads" and "Connections per download" I use, after about 10 minutes, the UI becomes unresponsive and I have to close FireDM using the SysTray icon. It also doesn't matter if I am downloading a single video or 100+, the UI will just crash

If FireDM has called FFMPEG and I have to close FireDM, then the video it was working on gets screwed up (usually, either only the video or the audio part is outputted) and I have to download the file again.

I am running the FireDM exe on Windows 10. I have attached Windows specs, CPU and memory utilisation at point of UI becoming unresponsive and FireDM versions.

Regards

Andrew

![Computer specs](https://user-images.githubusercontent.com/49162904/138553643-fd366697-5c85-4abb-ba79-c4ef0d21e894.JPG)
![CPU utilisation](https://user-images.githubusercontent.com/49162904/138553644-c956bb24-a048-4b34-b54d-952d1dc015f0.JPG)
![FireDM versions](https://user-images.githubusercontent.com/49162904/138553645-b0a023d9-14e8-4e9b-bf29-6dfad9d73120.JPG)
![Memory utilisation](https://user-images.githubusercontent.com/49162904/138553646-3baf3c7b-2e38-434a-973f-a09af4a09cce.JPG)

**Comment by firedm** [comment]
@AndrewISampson 
please check with new FireDM version 2021.11.4 if you still have same problem when you select youtube-dl  as a video extractor engine

**Comment by smaragdus** [comment]
@firedm 

I haven't tested new versions of [FireDM](https://github.com/firedm/FireDM) extensively but so far I have not noticed the program becoming unresponsive. What exactly should I need to do trying to reproduce this issue?

**Comment by firedm** [comment]
@smaragdus 



> I haven't tested new versions of [FireDM](https://github.com/firedm/FireDM) extensively but so far I have not noticed the program becoming unresponsive. What exactly should I need to do trying to reproduce this issue?

Thanks a lot, the same on my windows machine, couldn't reproduce the error
I think it is a special case where youtube-dl caused an issue on @AndrewISampson's machine

**Comment by AndrewISampson** [comment]
I did a complete download of the new version (rather than updating via the UI) and whatever the issue was, it has gone. UI is now fully responsive on both extraction engines.

Thanks for putting up with my weirdness :)

**Comment by firedm** [comment]
> I did a complete download of the new version (rather than updating via the UI) and whatever the issue was, it has gone. UI is now fully responsive on both extraction engines.
> 
> Thanks for putting up with my weirdness :)

Great, to know things are working fine for you
