### ISSUE TITLE
Playlist download window - Items not selected on page 2

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#309]
Hi, 

I'm trying to use the playlist download window (FireDM 2021.9.28 win), and i noticed that checking the "select all" checkbox, it correctly select all the videos in the first page (100 videos) but clicking on next to see the page 2, videos are not selected (while the flag "select all" is still selected).

I think it is not correct.

This is what i see:

![image](https://user-images.githubusercontent.com/69006279/139051823-f36a185c-ac85-48ce-b496-2a3cb8c6d679.png)

Thanks
Daniele

**Comment by firedm** [comment]
@jdaniele71 
please check if this issue is fixed in the new version

**Comment by jdaniele71** [comment]
@firedm 
Yes, it has been solved.
The commit solved also point 8 of #321 

Thanks
Daniele
