### ISSUE TITLE
Playlist download window - select all on last page (and enhancements)

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#313]
Hi, 

i'm here on this video channel: [https://www.youtube.com/c/masterwongsystem/videos](url)
There are more than 2500 videos.
I opened the playlist download window and i went to the last page (26) where there are only 41 videos.
Then i clicked on "select all" and magically FireDM selected 100 videos....WOW... 😅
So, my suspect is that it selected videos before the page 26...

Top of page 26:
![image](https://user-images.githubusercontent.com/69006279/139316141-e537484f-3083-46bd-b82d-d9ad4a172e2f.png)

end of page 26:
![image](https://user-images.githubusercontent.com/69006279/139316195-384dd4db-d12c-457a-ad67-10ed005543d0.png)

Notice also another thing that can support my hypothesis: the maximum detected video quality is 480, but no one of the 41 videos on the page has that resolution available. FireDM probably found it on more recent videos on page 25...

The proof of that is by going on page 25:

![image](https://user-images.githubusercontent.com/69006279/139316996-6ad5d81b-eb9c-4aaa-93ef-4e335d54c8cf.png)

As you can see, 100 items are selected from 2442 to 2541, crossing the boundaries of pages.

Now, if I click again on "select all" (already checked), it deselects the videos on page 25, living selected the 41 videos on page 26. This is what i wanted originally.

![image](https://user-images.githubusercontent.com/69006279/139317679-c5f3196d-6849-4595-91be-c2c2163a133a.png)

But look at the quality, it didn't change back to 240, even if there is no video selected with 480, so it is out of sync.

Apart from fixing that strange behavior, I have some enhancement I wanna share with you.

1) 
"select all" should NOT be a checkbox. If I click on that, it will select all the videos on the page, ok, than i deselect half or all of them one by one. Now, what do we have? The checkbox is completely out of sync. And would be out of sync even if I just deselect one video. So, actually, "select all" is just a "command" we ask to be executed on the current page at this very moment.
After the command has been executed, FireDM shouldn't have any responsibility about what will happen next...
So I would change it to a button or multi-option button...
It also should have a counter part "deselect all".

2) 
OK, i have just opened the playlist page, and i wanna download all the videos, and when i say "all", I mean "ALL" of the channel/playlist.
Now, I have to click on "select all", wait that everything is selected, than click next, than select all again, this for 26 times (26 pages).
So i think it would be useful a to split the select all command in two: "select all on this page", "select the full playlist".

3)
I think it is very rare that an user want to download exactly 100 videos of a channel fitting exactly in the first page.
I thought to some use cases:

A) The user wanna download everything (covered on point 2)

B) The user wanna download most of the videos on this first page, so could be useful to select only the current page (point 1) and than deselect manually some video, what he doesn't need.

C) The user is interested to download groups video of tutorials, that usually cross the boundaries of pages.
In this case, selecting by pages is not so useful, selecting all pages, the same.
So it should be a way (you already implemented in the download list) to select groups of video click -> (shift+click) and a right-click to have a context menu "select for download". 
If i try to do it now, it doesn't work because at first click, the checkbox of the video become already selected and there is no way to multi-select items in the playlist.

4)
Ok, I have 2500 videos in the playlist, I wanna download them all BUT the videos below a certain quality.
If i select all the videos, than i have to deselect one by one on 26 pages the videos that are below for example 480. 
It would be a tedious task. That's because as far as I understand, the "Quality" is the maximum quality the user wanna download.
What about adding a second dropbox for the minimum quality?
So i could select:
Max quality: mp4 - 720
then
Min quality: mp4 - 480  
(and if I have selected videos not supporting this quality, an alert will ask me if I wanna deselect X videos from download)

Well, i wrote a lot, maybe too much for you... 😅

Thanks for you time.
Daniele

**Comment by formlessdao** [comment]
> 
> 
> Still talking about quality setting in the playlist, i think i found a problem. If the selected quality is not available for a specific video but it has better resolutions, FireDM takes the best one available!
> 
> Here i selected 480 but in the first video you can see 1080!!
> 
> ![image](https://user-images.githubusercontent.com/69006279/139352282-bbca7a0c-e33f-44ae-8c53-5313cbe84027.png)
> 
> Opening the resolutions available for that video, the 480 is missing... ![image](https://user-images.githubusercontent.com/69006279/139352385-c151b3fb-8577-4e95-b53d-34a71a606dbf.png)
> 
> I think FireDM selected the wrong resolution (1080) because i asked for a maximum of 480. It should select 360 that is the closest just below. Am i wrong?
> 
> Thanks Daniele

How do you download all videos from a playlist? what are the steps?

**Comment by jdaniele71** [comment]
> How do you download all videos from a playlist? what are the steps?

1. Open FireDM
2. Select the playlist link (for example on youtube) 
3. Ctrl-c to copy to clipboard  (you can also copy in other ways)
![image](https://user-images.githubusercontent.com/69006279/139559678-f3409530-245c-41df-b168-279b5d634daf.png)

4. FireDM will catch the clipboard link and will show the home page with all the videos
5. Click on the playlist button
![image](https://user-images.githubusercontent.com/69006279/139559561-0c11e5a8-d5d0-4aee-9216-8fb0c3f0cb06.png)

6. Onto the Playlist window, click on "select all" and than on "Next" button, repeating this step for every page...
![image](https://user-images.githubusercontent.com/69006279/139559627-516d661b-a7c1-4940-abf9-a553daf0d025.png)

7. Select the video quality you desire (and check that all the video have the correct quality otherwise change the quality on those videos manually)
![image](https://user-images.githubusercontent.com/69006279/139559738-e87883e6-520c-4115-9582-8974bcc6e932.png)

8. Click on the download button

**Comment by formlessdao** [comment]
Thank you so much i appreciate you taking the time to make that detailed step by step guide!

**Comment by jdaniele71** [comment]
> Thank you so much i appreciate you taking the time to make that detailed step by step guide!

It was my pleasure. You are welcome! 😊
