### ISSUE TITLE
Playlist auto-numbering in reverse order and formatting

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#316]
Hi,

i wonder if could be reversed the order the playlist assigns a progressive number to the videos.

Imagine you have a playlist with 5 videos:

1- video 5
2- video 4
3- video 3
4- video 2
5- video 1

Let say I today download them on a folder related to the youtube channel.

Tomorrow, there are 3 more videos.  Look what happens to numbering:

1- video 8
2- video 7
3- video 6
4- video 5
5- video 4
6- video 3
7- video 2
8- video 1

As you can see, The video 5, before got number 1, now is number 4.
So when i download the last 3 new videos, this will the final result in my folder:

1- video 8
2- video 7
3- video 6
1- video 5
2- video 4
3- video 3
4- video 2
5- video 1

ordered would be:

1- video 5
1- video 8
2- video 4
2- video 7
3- video 3
3- video 6
4- video 2
5- video 1

Not so good.

Reversing numbering, every new video added will get a number greater than previous ones, so won't be conflicts between incremental downloads.
It has also a sense: the number 1 is the first (oldest one) video.

Would also be nice to have a zero padding.
With very long playlists, with more than a thousand videos, the numbering will fit progressively from 1 to 4 characters

1000- video 1000
100- video 100
10- video 10
1- video 1

Awful... 😂

I would like to see:

1000- video 1000
0100- video 100
0010- video 10
0001- video 1

With 4 fixed characters, we can mange 9999 videos, good enough for most applications.

Would be also very useful to have an used defined prefix we can add before numbering.
For example, I would like to uniquely identify a video on youtube, prefixing a contraction of the channel name.

CDE0002- video 2

Actually I would like the date....but i know it would be more difficult to extract the youtube date from the video page:

CDE20211030- video 2

Thanks
Daniele

**Comment by candrapersada** [comment]
https://github.com/firedm/FireDM/issues/276#issuecomment-929246627

**Comment by jdaniele71** [comment]
Hi @firedm ,

will this feature be included in the next release (at least the reverse order)?
I'm getting mad to download hundreds of video and the next day the whole playlist numbering changed by 1...WTF! 😅

Thanks
Daniele

**Comment by firedm** [comment]
no problem will add reverse numbers as a temporary fix

**Comment by jdaniele71** [comment]
> no problem will add reverse numbers as a temporary fix

Hi @firedm , what do you mean with temporary?
How would you solve the issue definitely?

Thanks
Daniele

**Comment by firedm** [comment]
> Hi @firedm , what do you mean with temporary?
How would you solve the issue definitely?

i mean we would add more options to manipulate names like template, then you can add channel name, zero padding, etc...

**Comment by jdaniele71** [comment]
> i mean we would add more options to manipulate names like template, then you can add channel name, zero padding, etc...

So good, oh yes thanks, as well as free text like:  List1-{filename}_{date}.{ext}
In the future, a user could save the templates and associate them to favorites playlists...( #328 )
In that way, when i download from a specific playlist, i know the app will automatically select the associated format template to save the file... 🤩

More over, if I'm downloading from multiple playlists at the same time, it would be nice to have an option to choose the destination directory for every downloading group of video (just before click "Download") , so they won't be mixed in the same folder.

Thanks
Daniele

**Comment by firedm** [comment]
will add this too, [choose download folder in playlist window]

**Comment by candrapersada** [comment]
and why the download queue is not sequential for example 1 is below and 5 is above but when I start downloading directly to 3, 2, 5, 4, and 1?

**Comment by firedm** [comment]
@candrapersada 
this is what happen, playlist window will send video numbers to controller say 1, 2, and 3
controller will ask server (e.g. youtube server) to send files metadata, then server send metadata for example 2 first, then 1, then 3
whatever file has its metadata ready will be added to downloads list first, in that example will be 2, 1, and 3

anyhow, we'll try to fix this to make things work as expected
