### ISSUE TITLE
easier selection of multiple videos from the playlist

### ISSUE THREAD

**Issue by sidmint** [firedm/FireDM#317]
selecting multiple videos from a playlist is tedious- scroll many times and select check boxes using cursor. An easier way is coveted. Also I can automate the process then for say, selecting/deselecting consecutive 100 videos.
It can be done in many ways:

1.  Like using keys to switch and select videos quickly.

2. and/or a faster way through mouse clicks. One example is of Downline app where a close appears at the same place for every video's tile and clicking on close button of one tile brings/slides the close button of next tile automatically under the cursor for next click. This way i used to click 50 times at a same place for removing 50 consecutive videos [to download the rest].

3. and/or through typing the ranges. eg: 2-8, 17, 50-100

4. and/or through what we make in a file manager using ctrl and shift keys for individual and range selections

But most importantly, I want to thank you all people responsible for this app. After years of hopping, I think this is the ultimate app on Linux at least. You people have left similar apps far behind. I was in trouble since a long time to find a proper app on Linux until I found this. Thank you Thank you. The features are like a premium app though looks can be improved with time, not a big deal anyway as functionality matters more.

**Comment by sidmint** [comment]
can be related to #313, #290 depending on implementation.

**Comment by firedm** [comment]
> and/or through what we make in a file manager using ctrl and shift keys for individual and range selections

i would go with this option, similar to the downloads tab selection method

**Comment by formlessdao** [comment]
How do you download all videos from a playlist? I don't see this mentioned in your guide.

**Comment by firedm** [comment]
@formlessdao 
there is no option yet to download [ALL] videos in playlist, since videos need to  be selected one by one in playlist window, 

but this option will be added in the future

**Comment by formlessdao** [comment]
What do you mean select one by one? I tried but I can't figure out how. Can you post a gif showing it or some screenshots?

**Comment by firedm** [comment]
there is a playlist button, check below


![image](https://user-images.githubusercontent.com/58998813/139559816-120095d3-85ae-4ced-94bf-f8181ab2aa2b.png)

**Comment by formlessdao** [comment]
Thanks. Seems you do have a "select all" button so that's very close to what I needed.

One problem is that no size for the webm formats is generated, only the MP4 formats show the size and i can determine the total download space I need for all the files in the playlist.

Also I am not certain that total download space needed is correctly approximated because audio tracks seem to not be counted.
