### ISSUE TITLE
Suggestion: Make FireDM remember the window size / open/run always maximized

### ISSUE THREAD

**Issue by KNTRO** [firedm/FireDM#318]
Hello,

Until now, it has happened twice: I click on the wrong "X" and close the background, full-screened program, instead of closing FireDM. 😅

As you can see in the screenshot below, FireDM doesn't run in a maximied, full-sized window. For inertia, when I want to close a program, my hand works faster than my mind [😱] and I click on the "X" symbol, in the upper right corner, without even thinking, and what I get is this: I just close any other program —in the screenshot, Mozilla Firefox— instead of closing FireDM.

![FireDM_window](https://user-images.githubusercontent.com/2568821/139625057-01df1655-c351-415f-8fd5-9c156c710920.jpg)

So, I suggest you to make FireDM remember its window size and run maximized —if I used it full-sized last time. Please!

Thank you so much for reading! 🙂

**Comment by firedm** [comment]
a fix applied for this, firedm will remember the last maximize state and restore it when started again, 
and also added an option in settings to always start maximized.
option will be available in coming release
