### ISSUE TITLE
Unable to Download FireDM on windows.

### ISSUE THREAD

**Issue by sujalgoel** [firedm/FireDM#319]
I downloaded the **highlighted** zip file from here and extracted the files but I didn't find any `FireDM.exe` file.
![image](https://user-images.githubusercontent.com/67121014/139722350-7131a69a-07e3-455d-9823-232b624b66ef.png)

![image](https://user-images.githubusercontent.com/67121014/139722177-325bd018-a749-4f4f-81b3-07002c39065a.png)

So, what am I supposed to do?

**Comment by jdaniele71** [comment]
Hi @sujalgoel,

you simply downloaded the source code, not the zip with binaries.
The content you showed is exactly belonging to the source code zip file.

When you download both, you can see that the name differs by one character so it is very easy to take one for another.
Please download it again paying attention to what you download and extract.

@firedm, could you change the name of source code zip file adding something like "_source" ?

Thanks
Daniele

**Comment by jdaniele71** [comment]
@sujalgoel 
More over, do not launch "FireDM.exe".

Launch instead "FireDM-GUI.exe".
Bye.
Daniele

**Comment by firedm** [comment]
@sujalgoel 
the one you are highlighting in yellow is the correct one, but i think you accidentally clicked the link below it which labeled "Source code (zip)"

you can try again, or here is a direct [link](https://github.com/firedm/FireDM/releases/download/2021.9.28/FireDM_2021.9.28.zip)  

and as @jdaniele71  said, after extract, you better launch application from "FireDM-GUI.exe"

**Comment by sujalgoel** [comment]
Thanks! It's working...
