### ISSUE TITLE
Playlist download window - Not responding

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#322]
Hi,

I've just opened (again) the Playlist window, and I have been clicking on "Next" button (a bit rapidly) and suddenly, at page 20 of 26, the window became not responding anymore...
Unfortunately it is not the first time it happens... 

![image](https://user-images.githubusercontent.com/69006279/139941903-782305fb-1880-4e1a-b16d-e6a110c0ea77.png)

I had to force the app to close... 
Obviously i did not see the log because the main windows was frozen as well..

Thanks
Daniele

**Comment by Aboghazala** [comment]
new playlist design inplace, problem fixed

**Comment by jdaniele71** [comment]
Thanks a lot!
