### ISSUE TITLE
Typo on Download Playlist hint

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#323]
Hi,

this is the typo:
![image](https://user-images.githubusercontent.com/69006279/139943373-2aa9431c-6bef-47bc-b7de-8e93617a1d30.png)

Thanks
Daniele

**Comment by firedm** [comment]
not sure why it is truncated, it show full word on Linux

![image](https://user-images.githubusercontent.com/58998813/139957812-0cb634b6-99b5-4c06-8318-190e662b7db5.png)

**Comment by jdaniele71** [comment]
> not sure why it is truncated, it show full word on Linux

Ok, i'm going to change my primary OS.... 😁

Seriously, with a very low priority, we should investigate which is the code that create the hint and if it responsible of the size of it, or if there is a direct call to the OS that will find the right size.
It would worth a try to add 1-2 spaces at the end of "Playlist" to help enlarging the hint window, as a workaround...

Thanks
Daniele

**Comment by firedm** [comment]
checked on both windows and linux and the tooltips are shown correctly
