### ISSUE TITLE
Playlist download window - Add first and last navigation buttons

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#324]
Hi,

is it possible to add two more navigation button "First" and "Last" to the window?
When there are many pages it tedious clicking next many times to get the last...

![image](https://user-images.githubusercontent.com/69006279/139944245-f4032a95-c8f1-4a26-99c3-62eb0fc05e45.png)

You could also substitute the "1 of 26" with a dropbox containing all the pages, so I will be able to select the page i want, directly. Alternative, a text box where i can input the page number will do the job as well (but it will need input validation).

![image](https://user-images.githubusercontent.com/69006279/139945073-3e849f0c-ae1b-42e6-a76c-a29e03ed8efa.png)

Thanks
Daniele

**Comment by firedm** [comment]
I think dropbox will be enough

**Comment by jdaniele71** [comment]
> I think dropbox will be enough

I agree with you.
Thanks
Daniele

**Comment by jdaniele71** [comment]
Thanks @Aboghazala !
Daniele
