### ISSUE TITLE
Zombies in the downloads list

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#325]
Hi,

sometimes happen strange things to the download list.
Initially i thought it was just my impression and i was wrong, but it is not the first time that i think "Hey, i remember i have removed these items from the downloads list...mmm..maybe i do not remember well....".

Today it happened again: i found old, already downloaded items in the list as "Cancelled".
As you can see in the image below, i already have got the video files.
Eventually, the items in the list should be marked as completed, not cancelled.
But I'm pretty sure i removed them from them list after completion, when i copied the files to the final destination folder.

So what's happening? Am I an idiot and my brain is blown out or is there something strange in the app?
Anyway, I will pay more attention to this list trying to understand when and how i happens, eventually... 😅

![image](https://user-images.githubusercontent.com/69006279/139949021-5dd51277-cc2a-4c99-874b-8b9cc983f5b5.png)

Thanks
Daniele

**Comment by firedm** [comment]
No idea what's happening, may be we need to add new filter called "zombies" :laughing:

**Comment by jdaniele71** [comment]
> No idea what's happening, may be we need to add new filter called "zombies" 😆

Yeeeeaaaa!!! So good! Please, do it! hahahah 😂😂

**Comment by Aboghazala** [comment]
now, downloads list will be saved after every change

**Comment by jdaniele71** [comment]
Thanks a lot!
