### ISSUE TITLE
Video errors delay and....replay!

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#327]
Hi,

I noticed two things about video errors.
1. Usually they come in burst, 50-100 in few seconds 
2. When i click on resume to retry downloading the file, it seems that it replays all the errors events before starting the download.

About 1, i would insert a delay between retries, maybe after 5 consecutive errors, we can put the file in "retry-standby", start to download another video, than come back and retry the first video again, if still errors, pass to another video and so on...
In that way, we are actually giving the time the issue to disappear (if it is transient).

About 2, this is what happens... Can anyone give me an hint on this behavior?

https://user-images.githubusercontent.com/69006279/139956109-e4e86b1d-8857-47bf-853d-656f44d63794.mp4

Thanks
Daniele

**Comment by firedm** [comment]
@jdaniele71 
this is intentional, usually youtube links has a very short life, and it get expired very soon, firedm will count 100 error trying to download the video file, then will refresh metadata and retry downloading again (default retries = 1), and if it failed again it will mark video as failed/error 
so no need to add delay between retries since it is a waste of time

**Comment by jdaniele71** [comment]
> @jdaniele71 this is intentional, usually youtube links has a very short life, and it get expired very soon, firedm will count 100 error trying to download the video file, then will refresh metadata and retry downloading again (default retries = 1), and if it failed again it will mark video as failed/error so no need to add delay between retries since it is a waste of time

ok, let me see if i have understood it well: when i click on resume, FireDM will first retry the last video link (expired) up to 100 errors, than it refreshes the metadata, and tries it again. Is that why i see the errors growing after a resume and than the download starts normally?
A curiosity: do we really need to get 100 errors in 5 seconds to understand that the video link is broken and and we have to reload the metadata?

Thanks 
Daniele

**Comment by firedm** [comment]
> A curiosity: do we really need to get 100 errors in 5 seconds to understand that the video link is broken and we have to reload the metadata?

in normal download you get errors e.g. server complains of too much concurrent connections / requests in same time, but the error counter will be reset once any worker receive valid data (beside connections number will be decrease to avoid these errors), so if you have 10 workers running, you will exceed 100 errors so quick.

in other words you can interpret it as "keep trying for 5 seconds" then refresh metadata and retry again.

another option is to rely on server response, which in ideal case will tell us "hey this link is expired" but as you know, internet is messy and most of these server doesn't respect standard, so relying on server response is fragile.

apart from that, I believe there is always a better idea, hope we can come up with better logic for this part

**Comment by jdaniele71** [comment]
OK @firedm , thanks for the explication.
What do you mean with "(**beside connections number will be decrease to avoid these errors**)"?
Will the number of connections decrease automatically to avoid errors?

Could a delay of 2-3 seconds between workers starting phase be a good strategy to avoid errors?
We could stop increasing the connections as soon as we get the first errors.

So, even if in options I set 20 connections per video, maybe I will get just 5-7 without errors.
It's like an "adaptive warm-up"...without a "connections bombing".
I think the servers will like FireDM more... 😉

Thanks
Daniele

**Comment by firedm** [comment]
> Will the number of connections decrease automatically to avoid errors?

yes, it will decrease gradually until it gets no errors or (allow only one connection) then will try to run more connections after a preset delay
the delay between trials is dynamically calculated based on error rate, check [dynamic connection manager](https://github.com/firedm/FireDM/blob/e0d456c592e4dd198946ae6557d1ff6b351b4ed0/firedm/brain.py#L415) for more info

> Could a delay of 2-3 seconds between workers starting phase be a good strategy to avoid errors?
We could stop increasing the connections as soon as we get the first errors.

there is already a (soft startup), i.e. 0.5 sec delay between workers, check this [comment](https://github.com/firedm/FireDM/blob/e0d456c592e4dd198946ae6557d1ff6b351b4ed0/firedm/brain.py#L324)

**Comment by jdaniele71** [comment]
> yes, it will decrease gradually until it gets no errors or (allow only one connection) then will try to run more connections after a preset delay the delay between trials is dynamically calculated based on error rate, check [dynamic connection manager](https://github.com/firedm/FireDM/blob/e0d456c592e4dd198946ae6557d1ff6b351b4ed0/firedm/brain.py#L415) for more info

> there is already a (soft startup), i.e. 0.5 sec delay between workers, check this [comment](https://github.com/firedm/FireDM/blob/e0d456c592e4dd198946ae6557d1ff6b351b4ed0/firedm/brain.py#L324)

Perfect! Thanks! Daniele

**Comment by Aboghazala** [comment]
@jdaniele71 
please confirm if you still have this problem with latest release, to be able to close this issue

**Comment by jdaniele71** [comment]
> @jdaniele71 please confirm if you still have this problem with latest release, to be able to close this issue

OK, I'm going to download it now...

**Comment by jdaniele71** [comment]
I installed it but no video errors encountered yet during few downloads. I will test it more when I will get any error.
Otherwise, if you have any advice to simulate a video error (unplugging the ethernet cable? :), i will check it ASAP.

Thanks
Daniele

**Comment by Aboghazala** [comment]
@jdaniele71 
great thanks, will close this issue for now
