### ISSUE TITLE
Playlist download window - Missing audio/video metadatas

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#332]
Hi,

one of the items in the list seems to have no audio/video metadatas.

Is it normal?

![image](https://user-images.githubusercontent.com/69006279/140445071-3506ae6e-0c0d-4d31-8a37-4edd7a4dc332.png)

Thanks
Daniele

**Comment by firedm** [comment]
this means firedm failed to retrieve metadata for this item, maybe because it is private video, or just need to try again
we should handle these failed items in better way, maybe failed item should be de-selected automatically, and will retry fetch metadata on re-selection by user

**Comment by jdaniele71** [comment]
> this means firedm failed to retrieve metadata for this item, maybe because it is private video, or just need to try again we should handle these failed items in better way, maybe failed item should be de-selected automatically, and will retry fetch metadata on re-selection by user

Ok, thanks @firedm 
Daniele
