### ISSUE TITLE
Download window - Active video filter does not refresh the list after status updates

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#333]
Hi,

I filtered the view by "Active".
The 3 videos you can see below were active at the moment i set the filter.
Than, i paused them because they were actually frozen.
Other 3 other downloads started automatically from the (hidden) list (you can see the active counter at 3) but the (active) view did not refresh the list.
It still shows the paused items...not the current active ones.

![image](https://user-images.githubusercontent.com/69006279/140446036-fcc8e5cc-2d5a-41b6-9f11-69f72bbc09db.png)

I think the filter view updates should be dynamic. Am I wrong?

Thanks
Daniele

**Comment by firedm** [comment]
> I think the filter view updates should be dynamic. Am I wrong?

it is implemented as a one run command, 
and yes it should be dynamic, there is a room for improvement

**Comment by jdaniele71** [comment]
Thanks a lot!
Daniele
