### ISSUE TITLE
Wrong video resolution downloaded

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#335]
Hi, 

After I selected many videos from the playlist window and checked they all have the 480 resolution set, i clicked on the download button.
Once downloaded, most of the videos were at 1080 resolution.

Here below one of them:

![image](https://user-images.githubusercontent.com/69006279/140457651-2127981a-300e-4549-9dab-51f45162f0c6.png)

As you can see, the item property from FireDM are correct, instead the downloaded video has the wrong resolution.
What's happening?

Thanks
Daniele

**Comment by firedm** [comment]
i can see the size is correct also
can you post the url for this playlist or this video for testing

**Comment by jdaniele71** [comment]
> i can see the size is correct also can you post the url for this playlist or this video for testing

Sure @firedm , you already have it: [https://www.youtube.com/c/masterwongsystem/videos](url)

Thanks
Daniele

**Comment by Aboghazala** [comment]
Investigation on this issue:

test video url: https://www.youtube.com/watch?v=6_1Sbd-3_kU

video shows 720p webm and 480p as highest mp4 quality

![image](https://user-images.githubusercontent.com/37757246/147129515-2ff5432e-4398-4b7e-9e70-b1790f819e6a.png)

after downloading, vlc shows its real quality as 608x1080 "not sure if this is considered 1080p?" 
![image](https://user-images.githubusercontent.com/37757246/147130237-70a06caa-0289-435a-b86a-56a9d7047f27.png)


after digging, found youtube-dl gives these output:
![image](https://user-images.githubusercontent.com/37757246/147151205-f1393692-22c0-40a2-b484-2fbafcee8023.png)

also, these metadata passed by youyube-dl to FireDM
 ```
             'container': 'mp4_dash',
              'ext': 'mp4',
              'filesize': 2424234,
              'format': '137 - 608x1080 (480p)',
              'format_id': '137',
              'format_note': '480p',
              'fps': 30,
              'height': 1080,
              'quality': 7,
              'resolution': '608x1080',
              'tbr': 1293.011,
              'vbr': 1293.011,
              'vcodec': 'avc1.64001f',
              'video_ext': 'mp4',
              'width': 608
```

FireDM uses format_note property to calculate resolution,
however height property is the right value, it is confusing sometimes, e.g. a 360p video could be 640x352 pixels

opening this video in a browser, found youtube player didn't show 1080, which isolate the source of this issue to youtube itself
![image](https://user-images.githubusercontent.com/37757246/147148501-d0a8e1e8-5dea-46c5-9a81-ae83d0bf36df.png)

from [wikipedia](https://en.wikipedia.org/wiki/1080p):

> 1080p typically refers to a 1920×1080 raster with a 16:9 picture aspect ratio. 

but our video has 608x1080, maybe this what cause this confusion
also regarding other resolutions:
360x640 ====> 360p 
406x720 ====> 360p
 i think both should be 720p

in most videos the height is the smaller value, i believe youtube take the lowest number in video dimension  (mistakenly thinking this is the height) and gets the closest preset value, e.g. 360p, 480p, 720p, etc...
but in social media videos which mostly made by mobile phone cameras will have width smaller than height

will add a preset values to correct this issue based on height property

**Comment by jdaniele71** [comment]
Thanks a lot!
