### ISSUE TITLE
Paste & Clear buttons for link bar

### ISSUE THREAD

**Issue by smaragdus** [firedm/FireDM#341]
Since I don't use `Monitor clipboard for copied urls` option (as it is intrusive for my usage) I have to frequently interact with the link bar. I think that 2 additional buttons:

- **Paste** button - it pastes link to link bar;
- **Clear** button - it clears link from link bar;

would be useful making paste and clear operations easier and faster. These two **Paste** and **Clear** buttons may be placed between the link bar and the **Retry** button, screen:

![FireDM 2021 11 04 - 2021-11-06 - clear - paste - 002](https://user-images.githubusercontent.com/9025757/140593833-9e2aca33-105d-4522-a99d-5ac73f0b525a.png)

So:

- **Paste** button would be a substitute for Click + Paste command or Click + CTRL+V
- **Clear** button would be a substitute for Click + CTRL+A + Backspace or Click + CTRL+A + Delete **(1)**

which means that the user would need a few clicks less to paste in the link bar or to clear the link bar.

**(1)** In this case CTRL+A = triple click

**Comment by firedm** [comment]
No problem, i think it will make working with links faster

**Comment by smaragdus** [comment]
@firedm 

Thank you for the great implementation of **Paste** and **Clear** buttons in version [2021.11.18](https://github.com/firedm/FireDM/releases/tag/2021.11.18):

![FireDM 2021 11 18 - 2021-11-20 - paste - clear - 002](https://user-images.githubusercontent.com/9025757/142705411-5fced643-ecdc-4697-9b88-6454bcb0fdc6.png)

Excellent work as usual, thanks! This may be a small feature but for me it is extremely useful and with time its value will accumulate as much time will be saved skipping the need to use right-click commands.

**Thanks!**
