### ISSUE TITLE
Taking too long getting headers on Crunchyroll links

### ISSUE THREAD

**Issue by nero-0** [firedm/FireDM#345]
The title is self-explanatory.
No problems when trying directly from the command line... tested on both youtube-dl and yt-dlp.
To reproduce just type or paste any Crunchyroll link into the FireDM address bar and watch the logs.

**Comment by firedm** [comment]
couldn't reproduce the problem

**Comment by nero-0** [comment]
But it exists
FireDM:
![b8V3LoljvN](https://user-images.githubusercontent.com/42862510/142480794-797505c2-c24c-4ec0-b8dc-cac5f40714c9.gif)

cmd:
![yUVR5JYD73](https://user-images.githubusercontent.com/42862510/142480856-516c0204-e074-4042-ab94-5efa79efe820.gif)

**Comment by firedm** [comment]
for the link you tested https://www.crunchyroll.com/platinum-end/episode-1-gift-from-an-angel-819757
i can play in web-browser 
on other hand i am getting the recaptcha response with no results through thru cmd line neither by youtube-dl nor yt-dlp
also FireDM is getting nothing
i think we are getting back to square one  with "captcha-bypass" challenge

**Comment by nero-0** [comment]
That link was just a sample, this has been happening with any of them
I don't know what is going on, FireDM can catch the stream options available to download, but it takes a long time (at least on my side)

Here's an example
![w4oI1GRynO](https://user-images.githubusercontent.com/42862510/142499924-cac063c9-9d3a-4002-a1a9-eceb172df615.gif)

**Comment by firedm** [comment]
@nero-0 
can you try with new FireDM version 
also change video extractor in FireDM's settings and see if it make a difference

**Comment by nero-0** [comment]
I just tried with the latest version and it still happens, with both extractors

On the other hand, after some tests, I could notice that this behavior starts in version 2021.11.4 (current version at the time I opened this issue). In the version before that (2021.9.28) everything works fine

In this example I downloaded version 2021.9.28, and updated to 2021.11.18
![2021.11.4](https://user-images.githubusercontent.com/42862510/142581099-f004f2e1-a744-4a13-8f82-84c08bdc3acf.gif)

Then I restored the previous version through FireDM itself
![2021.9.28](https://user-images.githubusercontent.com/42862510/142581566-0f4c1a8a-7889-4eaa-bab3-6c4ba8b96aa1.gif)

As you can see, everything is fine in version 2021.9.28, but something has changed from 2021.11.4 onwards

**Comment by firedm** [comment]
@nero-0 
you did a great job tracking this problem

i found what have been changed that affect hls videos


you can test by downloading this [video.zip](https://github.com/firedm/FireDM/files/7571895/video.zip) file, extract it, then copy the extracted file "video.py" to firedm's library folder

guessing you are running exe version on windows, firedm's library folder is `FireDM\lib\firedm`


and let me know the test results

**Comment by firedm** [comment]
to explain more, i think this is the problem line

https://github.com/firedm/FireDM/blob/ba3ce01017eb3e2622f35f9ec78b725ba43f2f5c/firedm/video.py#L490

we should delete `or self.size == 0` part and change this line to:
`if not isinstance(self.size, int) : `

**Comment by nero-0** [comment]
Thanks for the quick reply
It's working fine now :smile:
The only difference seems to be visual. All streams appear with a size of 0 B, but download is done correctly

**Comment by firedm** [comment]
@nero-0 
great it works for you, will add this fix to coming version
