### ISSUE TITLE
Feature to download torrents files

### ISSUE THREAD

**Issue by fidele000** [firedm/FireDM#346]
add feature to download torrents files in @firedm

**Comment by firedm** [comment]
@fidele000 
this a duplicate
please read comments in issue #196

**Comment by fidele000** [comment]
thank you @firedm

**Comment by WolfgangDpunkt** [comment]
Please at most as an optional feature!
The non-disable torrent function is a reason for many users not to use aria2. Since torrent usage almost inevitably leads to legal problems in many countries.
