### ISSUE TITLE
Add these amazing plugin TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#347]
Hello, it will be amazing if FireDM adds these plugins of TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection to further improve downloading video !

https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection

**Comment by firedm** [comment]
@trimechee 
Thanks for suggestion
the project you mention is a collection of bash scripts to run yt-dlp in terminal with a preset options
in other hand, FireDM uses yt-dlp directly as a video metadata extractor and download video files with libcurl
so, both projects are different in strategy and can't be integrated

**Comment by trimechee** [comment]
Thank you for these informations :)
