### ISSUE TITLE
Add a "paste from clipboard" button to manually add links

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#349]
Hello, I go to a youutbe channel full of videos and I choose the videos I like to download, I copy the link of the video and FireDM will automatically detect it and start to analyze and fetch the link but it takes a while so I go to a another video and I copy a new link and FireDM detects this second link and analyzes it and therefore my first link is lost ....
I know that we can disable the automatic detection of links from the clipboard but it is tiring to paste the links by clicking on the Ctrl + V keys, so it will be great and faster and more comfortable to add a "paste from clipboard" button to quickly add different youtube video links, thank you!

**Comment by Aman9das** [comment]
@firedm Solved by creating a browser extension. Shouldn't create another option.

https://ometer.com/preferences.html

**Comment by trimechee** [comment]
I don't understand lol, it seems complicated :(

**Comment by firedm** [comment]
> Hello, I go to a youutbe channel full of videos and I choose the videos I like to download, I copy the link of the video and FireDM will automatically detect it and start to analyze and fetch the link but it takes a while so I go to a another video and I copy a new link and FireDM detects this second link and analyzes it and therefore my first link is lost ....

@trimechee 
did you try batch download window, it will grab all your copied links and when you done you  can download them all
it can be opened by clicking on "BAT" button (but make sure clipboard monitoring is enabled first from settings)

![image](https://user-images.githubusercontent.com/58998813/141656586-ca474252-8b22-4f02-a71a-8bf9f7f1184a.png)

![image](https://user-images.githubusercontent.com/58998813/141656629-9b44450c-1ded-4509-aa2b-f189582a0f60.png)

**Comment by trimechee** [comment]
Ohh really I am very sorry, excuse me, i didn't see your comment, I just discovered your commment by seeing the changelog....thank you veru much for your advise :)

**Comment by firedm** [comment]
No problem, also paste button added in new version

**Comment by trimechee** [comment]
Wonderful !! Thank you very much :)
