### ISSUE TITLE
list of streams does not disappear when I click on a stream and the stream download starts

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#350]
Hello, when I put a youtube link, FireDM offers me several streams and video links of different qualities and audio, I choose a stream to download it and the download starts but the list of streams and the links do not disappear from "Home" , which can cause some confusion because I download several successive videos and I doubt if I downloaded this or that video and if the downloads have started ...... so it will be great if the list of streams automatically dips from " Home "when we click on a stream and the download starts in order to avoid confusion because I sometimes download the same stream twice, thank you :)

**Comment by firedm** [comment]
@trimechee 
no problem, will add an option in settings

**Comment by trimechee** [comment]
Great ! Thank you very much :)

**Comment by firedm** [comment]
added a fix to prevent re-downloading the same video again
will not add an option to clear main tab on pressing download since it will make things more complicated

**Comment by trimechee** [comment]
Yess, this is very useful and essentiel, I see a button to clear previous donwload, thank you vey much :)
