### ISSUE TITLE
Every video I download stops at 99%

### ISSUE THREAD

**Issue by formlessdao** [firedm/FireDM#352]
Can you guys help troubleshoot what might be wrong please?

**Comment by trimechee** [comment]
Me too, when i download audio stream from facebook video, the download pregress freeze at 99%

**Comment by firedm** [comment]
@formlessdao 
@trimechee 
is this happening all the time?
what the output of log tab?

**Comment by jdaniele71** [comment]
Maybe related to #315

**Comment by formlessdao** [comment]
> 
> 
> @formlessdao @trimechee is this happening all the time? what the output of log tab?

>> Seg 0 start, size: 7.25 MB - range: [0, 7603354]  - worker 7
>> Seg 1 start, size: 14.5 MB - range: [7603355, 22810065]  - worker 6
>> downloaded segment:  0 [0, 7603354] 7.25 MB - worker 7
>> Seg 2 start, size: 21.75 MB - range: [22810066, 45620131]  - worker 5
>> Seg 3 start, size: 29 MB - range: [45620132, 76033553]  - worker 3
>> Seg 4 start, size: 72.51 MB - range: [76033554, 152067111]  - worker 0
>> Seg 0_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  0_audio None 632 B - worker 1
>> Seg 1_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  1_audio None 158.15 KB - worker 2
>> Seg 2_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  2_audio None 157.94 KB - worker 4
>> Seg 3_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  3_audio None 157.75 KB - worker 7
>> Seg 4_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  4_audio None 157.9 KB - worker 1
>> Seg 5_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  5_audio None 157.54 KB - worker 2
>> Seg 6_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  6_audio None 158.07 KB - worker 4
>> Seg 7_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  7_audio None 157.73 KB - worker 7
>> Seg 8_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  8_audio None 157.7 KB - worker 1
>> Seg 9_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  9_audio None 157.66 KB - worker 2
>> Seg 10_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  10_audio None 157.77 KB - worker 4
>> Seg 11_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  11_audio None 157.88 KB - worker 7
>> Seg 12_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  12_audio None 157.8 KB - worker 1
>> Seg 13_audio start, size: 0 B - range: None  - worker 2
>> Seg 14_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  14_audio None 157.69 KB - worker 4
>> downloaded segment:  13_audio None 157.84 KB - worker 2
>> Seg 15_audio start, size: 0 B - range: None  - worker 7
>> Seg 16_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  15_audio None 157.9 KB - worker 7
>> downloaded segment:  16_audio None 157.9 KB - worker 1
>> Seg 17_audio start, size: 0 B - range: None  - worker 2
>> Seg 18_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  17_audio None 157.55 KB - worker 2
>> downloaded segment:  18_audio None 158.04 KB - worker 4
>> Seg 19_audio start, size: 0 B - range: None  - worker 7
>> Seg 20_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  20_audio None 157.97 KB - worker 1
>> Seg 21_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  21_audio None 157.57 KB - worker 2
>> Seg 22_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  19_audio None 157.55 KB - worker 7
>> downloaded segment:  22_audio None 157.99 KB - worker 4
>> Seg 23_audio start, size: 0 B - range: None  - worker 7
>> Seg 24_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  24_audio None 157.77 KB - worker 1
>> downloaded segment:  23_audio None 157.63 KB - worker 7
>> Seg 25_audio start, size: 0 B - range: None  - worker 2
>> Seg 26_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  25_audio None 157.79 KB - worker 2
>> Seg 27_audio start, size: 0 B - range: None  - worker 7
>> Seg 28_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  26_audio None 157.93 KB - worker 4
>> downloaded segment:  28_audio None 157.86 KB - worker 1
>> downloaded segment:  27_audio None 157.6 KB - worker 7
>> Seg 29_audio start, size: 0 B - range: None  - worker 2
>> Seg 30_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  29_audio None 157.85 KB - worker 2
>> Seg 31_audio start, size: 0 B - range: None  - worker 7
>> Seg 32_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  32_audio None 157.76 KB - worker 1
>> Seg 33_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  30_audio None 157.69 KB - worker 4
>> downloaded segment:  31_audio None 157.85 KB - worker 7
>> Seg 34_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  33_audio None 157.87 KB - worker 2
>> Seg 35_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  34_audio None 157.88 KB - worker 4
>> Seg 36_audio start, size: 0 B - range: None  - worker 1
>> Seg 37_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  36_audio None 157.85 KB - worker 1
>> Seg 38_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  37_audio None 157.76 KB - worker 2
>> downloaded segment:  35_audio None 157.57 KB - worker 7
>> Seg 39_audio start, size: 0 B - range: None  - worker 1
>> Seg 40_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  38_audio None 157.77 KB - worker 4
>> Seg 41_audio start, size: 0 B - range: None  - worker 4
>> Seg 42_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  40_audio None 157.84 KB - worker 2
>> downloaded segment:  41_audio None 157.91 KB - worker 4
>> downloaded segment:  42_audio None 157.57 KB - worker 7
>> downloaded segment:  39_audio None 157.83 KB - worker 1
>> Seg 43_audio start, size: 0 B - range: None  - worker 2
>> Seg 44_audio start, size: 0 B - range: None  - worker 4
>> Seg 45_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  44_audio None 157.72 KB - worker 4
>> Seg 46_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  45_audio None 157.91 KB - worker 7
>> Seg 47_audio start, size: 0 B - range: None  - worker 4
>> Seg 48_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  48_audio None 157.87 KB - worker 7
>> Seg 49_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  46_audio None 157.71 KB - worker 1
>> downloaded segment:  43_audio None 157.88 KB - worker 2
>> Seg 50_audio start, size: 0 B - range: None  - worker 1
>> Seg 51_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  50_audio None 157.74 KB - worker 1
>> downloaded segment:  47_audio None 157.7 KB - worker 4
>> Seg 52_audio start, size: 0 B - range: None  - worker 1
>> Seg 53_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  49_audio None 157.8 KB - worker 7
>> Seg 54_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  51_audio None 157.8 KB - worker 2
>> Seg 55_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  53_audio None 157.67 KB - worker 4
>> downloaded segment:  54_audio None 157.84 KB - worker 7
>> downloaded segment:  52_audio None 157.9 KB - worker 1
>> downloaded segment:  55_audio None 157.84 KB - worker 2
>> Seg 56_audio start, size: 0 B - range: None  - worker 4
>> Seg 57_audio start, size: 0 B - range: None  - worker 7
>> Seg 58_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  57_audio None 157.55 KB - worker 7
>> Seg 59_audio start, size: 0 B - range: None  - worker 2
>> Seg 60_audio start, size: 0 B - range: None  - worker 7
>> downloaded segment:  59_audio None 157.7 KB - worker 2
>> Seg 61_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  61_audio None 157.79 KB - worker 2
>> Seg 62_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  62_audio None 157.8 KB - worker 2
>> Seg 63_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  56_audio None 157.96 KB - worker 4
>> downloaded segment:  58_audio None 157.84 KB - worker 1
>> Seg 64_audio start, size: 0 B - range: None  - worker 4
>> Seg 65_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  60_audio None 157.79 KB - worker 7
>> downloaded segment:  64_audio None 157.71 KB - worker 4
>> Seg 66_audio start, size: 0 B - range: None  - worker 7
>> Seg 67_audio start, size: 0 B - range: None  - worker 4
>> downloaded segment:  63_audio None 157.89 KB - worker 2
>> Seg 68_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  66_audio None 157.7 KB - worker 7
>> downloaded segment:  65_audio None 157.87 KB - worker 1
>> downloaded segment:  68_audio None 157.66 KB - worker 2
>> downloaded segment:  67_audio None 157.92 KB - worker 4
>> Seg 69_audio start, size: 0 B - range: None  - worker 7
>> Seg 70_audio start, size: 0 B - range: None  - worker 1
>> downloaded segment:  69_audio None 157.84 KB - worker 7
>> Seg 71_audio start, size: 0 B - range: None  - worker 2
>> downloaded segment:  70_audio None 157.81 KB - worker 1
>> Seg 72_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 4
>> Seg 73_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 7
>> downloaded segment:  72_audio None 157.66 KB - worker 4
>> Seg 74_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 1
>> Seg 75_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  71_audio None 157.92 KB - worker 2
>> Seg 76_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  74_audio None 157.8 KB - worker 1
>> Seg 77_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  73_audio None 157.73 KB - worker 7
>> Seg 78_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 7
>> downloaded segment:  75_audio None 157.95 KB - worker 4
>> Seg 79_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  76_audio None 157.69 KB - worker 2
>> Seg 80_audio start, size: 0 B - range: None- minimum speed= 20480, timeout=10  - worker 2
>> downloaded segment:  77_audio None 157.87 KB - worker 1
>> Seg 86 start, size: 7.75 MB - range: [37490019, 45620131]- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  78_audio None 157.79 KB - worker 7
>> downloaded segment:  79_audio None 157.83 KB - worker 4
>> downloaded segment:  80_audio None 121.72 KB - worker 2
>> downloaded segment:  86 [37490019, 45620131] 7.75 MB - worker 1
>> Seg 87 start, size: 33.51 MB - range: [116927709, 152067111]- minimum speed= 20480, timeout=10  - worker 2
>> Seg 88 start, size: 11.26 MB - range: [64230978, 76033553]- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  88 [64230978, 76033553] 11.26 MB - worker 4
>> Seg 89 start, size: 15.76 MB - range: [100406575, 116927708]- minimum speed= 20480, timeout=10  - worker 7
>> Seg 90 start, size: 13.51 MB - range: [137899069, 152067111]- minimum speed= 20480, timeout=10  - worker 1
>> Seg 91 start, size: 7.88 MB - range: [92146008, 100406574]- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  91 [92146008, 100406574] 7.88 MB - worker 4
>> Seg 92 start, size: 6.76 MB - range: [130815047, 137899068]- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  92 [130815047, 137899068] 6.76 MB - worker 4
>> Seg 93 start, size: 3.63 MB - range: [60426826, 64230977]- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  93 [60426826, 64230977] 3.63 MB - worker 4
>> Seg 94 start, size: 3.76 MB - range: [112989391, 116927708]- minimum speed= 20480, timeout=10  - worker 4
>> downloaded segment:  94 [112989391, 116927708] 3.76 MB - worker 4
>> downloaded segment:  1 [7603355, 22810065] 14.5 MB - worker 6
>> downloaded segment:  2 [22810066, 37490018] 14 MB - worker 5
>> downloaded segment:  3 [45620132, 60426825] 14.12 MB - worker 3
>> downloaded segment:  89 [100406575, 112989390] 12 MB - worker 7
>> downloaded segment:  4 [76033554, 92146007] 15.37 MB - worker 0
>> downloaded segment:  87 [116927709, 130815046] 13.24 MB - worker 2
>> downloaded segment:  90 [137899069, 152067111] 13.51 MB - worker 1
>> thread_manager uid_ece9ae4217f26f8d99ff0ae03942acdf: quitting

**Comment by firedm** [comment]
@formlessdao 
thanks for reporting
this bug already fixed and will be available in coming release (soon)

**Comment by trimechee** [comment]
@firedm It happens from time to time, sometimes i can download totally sometimes it gets stuck at 99%, i will try to find a download which fails and post log tab in sha Allah

**Comment by formlessdao** [comment]
> 
> 
> @formlessdao thanks for reporting this bug already fixed and will be available in coming release (soon)

Yeah, it's pretty important to me so of course I'm going to report such a serious bug. When do you plan to release it?. It's a pretty serious bug that right now forces me to use other apps to download stuff.

**Comment by firedm** [comment]
> When do you plan to release it?.

i believe it will be within a week (more or less)

**Comment by firedm** [comment]
@formlessdao 
please check if this problem fixed in the new version

**Comment by trimechee** [comment]
I checked and idownload lots of youtube videos and didn't see this problem, i would try with facebook in sha Allah videos to make sure the bug is gone .....
in any case I have the impression that FireDM has become much faster and as swift as a rocket !! 
as a precaution, I deleted the old version and I installed clean the new version, before I waited for FireDM to analyze the links but with this new version, the analysis ends in the blink of an eye !!! Thank you very much for all your efforts to make this amazing software :)

**Comment by formlessdao** [comment]
> 
> 
> @formlessdao please check if this problem fixed in the new version

Yes now it actually finishes downloading BUT now thumbnails are broken and do not show anymore.

Also on Linux  I can not save files on a partition that is formatted as NTFS but I can transfer just fine files from EXT4 to NTFS with the default file manager.

**Comment by firedm** [comment]
> I checked and idownload lots of youtube videos and didn't see this problem, i would try with facebook in sha Allah videos to make sure the bug is gone ..... in any case I have the impression that FireDM has become much faster and as swift as a rocket !! as a precaution, I deleted the old version and I installed clean the new version, before I waited for FireDM to analyze the links but with this new version, the analysis ends in the blink of an eye !!! Thank you very much for all your efforts to make this amazing software :)

THANKS @trimechee

**Comment by firedm** [comment]
@formlessdao 

> Yes now it actually finishes downloading BUT now thumbnails are broken and do not show anymore for downloaded files.

new version has no "bulk view" it has a 'mix and compact" only
in mix view only active items "currently downloading" show thumbnails
you can use preview button in downloads tab to show preview box at the bottom for any selected item

> Also on Linux I can not save files on a partition that is formatted as NTFS but I can transfer just fine files from EXT4 to NTFS with the default file manager.

not sure what is the problem, since i have linux and download files to ntfs partitions 
i think you are dual booting linux and windows and you forgot to shift shutdown windows

**Comment by formlessdao** [comment]
I have Fast startup disabled. 

> 
> 
> @formlessdao
> 
> > Yes now it actually finishes downloading BUT now thumbnails are broken and do not show anymore for downloaded files.
> 
> new version has no "bulk view" it has a 'mix and compact" only in mix view only active items "currently downloading" show thumbnails you can use preview button in downloads tab to show preview box at the bottom for any selected item
> 
> > Also on Linux I can not save files on a partition that is formatted as NTFS but I can transfer just fine files from EXT4 to NTFS with the default file manager.
> 
> not sure what is the problem, since i have linux and download files to ntfs partitions i think you are dual booting linux and windows and you forgot to shift shutdown windows

I have Fast Startup disabled/unchecked.

**Comment by firedm** [comment]
> I have Fast Startup disabled/unchecked so I'm sure there's something else. What can i do to help you find out what's wrong?

see what errors you are getting in log tab while saving on NTFS folder
use a download path that doesn't have spaces or non-Ascii letters in folders' names



> How can i get back thumbnails for all videos? Going one by one and only then seeing a thumbnail is a big UX regression.
> If i have many downloaded videos it's much harder to visually hone down on what I'm actually looking without all thumbnails being visible.

the only reason this has been disabled is because the low performance of GUI in presence of too much download items with thumbnails displayed

will reconsider put this option back and let users decide what is best for them

**Comment by trimechee** [comment]
I think it's most important to have even faster and smoother performance and it's a good idea to turn off thumbnails ! and even if there is come back of thumbnails, we hope that there will be an option to disable them, thank you :)

**Comment by firedm** [comment]
> I think it's most important to have even faster and smoother performance and it's a good idea to turn off thumbnails ! and even if there is come back of thumbnails, we hope that there will be an option to disable them, thank you :)

@trimechee
sure it will be an option in view button in downloads tab, 
the default  is "mix" view but user can switch to bulk view "with thumbnail" if he want to

**Comment by trimechee** [comment]
Ohh that's great ! Thank you very much :)
