### ISSUE TITLE
Please add the ability to download from this wonderful amazing marvelous crazy site that removes noises !

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#357]
Please, I found this exceptional site which offers various specific free sounds which allow to delete the noises in the backgroud so we can better concentrate in our studies, work, and sleep better in sha Allah ....
the sounds are free but to download, we have to make a donation and I would like to listen to this sound offline in sha Allah, I tried with FireDM but got lots of error messages, I also downloaded with Video DownloadHelper with companion app installed but i can download only 30 seconds or 25 seconds of this sound .....
I would very much like to download this specific sound because it has many virtues and benefits and I would be grateful if you can find a solution to download this useful beautiful sound necessary for our well-being, thank you very much !

https://mynoise.net/NoiseMachines/whiteRainNoiseGenerator.php?l=14222840464228211305&m=&d=0

This why I hope very much to download this rare sound : 

White Noise + Rain = White Rain Noise ?
For the engineer, white noise is a signal that contains all frequencies in equal proportion, or, in other words, a signal whose spectrum is flat. For the mathematician, white noise is a signal made of uncorrelated samples, exactly like numbers output by a random number generator. Assuming that both engineers and mathematicians are right, we conclude that, when a source behaves like a random process, its sound should resemble white noise.

This is exactly what happens with rain. Every drop can be considered as an independent, uncorrelated, sound source. A gentle rain, made of sparse drops, will generate a pitter-patter sound, where you will still be able to hear each drop's distinctive sound. By increasing the rate and the number of drops, a heavier rain starts behaving as a huge random process, and its sound turns white.

Our white rain sound recording is totally natural: no synthetic white noise has been superimposed here. Yet, it sounds close to white noise. Not all rain sounds are white though, mostly because of the environment in which the rain falls alters the color of the sound too. Our recording has been performed in the silence of the night, in a huge space - namely the Harau Valley in Sumatra - and in the absence of any wind, as to produce the most even noise one can get.

This sound offers the exact same spectrum as white noise, and can be used in the same applications in the mind, such as noise blocking or tinnitus relief. If white noise ever sounded too synthetic for your ears, give our white rain noise a try.

Calibrated Output
This sound generator is calibrated and outputs a pink-like spectrum when the sliders are horizontally aligned. Calibration is unique to this website, and can be used to compensate for your own hearing, audio equipment, and listening environment deficiencies: follow our Calibration Procedure once, then access Your Hearing Curve from the right column.

**Comment by firedm** [comment]
@trimechee 
this is truly a wonderful website.

after inspecting the link you supplied, found only one free demo available for download with 16 seconds duration, in 2 formats:
[demo.mp3](https://myNoise.net/Data/RAIN2/demo.mp3  )
[demo.ogg](https://myNoise.net/Data/RAIN2/demo.ogg)

the website doesn't offer any other free streams, unless you login and have enough credit, it will make other streams available

**Comment by trimechee** [comment]
Ohh that's great ! thank you vey much for your precious help !!

I discover that this site has a youtube channel and so I can download other sounds for free so that attenuates my disappointment lol, my last chance is either to pay or to try to contact Mr Xavi Esteve, I discovered this site while reading his article gathering the very best web apps :
https://xaviesteve.com/6812/web-based-tools/?unapproved=407897&moderation-hash=24aa338896dec29f3d6bff84ba286439#comment-407897

and he himself who calibrated this sound which I am trying to download, I would try to contact him in sha Allah and ask him to send me this audio ... otherwise I think I will connect to internet or use the android app to listen to this sound when I need it .... 
thank you very much for your great help :)

**Comment by trimechee** [comment]
Ouahh I have just made this great sensational discovery : I can listen  sounds while being offline by using their app ! 

https://play.google.com/store/apps/details?id=com.mynoise.mynoise&hl=en

here is what the website says : 

Our website has an App - not the opposite. If you have not heard about myNoise yet, please try the original website. If you like our noise generators, and want to use them on the go without worrying about connectivity, the App is definitely what you need! It comes with our most successful noise machines... for free!

The Noises, without the Internet
The app keeps all features for which myNoise is renowned: the same generators, same uncompromised sound quality, same level of customization; only without the need of being connected to the Internet! The app packs all our noise generators in your pocket, and makes them available to you without worrying about connectivity, while you are on the go, or in places where computers are not always available or desired, such as your bedroom.

The Bonuses
The App comes with some neat bonuses, such as an alarm, a timer, several animation modes, and it even streams audio wirelessly! It also offers the ability to name and store your own presets. The App has been written from scratch, and uses native code: it is not just the website embedded in a window. Sliders will be easier to operate and more responsive too.

The Apps v/s the Website
The website offers you a way to access all sound generators, for free, and is open to donations.

Our Apps - iOS and Android - are free, ad-free, and bundled with five of myNoise's best and most successful noises. This in itself offers much value already: many other apps on the store are making profit out of these exact same sounds, and have no calibration yet to offer. All the other noise generators are available either as individual IAPs (In App Purchases), USD 0.99 each, or as a lifetime access to the full catalog, present and future, for USD 9,99 only!

With the five bundled noises, we offer you a high-quality sonic Swiss-army knife, holding in your pocket; a tool that will help you in a variety of daily circumstances. White noise has been scientifically proven to help blocking noises and mask tinnitus. Rain noise works great as a noise blocker too, and is often used in anxiety management and during meditation. Binaural beats are often used in the context of personal growth, mind change and sound therapy. And then, we added Temple Bells and Spring Walk for free as well. To thank Android users for their patience, we added Warp Speed as a free build-in sound too, only on Android! Plus, if you open the download tab of our apps, you will find a couple of complimentary generators there too, depending on our mood.

Please note that the website donations and the App purchases are not linked. Donating to this website will not unlock all the downloads on the app, or purchasing additional generators from any of our Apps will not grant you a privileged access to the website. Every platform should be considered as independent. Likewise, purchasing the bundle on one mobile platform will not unlock another. This is why we keep prices low. All your purchases should be considered as independent ways to serve the same purpose: leverage funds to keep the project alive and recording new generators.

The idea behind a noise machine, is to make use of the noises you like to mask the noises you dislike. The concept is simple, works extremely well, and does not require expensive equipment, such as active noise cancelling headphones.

Background noises can be used in a variety of ways throughout your daily lives, and by all audiences. They can not only help you focus while working in a noisy environment, or help to settle your anxiety, but they are also useful in cases of insomnia or tinnitus. Fortunately, you don't need a specific reason to start listening to our noise generators! These are all sonic marvels that you will simply enjoy listening to; candy for your ears!

myNoise is free, with White Noise, Rain Noise, Binaural Beats, Spring Walk, Temple Bells and Warp Speed, the white noise machine for Sci-Fi fans!

**Comment by trimechee** [comment]
Sorry,  just to be sure to well understand, you said "the website doesn't offer any other free streams", that's means there is no free streams to download ?
I just checked this website, yes i don't see download option, but luckily there are plenty of free streams to listen like streams to :  need to focus in a noisy environment, I want to sleep, I need to calm down, I am a student with ADHD, I work in an open space office, I suffer from tinnitus, I am looking for sounds during my meditation, I'm a writer in need of inspiration....

https://mynoise.net/

**Comment by firedm** [comment]
@trimechee 
the available free streams are short demos with few seconds duration
you can download them using the link pattern like below:
`https://myNoise.net/Data/xxxxxxx/demo.mp3`

you can replace xxxxxxx with words from this [page](https://mynoise.net/) to get different demos, e.g
https://myNoise.net/Data/beach/demo.mp3
https://myNoise.net/Data/THUNDER/demo.mp3
https://myNoise.net/Data/forest/demo.mp3
and so on ....

**Comment by trimechee** [comment]
Amazing !!! Thank you very much fot your great kindness and generosity :)

**Comment by trimechee** [comment]
I just tried, I clicked on your links and tried to follow the procedure you recommended to me but it does not work, but there is no problem, you have already helped me a lot and I was able to download the sound I was looking for thank you very much :) 

just for information, i have this message when i click on the links  : 
" Ooops... You just hit a page that doesn't exist, or doesn't exist anymore. You can try knocking at the door, but I am afraid no one is there to answer you. Please proceed to the front desk.

404 Error - This page cannot be found"
