### ISSUE TITLE
Afraid that my IP address will be banned by youtube

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#358]
I made the most best playlist in the world gathering the most beautiful sublime recitiosn of the noble quran alhamdoulilAllah

https://www.youtube.com/playlist?list=PLCVfum9m6K6OkOnoRAzHnz5puRE4zVjWF

 I would like may be in the future in sha Allah to use firedm to try to archive these recitations or some recitations and save them because sometimes recitations are deleted from youtube, I put a lot nice recitations in my playlist and i'm afraid if i download them successively using FireDM, youtube will block my IP address and maybe delete my google or youtube account ......                  
 is there a risk if, for a long time i download successively audio from a lot of youtube videos using Firedm, is there a risk that youtube will block Firedm and ban me ?

**Comment by firedm** [comment]
@trimechee 

> I made the most best playlist in the world gathering the most beautiful sublime recitiosn of the noble quran alhamdoulilAllah

**ما شاء الله**

if you are nice to theses website it won't be a problem
for example:
in FireDM set "concurrent downloads = 1"  to download only one video at a time, and you can download as much as you like it won't be a problem
another thing, do you have a fixed ip, or you get a new ip each time your router connect to internet?

**Comment by trimechee** [comment]
Thank you very much :)

بارك الله فيك

Sorry, i don' know if I have fixed IP, so how do we know ? what I know, for my network settings, I just changed dns setting of windows 10  to dns cloudflare malware block family and also to the dns of  adguard to block ads.....

I use Wi-Fi if I have to donwload, I think if I download in sha Allah, I would try to start with limited numbers of downloads to avoid to saturate my connection.....

**Comment by firedm** [comment]
> Sorry, i don' know if I have fixed IP, so how do we know ?

you can visit website like [this](ipinfo.io/ip) or [this](https://ifconfig.me/) to get your public ip
note it down then unplug your router power and after 10 seconds connect again
then wait for your router to connect to internet, then check your public ip again 
if you get different ip address, this means you don't have a fixed ip, and in case you feel you are banned by anywebsite you can restart your router to get new ip address

**Comment by trimechee** [comment]
Great ! Thank you very much for your help !
