### ISSUE TITLE
Mistery 

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#362]
Hello, before I discover FireDM,  I also use this downloade : "3D Youtube Downloader", in the settings of 3D Youtube Downloader, I chose the WORST audio quality and when I use this software to download youtube video, it automatically downloads the audio stream with audio format " opus ", and I like this audio format because small size and good quality and fast to download but when I download the same video using FireDM and I check between the audio streams offered by FireDM, I see the audio format" m4a " offered by FireDM and I don't see  "opus" audio format which I prefer to download, is there any explanation for this mystery and can FireDM download audio streams with "opus" audio format ?

**Comment by firedm** [comment]
the audio streams displayed in FireDM are the ones supplied by the server (e.g. youtube), however you can convert from any format to another but simply you can't get more quality

I believe webm and ogg displayed in audio streams are opus
you may read [this](https://stackoverflow.com/a/67796802/10146012)

**Comment by trimechee** [comment]
I checked and 3D Youtube Downloade does not convert the audio file but I think it changes the name of the extension to "opus" ....
please I put some tv show extracted to audio and play them with my audio player when I sleep and audio players can't play webm files, can FireDM replace automatically webm files with opus files? because the page you sent me said "So, it's not correct to say that there's no audio metadata. You can't play the audio in audio players because they consider it to be a video file, but most video players support playing it. For example, it works with vlc, mpv, totem, Google Chrome and Firefox.

When you add the extract audio parameter, an extra step is done: the webm container is replaced by the Ogg container (and the extension is renamed to .opus). The Opus audio contained in the file stays the same"

**Comment by firedm** [comment]
@trimechee 
no problem we can add .opus option

**Comment by trimechee** [comment]
Amazing ! hank you very much :)
