### ISSUE TITLE
Download directly to smartphone to avoid wasting time

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#365]
It's sometimes complicated to use the smartphone to download the streaming video and using FireDM, it's more comfortable and fast and powerful, so I have a may be weird idea lol :
use FireDM to download the videos directly to our smartphones without downloading them to the computer and then transfer them to the smartphone, so here is my idea :

these two wonderful open source sites snapdrop and sharedrop allow you to transfer files between computer and smartphone without installing any app! 

https://snapdrop.net/

https://www.sharedrop.io/

so maybe FireDM can use the APIs of these open source software and FireDM could detect our smartphones and download video directly to our smartphones just using the WI fi network without  having to donwload first to our computer ?

is this technically possible?

Thank you so much !

**Comment by firedm** [comment]
@trimechee 
sorry, this is not possible

**Comment by trimechee** [comment]
Ok thank you :)
