### ISSUE TITLE
Support FireDM

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#366]
Hello, to express our support for FireDM, FireDM users might accept some non-intrusive ads, so I suggest adding some ads to FireDM to support the development of the project and to thank you, and for the people who don't ads, FireDM could add an option to disable ads, thanks

**Comment by firedm** [comment]
@trimechee 
thanks for caring
however, i don't seek any financial revenue from FireDM

**Comment by trimechee** [comment]
Yes,  it was just a suggestion in case the project is still growing and needs developers or servers .... or maybe allow people to make donation.....any way thanks a lot for all your efforts  to conceive this software and to all contributors :)
