### ISSUE TITLE
SSL verification

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#367]
Hello, the new update of FireDM is so wondereful and awesome !!! Thank you very much !

I have a question please: I noticed this option : "show warning when disabling SSL verifcation", so what does this option mean? Is there a risk if we disable it? does disabling this option affect the speed of downloading ?

**Comment by firedm** [comment]
SSL verifcation is a mechanism to prevent "man in the middle attack", where the hacker could intercept your traffic 

it doesn't have any relation with download speed
some website doesn't have a valid ssl certificate, if you need to download something from these websites you have to disable ssl verification

you can read more [here](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html) or search google for what is ssl certificate

**Comment by trimechee** [comment]
Very useful, thank you for adding unique and important features :)
