### ISSUE TITLE
Download twitch subscribers only stream videos

### ISSUE THREAD

**Issue by moashxer** [firedm/FireDM#368]
Hi thanks a lot for your work,

I use pyidm to download some twitch past videos once the live stream is finished however now some streamers switched to subscribers only and unfortunately without passing cookies to PyIDM I cannot download any of the past stream videos of subscribers only streams.

Solution; 
If there is an additional fields to paste twitch cookies and then to detect and download the past streams or something similar to that.

Thanks 😄

**Comment by firedm** [comment]
@moashxer 
did you try cookies option in settings?

![image](https://user-images.githubusercontent.com/58998813/142667562-e88c8877-4962-4d3b-aa39-b660e7c766ed.png)

**Comment by moashxer** [comment]
I didn't look this, I'll let you know once I've tried.
Thanks :)

**Comment by moashxer** [comment]
this is not working, i pasted the cookies from http request into a text file in `Cookie: jajaja-here` and simply the cookies itself also but seems not working, the percentage bar keeps loading over and over again.

**Comment by moashxer** [comment]
#### update follow this
https://github.com/dandv/convert-chrome-cookies-to-netscape-format
