### ISSUE TITLE
'refreshing the URL' fails?

### ISSUE THREAD

**Issue by altadr** [firedm/FireDM#369]
Hello, 
first of all, thank you for this wonderful tool!

But, I have (using OS Windows10  21h1 32-bit) a Problem resuming, and even starting,  YouTube downloads after a pause of some hours, probably caused by expiring of the 'direct URL'. 
It seems, that 'refreshing the URL' fails.

After copying the 'webpage URL' to the clipboard, removing the item from the download list, pasting the 'webpage URL' in the Link box on the main tab, and clicking 'download', everything works fine, with the then obtained new 'direct URL'. 
Downloading works, resuming works, until this new 'direct URL' also is expired ...  

Not having found anything like this in the issue list, and being a beginner in using these things, 

my question is, what did I wrong, and what's to do to make it work correctly?

Thank you again

Here my settings:
{
    "active_video_extractor": "yt_dlp",
    "auto_rename": false,
    "autoscroll_download_tab": false,
    "check_for_update": true,
    "checksum": false,
    "current_theme": "White-grey-blue",
    "custom_user_agent": null,
    "disable_log_popups": false,
    "ditem_show_top": true,
    "download_folder": "E:\\",
    "download_thumbnail": true,
    "enable_proxy": false,
    "enable_systray": true,
    "gui_font": {
        "family": "Segoe UI",
        "size": 10,
        "weight": "normal",
        "slant": "roman",
        "underline": 0,
        "overstrike": 0
    },
    "ibus_workaround": false,
    "ignore_ssl_cert": true,
    "keep_temp": false,
    "last_update_check": [
        2021,
        11,
        18
    ],
    "log_level": 2,
    "max_concurrent_downloads": 3,
    "remember_web_auth": false,
    "use_web_auth": false,
    "username": "",
    "password": "",
    "max_connections": 10,
    "minimize_to_systray": false,
    "monitor_clipboard": true,
    "on_download_notification": true,
    "proxy": "",
    "recent_folders": [
        "E:\\",
        "C:\\",
        "C:\\Users\\av-2in1-silver.V2021\\Downloads"
    ],
    "refresh_url_retries": 10,
    "scrollbar_width": 21,
    "speed_limit": 0,
    "update_frequency": 7,
    "use_playlist_numbers": true,
    "use_server_timestamp": true,
    "window_size": [
        1273,
        476
    ],
    "write_metadata": true,
    "view_mode": "compact",
    "window_maximized": false,
    "force_window_maximize": false,
    "reverse_playlist": false,
    "d_preview": true,
    "updater_version": "2021.11.18",
    "popup_1": true,
    "popup_2": true,
    "popup_4": true,
    "popup_5": true,
    "popup_6": true,
    "popup_7": true
}

The log file is 
>> -------------------- FireDM --------------------
>> Starting FireDM version: 2021.11.18 Frozen
>> operating system: Os: Windows - Platform: Windows-10-10.0.19041 - Machine: x86
>> Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
>> current working directory: C:\FireDM
>> FFMPEG: C:\FireDM\ffmpeg.exe, version: git-2020-01-24-e931119
>> Tkinter version: 8.6.9
>> AwesomeTkinter version: 2021.11.8
>> Pillow version: 8.2.0
>> PyCUrl version: PycURL/7.43.0.5 libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 c-ares/1.15.0 WinIDN libssh2/1.9.0 nghttp2/1.40.0
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> Gui Loading time: 12.67 seconds 
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: C:\FireDM\ffmpeg.exe, version: git-2020-01-24-e931119
>> download item uid_71561a7dbab74856afeabcea6e9ddeea already in list, check resume availability
>> resume is possible
>> downloads items list saved in: C:\FireDM\downloads.dat
>> --------------------------------------------------
>> start downloading file: "Tutorial Teil 3.4 Steckdose Schalten Aufputz _Schaltbare Steckdose anschließen _ Allpolig Schalten.mp4", size: 391.98 MB, to: E:\
>> url: "https://www.youtube.com/watch?v=ERN_66zd1fU" 

>> load_progress_info()> rebuild segments from previous download for: Tutorial Teil 3.4 Steckdose Schalten Aufputz _Schaltbare Steckdose anschließen _ Allpolig Schalten.mp4
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 3
>> Seg 1 start, size: 36.39 MB - range: [19077518, 57232553]  - worker 4
>> Seg 2 start, size: 54.58 MB - range: [57232554, 114465108]  - worker 5
>> Seg 3 start, size: 72.77 MB - range: [114465109, 190775181]  - worker 9
>> Seg 4 start, size: 181.94 MB - range: [190775182, 381550366]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 0_audio start, size: 1.41 MB - range: [0, 1473467]- minimum speed= 20480, timeout=10  - worker 1
>> Seg 1_audio start, size: 2.81 MB - range: [1473468, 4420403]- minimum speed= 20480, timeout=10  - worker 6
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]- minimum speed= 20480, timeout=10  - worker 8
>> Seg 1 start, size: 36.39 MB - range: [19077518, 57232553]- minimum speed= 20480, timeout=10  - worker 7
>> Seg 2 start, size: 54.58 MB - range: [57232554, 114465108]- minimum speed= 20480, timeout=10  - worker 2
>> Seg 3 start, size: 72.77 MB - range: [114465109, 190775181]- minimum speed= 20480, timeout=10  - worker 3
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 4
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 5
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 9
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 0
>> Seg 1 start, size: 36.39 MB - range: [19077518, 57232553]  - worker 1
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 1
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 1
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 6
>> Seg 1 start, size: 36.39 MB - range: [19077518, 57232553]  - worker 8
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 7
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 2

and so on 

down to 

>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 5
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 9
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 1
>> Seg 0 start, size: 18.19 MB - range: [0, 19077517]  - worker 0
>> thread_manager uid_71561a7dbab74856afeabcea6e9ddeea: quitting
>> File Failed.
>> file_manager uid_71561a7dbab74856afeabcea6e9ddeea: quitting
>> brain uid_71561a7dbab74856afeabcea6e9ddeea: quitting
>> -------------------------------------------------- 

>> auto refresh url for: Tutorial Teil 3.4 Steckdose Schalten Aufputz _Schaltbare Steckdose anschließen _ Allpolig Schalten.mp4
>> creating video playlist
>> [youtube] ERN_66zd1fU: Downloading webpage
>> [youtube] ERN_66zd1fU: Downloading android player API JSON
>> downloading Thumbnail
>> download()> error: 'ObservableDownloadItem' object has no attribute 'selected_stream'

End

**Comment by firedm** [comment]
@altadr 
thanks for reporting this and including all necessary data

i believe this is a bug, will investigate more to find a fix

**Comment by firedm** [comment]
fixed in commit  a5f997e  and will be available in coming release
