### ISSUE TITLE
move select auto number playlist filename from setting

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#370]
move auto number playlist filename from setting
![Capture](https://user-images.githubusercontent.com/36833664/142717763-c9a7d048-ae01-431b-b8d6-1e492278a57c.PNG)
to download playlist
![Capture2](https://user-images.githubusercontent.com/36833664/142717569-cd3f0e7a-605e-4589-9c91-9ef1296b7f1b.PNG)

**Comment by firedm** [comment]
@candrapersada 
thanks for suggestion,
yes, it would be the proper place for such an option

anyhow there is a plan to re-work playlist window
