### ISSUE TITLE
 Download m3u8

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#371]
Hello, may be this open sorce softwate could help to add more options like download m3u8.....
there is the description of this sofware, it has even a GUI : 

"N_m3u8DL-CLI is a command line tool for downloading m3u8. It is .NET Framework 4.6 developed based on the framework and calls the system library for HTTP downloads. It supports common m3u8 format downloads, supports downloading from a part of the video, and also provides a wealth of command line options to Enhance its functions. Simple GUI included.
This version is almost all minor revisions, and new features...... "

**Comment by firedm** [comment]
@trimechee 
FireDM already can download m3u8 videos "called HLS"  

give FireDM a try with m3u8 link and let me know if it works for you

here it is an example m3u8  video file
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by trimechee** [comment]
Ahhh I didn't know that! I just tested and it works perfectly and I can download the playlist and the video and audio streams: thank you very much !

**Comment by firedm** [comment]
you're welcome

**Comment by candrapersada** [comment]
why this m3u8 video can't be downloaded?
https://hive.gdriveplayer.link/OTnDjnoJMZXS3pM5hhPEMxDzQQt7E8YMUMsINKGoqHlY7HgdbUgTaPJ274hXTGxQmbmcfKTTpJXVZB0zBwIiZA/Gv0GRncITvC-ZepBPuVMus4rRlr9Pc-nplnrnfuMuoI/360.m3u8

**Comment by firedm** [comment]
can't open this link in web-browser

![image](https://user-images.githubusercontent.com/58998813/147861483-4b174c54-67ac-4f1b-9a98-3fd4c18fd734.png)

**Comment by candrapersada** [comment]
http://45.148.26.41/spider-man-far-from-home-2019/
https://hive.gdriveplayer.link/FH-aLArERC63clN0I8u8e6zgtWReA3FvjNsshIHGrIVjSVNzc4SHZnDhkgYaATLzn5H9pnbXfWthO4mzPW_2mg/_mn0D9w4k8GOMO6giUYZM0iE4RN3v4oqrJuEVWOHUA4/360.m3u8

**Comment by firedm** [comment]
same thing
for first link, player failed to play video 
![image](https://user-images.githubusercontent.com/58998813/147889156-345f5d1f-fff0-412b-88fc-f21d1b6dcf35.png)

and second link same as before

please open a new issue if you feel this is not a connection problem, because this issue is already closed
