### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#374]
Hello, I find this oPen source software and I see many bug fixes and enhancements , may be it can help in case there is bugs......

https://jeanslack.github.io/Videomass/

Here the changelog of the new version of this software : 
* Fixed `command not found` issue. In some cases using pip to install
Videomass the directory is not added to the $PATH.
* [YOUTUBE-DOWNLOADER] Added option to get 'Best', 'Medium' and 'Worst' of
precompiled videos. It may be useful to speed up video download containing
both audio and video, e.g. without download video and audio separately and
then executing the merging process with FFmpeg.
* [YOUTUBE-DOWNLOADER] Improved 'Get Statistics' and 'Download by Format Code'
features. This should improve exception management of unusual web site
data structures (like <http://zen.yandex.ru/>) and playlists, channels, etc.
* #41 Fixed mount point issue on external drives using relative paths on
MS-Windows. If "ValueError" is raised, it returns the absolute path given
instead of showing the error.
* [YOUTUBE-DOWNLOADER] Improved 'Download all videos in playlist' feature
when checked on URLs containing playlists.
* [YOUTUBE-DOWNLOADER] fixed audio quality when 'Download split audio
and video' option is selected.
* [NEW] Added the ability to read and write useful notes with deafault text
editor (Request made by @ChourS).
* During the processes some menu items have been enabled allowing you to
perform some useful actions.
* Improved Setup dialog with a new Miscellanea tab.
* Added the ability to delete the contents of log files when exiting the
application (see Setup dialog Miscellanea tab).
* Update Russian translation from @ChourS
* Update Italian translation from @jeanslack

**Comment by firedm** [comment]
> Hello, I find this oPen source software and I see many bug fixes and enhancements , may be it can help in case there is bugs......

@trimechee 
every project has its own bugs, and fixes in one project won't help in the others, anyway thanks for suggestions

**Comment by trimechee** [comment]
Ok thank you, I posted this because Aman9das said to you that he analyzes uget extension and this software talks about ffmpeg and bug fixing and a lot of software uses the code of other software on condition of sharing their code to the public .... :   
"Yes .. Note that you'll have to change the directory address in firedm.json to point to browser.py

uget extension is quite helpful to learn how to support multiple browsers. Let's support get it running with firefox first, and then add support for chromium ..

@firedm Did you test it out ?, is it able to connect back and forth?

I could move the PR from master to another branch and we could try develop from there .. "

https://github.com/firedm/FireDM/pull/348

**Comment by firedm** [comment]
@trimechee 
it is no problem at all you suggested something, and you're welcome anytime 

when we need to add a new feature for example "supporting google drive"  or make browser extension as you mentioned above, will look for other open source project that could help 

but for bug fixes, nothing could help, since bugs are very specific to your code, and human errors

**Comment by trimechee** [comment]
Ahh I did not know it ! thank you very much for these clarifications :)

**Comment by trimechee** [comment]
Thank you :) i understand konow, i found also this software wich has many new features like live recording, may be it can help....

https://github.com/xhlove/XstreamDL-CLI
