### ISSUE TITLE
Optionally enable / disable storage of folders with backups like firedm_bkup and others

### ISSUE THREAD

**Issue by l3xrom** [firedm/FireDM#375]
Hello @firedm!
I really like your work and I recommend it to all my friends. But recently, one of them asked me a question that I could not answer.

For what it has more than a thousand files, while it uses youtube-dl and yt-dlp which have compiled executables like ffmpeg.exe which is in the root folder and works fine. It was possible, as in some other GUIs, to simply refer to the same executable files youtube-dl and yt-dlp.

Also in the FireDM\lib folder there are folders with backups, which are quite understandable for what they are needed, but is it possible to make their storage optional, because personally they have never been useful to me yet? And the point is not even the number of Mb occupied by them, but in the compactness and simplicity.

There are also folders with the ending .dist-info, but I don't quite understand their usefulness, and after deleting them, I did not experience any problems with the functioning of FireDM.

I hope you don’t take this as some kind of criticism, since I did not put such a meaning in my text at all. I still use your FireDM and I think it is by far the best GUI for youtube-dl and yt-dlp. I hope to receive answers that will help me in the future to confidently answer such questioners.

**Comment by firedm** [comment]
@l3xrom 

> It was possible, as in some other GUIs, to simply refer to the same executable files youtube-dl and yt-dlp.

most GUIs are running youtube-dl and yt-dlp executables in a background shell to do the download, and there is no difference in performance if you run these executables directly from command line / terminal
but FireDM is different here, where it uses youtube-dl and yt-dlp library to only fetch video info, then use a multi-connection download with the help of libcurl, you can notice a very high difference in download speed especially if you try to download HLS videos

in short, FireDM doesn't use  youtube-dl and yt-dlp executables.

> Also in the FireDM\lib folder there are folders with backups

these folders created when you update application thru update button, to give ability to revert these updates

![image](https://user-images.githubusercontent.com/58998813/143222315-bb385ecd-b5cc-43c5-a89c-5b96913634c7.png)

> There are also folders with the ending .dist-info, but I don't quite understand their usefulness, and after deleting them, I did not experience any problems with the functioning of FireDM.

these folders has pkgs info and used by python pip to remove and update packages

>  hope you don’t take this as some kind of criticism

no problem at all, and i welcome any more questions

**Comment by l3xrom** [comment]
@firedm, OK
Thank you, you have confirmed my guesses, now everything is more clear to me.
