### ISSUE TITLE
clip boards monitor to switch focus to firedm after it has parsed the url to save user from waiting while url is being parsed.

### ISSUE THREAD

**Issue by mrustad67** [firedm/FireDM#376]
current clip board monitor switches to firedm immidietly after sensing downloadable url,   user has to wait until URL gets parsed to choose the format and other choices,   it would be good to have preset choices in menu,  and optionally  switch focus from browser to firedm when parsing has been done.   so that users time saves form seeing firedm doing parsing of  URL.

i did little programing with basic,  and know that a few lines need editing to get firedm present ready parsed url for choices to user instead of forcing user to look at parsing process for several seconds or minutes,   but  havent ever practiced editing this kind of software,   maybe there are good youtube guide  for  learners like me to change software like firedm to as we want it to work.

**Comment by firedm** [comment]
@mrustad67 
you can disable clipboard monitoring from option and paste the link manually
regarding switch focus, we can make the switch after finish processing the link
