### ISSUE TITLE
Unable to download from Twitch

### ISSUE THREAD

**Issue by AndrewISampson** [firedm/FireDM#377]
Since 10am GMT, I have been unable to download videos from Twitch.
Even files that I had previously downloaded cannot be now be downloaded.

When adding a Twitch video, the following error occurs:
>> get_headers()> (28, 'Resolving timed out after 10003 milliseconds')

When downloading the video, I get:
>> received invalid m3u8 file from server

Example file: https://www.twitch.tv/videos/1218749756

**Comment by firedm** [comment]
@AndrewISampson 
just tested the link you provided and it downloads normally, with no problem 
i think you might have connection problem, make sure you can watch this video on web browser first  then try again

**Comment by AndrewISampson** [comment]
Aaaaaaaaaaaand now it works........that is so weird.

Well.....nothing to say but......keep up the awesome work you're doing with FireDM
