### ISSUE TITLE
Make "paste link" button "always visible even in the" Downloads "section 

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#380]
We thank you very much for this new exceptional version which brings a lot of improvements and novelties and opus format, thank you very much :) I have a request please: sometimes I download several videos successively, so I copy paste the link in FireDM, I choose a format then automatically the "dowloads" section where we see the downloads progress, then I return to my web browser to copy paste another link but I see the "downloads" section in FireDM dn and I have to click again on the "Home " section "to paste the link ....
there is no problem if it is a few videos but sometimes we download a lot of videos and it gets a bit tiring to click every time on "Home", so we will be grateful if you have a "paste link" button "always visible even in the" Downloads "section to speed up the process of downloading a lot of videos even more, thank you very much!

**Comment by trimechee** [comment]
So apparently it is not possible to add an option to fix the "paste link" button and leave it visible in the downloads page to save time, I understand that it may not be aesthetic..... anyway thank you very much :)

**Comment by firedm** [comment]
> So apparently it is not possible to add an option to fix the "paste link" button and leave it visible in the downloads page to save time, I understand that it may not be aesthetic..... anyway thank you very much :)

Sorry for this,
i think it will be better to get the browser extension ready which will make it easier for you than add paste button in other tabs

**Comment by trimechee** [comment]
I understand, thank you very much :)
