### ISSUE TITLE
Exit when finished

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#382]
Hello, it will be great to add this option "exit when dow,loads finished" because my computer is programmed to hibernate after a while of inactivity and we can sleep by letting FireDM download large files and when the download is finished it will be good if FireDM closes automatically so the computer can go into hibernation in sha Allah, thank you very much !

**Comment by firedm** [comment]
@trimechee 
no problem, will consider this feature

**Comment by trimechee** [comment]
Great ! Thank you so much !

**Comment by Aboghazala** [comment]
@trimechee 
Done, option will be available in coming release

**Comment by trimechee** [comment]
Ohhhhh fantastic !! thank you very much, we are so greatful :)
