### ISSUE TITLE
Just out of curiosity

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#384]
Hello, just out of curiosity, the new versions of FireDM uses the official version of FFmpeg or the modified version of FFmpeg modified by yt-dlp? this is just out of curiosity because FireDM works great for me and I have no problems downloading youtube and facebook videos ....
if FireDM does not use the version of FFmpeg modified by yt-dlp, could that cause bugs if one day we adventure to remove the official version of FFmpeg and replace it with the FFmpeg version customized by yt-dlp and put it in the FireDM settings directory ?

**Comment by firedm** [comment]
@trimechee 
FireDM windows portable release uses the modified build by yt-dlp
however the official build works, the modified version in some special cases can be faster (few seconds compared to minutes in official one) while muxing video and audio

**Comment by trimechee** [comment]
Great ! thnak you so much !
