### ISSUE TITLE
Embedded videos and trsuted open source extension to detect video streams

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#385]
Hello, we know that it is very difficult and complicated, maybe even impossible but this is a suggestion to make even more FireDM superior to other competitive downloaders in sha Allah , and we know that the developer of FirDM is so generous and helpful and brilliant ma sha Allah and the FireDM team is brilliant too !

The streaming web sites often integrate video players from video hosting platforms like uptobox and many others platforms like for example these web sites which offer a wide choice of different video players for the same episode:

https://wiflix.tel/serie-en-streaming/22418-invasion-saison-1.html

or

https://www.zone-telechargement.cam/telecharger-serie/67102-telecharger-the-grand-tour-saison-4-saison-4-webrip-french.html

or

https://wwvv.cpasmieux.cam/series/8851-evil/2-season/1-episode.html

The problem is that these videos are integrated into the web page and there is no direct link to these video hosting platforms  so it is sometimes very complicated to download them, for example we have to search the video platform icon integrated in video players and click on it to go to the original hosting site and thus get the link of the original video but by doing that  we suffer from a a lot of ads and even deceptive virus pages, sometimes you have to right click on the video player to get the original url address and sometimes it's written in russian language .....

So my question and my suggestion is : please is it possible that FireDM scan the web page to detect embedded videos and thus simplify the download process? maybe integrate some kind of integrated browser to detect embedded videos? or invent trsuted open source extension to detect video streams which is very rare because mostly  we do not find extensios of this type which are open source and without advertising??

I searched on chrome store and I can't find any free open source extensions that allow downloading videos, there are effective video extensions but they are not open source, and some extensions are paid and sometimes they may contain malware and traps like the famous "savefrom" video extension where yandex after sharp and complicated analyzes found that this famous extension sophisticatedly traps users by secretly playing videos and bypassing browser security:

https://forums.opera.com/topic/46105/virus-in-the-popular-extension-savefrom

https://habr.com/ru/company/yandex/blog/534586/

I discovered that we can download videos from streaming sites without needing to install an unknown extension that can trick us by going to the web browser settings and clicking on Chrome DevTools and looking for the network section and looking for the video streams. ... but it's difficult, complicated and you have to be an expert and it's long .....
 so my suggestion is to make an open source extension which simplifies this process and detects the video streams and thus send the found video stream to FireDM to speed up the download in sha Allah, the videos on the streaming sites are not protected so we can download them, we trust the developer of FireDM and the FireDM team and we hope that FIreDM will dazzle us by inventing an incredible open source extension that detects videos and sends them to FireDM to speed up downloads in sha Allah!

I searched on github and I can't find open source video extension that detects video streams but I found this open source extension that downloads all types of video streams, the latest version is from 2018:

https://github.com/LeonardoCiaccio/GrabAnyMedia

I heard that there are a lot of bookmarklets which cause viruses and hacks so I'm afraid to use bookmarklets but we trust FireDM and maybe a bookmarkelt invented by FireDM can replace the extension, I found a Crawler bookmarklet made by an Italian developer:

https://github.com/LeonardoCiaccio/Crawy

Thank you very much !

**Comment by firedm** [comment]
@trimechee 

some videos have its download link embedded in webpage content, and others will be loaded dynamically by javascript when you play a video 

extracting download links statically is easy (some how) and this is what youtube-dl and yt-dlp do
to extract download links which get loaded dynamically by javascript, it requires running javascript, one of these methods i tried and it works is making a custom extractors for youtube-dl which uses selenium and a webdriver
however this method works, but it is very slow and can not be shipped in final app release

the best method is to use a web extension, since it will be installed in the web-browser it has everything it needs to do the job

making this kind of web extensions requires a lot of work and time, not sure if we can start this kind of projects, but maybe in the future we will

**Comment by trimechee** [comment]
Thank you very much for this insight :) yes I understand, it was just a suggestion, the most important is to be able to download the youtube and facebook videos and extract their audio streams which video extensions cannot do and FireDM works perfectly, thanks a lot :)

it's surprising that there are no extensions on github which allow to extract the video streams or maybe I did not look very well .... but it does not matter, because I 've tested several extensions and I think the Video DownloadHelper extension is the most efficient even if it is not open sourc and I can have the url of the video and put it in FireDM to speed up downloads in sha Allah,
  thank you very much for this interesting information and thank you for all your efforts to make FireDM even better !

**Comment by trimechee** [comment]
Just for curiosity, you said "however this method works, but it is very slow and can not be shipped in final app release", very slow ie several minutes, or hours? Personally, I would be very happy and privileged to test this method because I admit that I do not like using video extensions that are not open source or have paid option, the press often talks about infected malware extensions ....

I allow myself to submit a suggestion if that doesn't bother you: it would be extraordinary and rare compared to other dowloaders for users to be able to test this method that you invented and put it in a kind of experimental version independent of the official version of FireDM, it will be amazing to integrate in an experimental version or an alternative version the methods of selenium and a webdriver .....

 then the users have nothing to lose, anyway they cannot download the content they are looking for so using this experimental version can help if you are afraid of using untrustworthy extensions or you have a hard time find trusted extensions where maybe even one day video extensions could be banned from the chrome store or edge store and there have been extensions banned from the chrome store like the famous skyload extension which has been banned many times from the chrome store because it allows you to download from certain sites ..... to such an extent that the developer of this extension has described a method to install its extension on chrome browser although the chrome store has banned this extension but it is a bit complicated to where my fear that the most effective video extensions will be more and more banned from stores hence the interest of my suggestion to make an alternative or experimental version of FireDM which running javascript and selenium and a webdriver .......

https://www.hashtap.com/@skyload/guide-to-install-skyload-extension-in-chrome-browser-amMb_QyE0BlP


and if the porcessus takes a long time, we can always cancel the analysis of links from streaming sites .....

but if this is not technically possible, then there is no problem and we understand that the software must be as fluid as possible :)

**Comment by firedm** [comment]
we might make a separate project for this, will let you know if one is available

**Comment by trimechee** [comment]
Fantastic ! we are very grateful to you !

Thank you so much ! may Allah bless you !

if people are wondering why I expected this complex functionality like selenium and a webdriver .... my wish is to recommend FireDM to my twitter subscribers and my friends and family in sha Allah but some do not necessarily understand how to do like choosing a video extension to download and this extension must have a "copy video url" option and then put the link on FireDM .....
in addition the video extension will be activated all the time even when they do not want to download videos which will make the web browser cumbersome and some will be afraid to install unknown video extensions ..... this is why an all solution in one would be ideal even if it takes a long time to analyze the web page, we could put the link of the streaming page in FireDM and do something else and browse other sites while waiting for FireDM to analyze and download the videos embedded in sha Allah!

Thank you very much for your kindness and patience :)

**Comment by trimechee** [comment]
Oops sorry I closed the subject involuntarily and I'm trying to cancel it but I don't know how to do it

**Comment by firedm** [comment]
> Oops sorry I closed the subject involuntarily and I'm trying to cancel it but I don't know how to do it

no problem, it will be a separate project away from FireDM, this issue will be closed anyway

**Comment by trimechee** [comment]
Ohhh magnificent ! we are very grateful to you for providing us with these rare features that cannot be found elsewhere :)
