### ISSUE TITLE
Option to put the button "paste link" on the left

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#388]
Hello, since the "downloads" section is on the left, when you download several videos, you have to click on the "home" section on the left then go to the right to paste the link, and if you have several videos, it can be a bit tiring , it will be great if there is an option to put the "paste link" button on the left or put the "home" and download "sections on the right, in addition some users are left-handed .... thank you very much :)

**Comment by firedm** [comment]
@trimechee 
i see you need faster method to paste a link
i just made a keyboard shortcut "Alt-v", you can use it anywhere no matter which tab is opened in  FireDM, and it will paste clipboard contents in url entry and switch to home tab automatically

is this ok with you

**Comment by firedm** [comment]
or i might set the shortcut to "Ctrl-Shift-v", still thinking about it

**Comment by trimechee** [comment]
Great, thank you very much :)
