### ISSUE TITLE
Fail to donwload from website

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#389]
Hello, I'm trying to watch this streaming  video in HD but it jerks and lags because one or more members of my family are connected to wifi, so I have the idea to download the video from this sport highlights site, I made right click on the embedded video player and I was able to get the url address of the original video and I put the url address in FireDM but it fails to download the video, I also put the url of the video in potplayer after installing 3DYD Youtube Source but potplayer and 3DYD Youtube Source also fail ....

I also tried with the powerful Video DownloadHelper video extension but unfortunately it also fails .....

this video hosting site is very important because it often hosts football highlights while avoiding censorship so it will be great if we can download this video from this video hosting platform, thank you !

https://ourmatch.me/04-12-2021-barcelona-vs-real-betis/

original video

https://dkoms.korafact.com/embed/Qj8k5CNczAuga

**Comment by firedm** [comment]
website is not supported by youtube-dl nor yt-dlp
try to find the url manually by inspecting the webpage 
should be a url ending with `.m3u8` 
then paste the link into FireDM

**Comment by trimechee** [comment]
Yess ! thank you :)
