### ISSUE TITLE
Off topic 

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#392]
Sorry it's out of context, I'm asking my question to you because you're generous and you help people, the developer of this extension says at the end of the description of his extension that he made a bookmarklet:

https://chrome.google.com/webstore/detail/minimal-reading-mode/peoapnglceoafojobbkpohnojniabmkd

I click on the bookmarklet link :

https://gist.github.com/luckyshot/8a28768ae0f7035146946272563d8863#file-readingmode-js

but i can't find how to add this important bookmaklet to my bookmarks bar, can you tell us how to do  please ?

**Comment by firedm** [comment]
sorry @trimechee 
i have no idea

**Comment by trimechee** [comment]
There is no problem lol, thank you very much, I would have liked to contact the developer but I didn't know how .... i keep use reader mode in chrome flags of chromium in sha Allah
