### ISSUE TITLE
NameError: name 'get_pkg_path' is not defined

### ISSUE THREAD

**Issue by wada3n** [firedm/FireDM#393]
السلام عليكم
بعد تحميلي للنسخة الأخيرة الخاصة بنظام لينكس
Linux: [.AppImage file]
تأتيني رسالة الخطأ التالية:

> File "/tmp/.mount_FireDMzGplAP/run.py", line 112, in <module>
    orig_pkg_version = get_pkg_version(os.path.join(src_folder, pkg_name))
  File "/tmp/.mount_FireDMzGplAP/run.py", line 37, in get_pkg_version
    pkg_path = get_pkg_path(pkg_name)
NameError: name 'get_pkg_path' is not defined

**Comment by firedm** [comment]
وعليكم السلام
ما هو رقم الاصدار
version number?

**Comment by Aboghazala** [comment]
شكرا على التوضيح سيتم اصلاح المشكلة ان شاء الله

**Comment by Aboghazala** [comment]
new fix will be available in coming release, will close this issue
