### ISSUE TITLE
why the video is broken when playing

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#394]
for example, a video that I downloaded video and audio dash but when I play it after the download is complete the video stops, only the audio is still running until it's finished?
Firedm 2021.12.2.post1
>> start downloading file: "テイルズ オブ ジ アビス ストーリーパート part29 【PS2】.mp4", size: 0 B, to: D:\FireDM
>> url: "https://www.youtube.com/watch?v=CpzBdATcudo" 

>> File: テイルズ オブ ジ アビス ストーリーパート part28 【PS2】.mp4, saved at: D:\FireDM
>> merging video and audio
>> frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=0.0444x
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (0 > 66).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 70
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (10485760 > 34).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 38
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1114113 > 69).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 99
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (805306624 > 58).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 62
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (7680 > 121).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 125
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (0 > 132).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 136
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (0 > 58).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 62
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 69).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 73
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (16777216 > 91).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 95
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 48).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 52
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (805306624 > 80).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 127
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (0 > 57).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 61
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 92).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 96
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 84).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 88
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 92).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 96
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 44).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 48
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (65536 > 195).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 199
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1553715760 > 39).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 43
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1445968687 > 21).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 25
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1357559915 > 42).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 46
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1576046150 > 92).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 96
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1624125734 > 58).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 62
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1143933602 > 47).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 51
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (426338724 > 36).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 40
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-193397457 > 32).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 36
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (448733946 > 29).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 33
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1044216054 > 59).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 63
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (123686811 > 94).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 98
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (867038108 > 29).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 33
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (150125562 > 34).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 38
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1253236490 > 101).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 105
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (287363935 > 53).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 57
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1062601885 > 70).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 74
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-909798949 > 57).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 61
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-514476047 > 115).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 119
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (135667628 > 76).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 80
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1243217462 > 180).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 184
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-176046204 > 37).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 41
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1324549663 > 61).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 65
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (549889960 > 39).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 43
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-727773374 > 224).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 228
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1911436993 > 64).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 68
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-721066011 > 85).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 89
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-885427973 > 89).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 93
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-41184231 > 62).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 66
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1389427253 > 199).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 203
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1753124319 > 64).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 68
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-679923533 > 44).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 48
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1666229281 > 50).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 54
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1112434342 > 32).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 36
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1824366446 > 43).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 47
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1233567572 > 42).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 46
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1991894868 > 44).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 48
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-204075624 > 47).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 51
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-403715067 > 54).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 58
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-2106765197 > 57).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 61
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1530855280 > 43).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 47
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (2037433360 > 69).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 73
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-2066808915 > 76).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 80
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1508230663 > 78).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 82
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (311891304 > 33).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 37
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (432779407 > 103).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 107
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-378843966 > 80).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 84
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (2077932646 > 84).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 88
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (482058093 > 53).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 57
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (98985763 > 109).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 113
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-90641631 > 39).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 43
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1976684561 > 166).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 170
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (11511509 > 78).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 82
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-839442676 > 96).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 100
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1549237210 > 114).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 118
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1324996739 > 82).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 86
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-142631604 > 79).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 83
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (817357948 > 96).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 100
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1674170840 > 114).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 118
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (724988136 > 70).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 74
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1858913974 > 115).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 119
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-192740509 > 47).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 51
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1563314033 > 41).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 45
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-1174124626 > 39).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 43
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-191645521 > 35).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 39
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-35613230 > 40).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 44
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (1218832028 > 55).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 59
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-781699989 > 55).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 59
>> [NULL @ 00000000004ddec0] Invalid NAL unit size (-746090268 > 69).
>> [NULL @ 00000000004ddec0] missing picture in access unit with size 73
>> frame=21441 fps=0.0 q=-1.0 Lsize=   10127kB time=00:13:06.41 bitrate= 105.5kbits/s speed=2.17e+03x
>> File: テイルズ オブ ジ アビス ストーリーパート part29 【PS2】.mp4, saved at: D:\FireDM

**Comment by Aboghazala** [comment]
@candrapersada 

which video quality and audio type you chose when downloading this video
you can right click the download item in downloads tab and select properties to find out

**Comment by candrapersada** [comment]
```
Video stream:     mp4 - 480 - 0 B - id:135 - 30 fps
Audio stream:     m4a - 132 - 0 B - id:140-dash

```

**Comment by Aboghazala** [comment]
i just tried to download the link with 
```
Video stream:     mp4 - 480 - 0 B - id:135 - 30 fps
Audio stream:     m4a - 131 - 0 B - id:140-dash
```

and it works with no problem

i guess, due to network issues some segments failed to be downloaded and it has zero size on disk, this is why ffmpeg shows error

i think FireDM shouldn't mark a zero sized segment as completed
will check what we can do
meanwhile, i think if you retry downloading the video again, it will work properly

**Comment by candrapersada** [comment]
> meanwhile, i think if you retry downloading the video again, it will work properly

but in the Download Tab there is no button to retry downloading the video again

**Comment by Aboghazala** [comment]
> but in the Download Tab there is no button to retry downloading the video again

you can right click "this download item" and copy webpage url, then it will switch to main tab and you can download again

**Comment by candrapersada** [comment]
why is my problem closed?

**Comment by Aboghazala** [comment]
because i can't reproduce the same error
