### ISSUE TITLE
changing "concurrent downloads" does not work until restart FireDM 

### ISSUE THREAD

**Issue by joshatt** [firedm/FireDM#396]
FireDM v2021.12.2.  
Window 7.
I'm new here, correct me if I'm wrong: I changed  "concurrent downloads" down to 1, but it did not work, until I restarted FireDM.

Please keep up the fantastic work!

**Comment by Aboghazala** [comment]
@joshatt 
just tested this option and it works properly, not sure which issue you have
note: changing this option will have no effect on "the ongoing downloads", for example if you have 3 items currently downloading and you change "concurrent downloads" down to 1, the 3 items will continue until finish then new one from pending items will start

**Comment by joshatt** [comment]
> @joshatt just tested this option and it works properly, not sure which issue you have note: changing this option will have no effect on "the ongoing downloads", for example if you have 3 items currently downloading and you change "concurrent downloads" down to 1, the 3 items will continue until finish then new one from pending items will start

I just tried again, you're totally right. Last time I tried, downloads must be ongoing. Thanks for your help.
