### ISSUE TITLE
feature request: a beep AFTER streams list fetched

### ISSUE THREAD

**Issue by joshatt** [firedm/FireDM#398]
Wonderful job. The whole process for multiple videos is fluent and the download is super fast. 
One request of an option: if there is a beep that tells me streams list has been fetched for each task, which kills some waiting seconds and the process will be even better.

**Comment by Aboghazala** [comment]
@joshatt 
you can leave it in background and FireDM will bring itself on top of other windows when done processing url and video(s) list is ready

**Comment by joshatt** [comment]
> @joshatt you can leave it in background and FireDM will bring itself on top of other windows when done processing url and video(s) list is ready

That's great, great enough for me. Thanks!
