### ISSUE TITLE
"No subtitle available" forever

### ISSUE THREAD

**Issue by joshatt** [firedm/FireDM#399]
I've been here for only 2 days, and never seen any subtitle for any video. For example: 
https://www.youtube.com/watch?v=hmb75r4yBbI
FireDM version is 2021.12.2.post1
BTW, I'm behind proxy, in order to download youtube videos.

**Comment by Aboghazala** [comment]
@joshatt 
thanks for reporting this, just found the bug and the fix will be available in coming release

**Comment by Enrico9431** [comment]
Hopefully it'll be fixed asap, thanks in advance.

**Comment by Enrico9431** [comment]
Am still unable to download subtitles.
