### ISSUE TITLE
HELP - How to download MP3 at high quality instead of 124kb cap? 

### ISSUE THREAD

**Issue by ProgammerOrProGamer** [firedm/FireDM#401]
Can't find any option to download a mp3 with at least more than 240 kbs. I'm not talking about FLAC. Just MP3.

**Comment by Aboghazala** [comment]
@ProgammerOrProGamer 
an mp3 stream option in FireDM is simply an m4a audio converted by ffmpeg
here is the internal command used by FireDM
`ffmpeg -i audio.m4a -acodec copy audio.mp3`
ffmpeg will use its default values in conversion process
