### ISSUE TITLE
Playlist download window - Typo and truncated path

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#402]
Hi,

I wanna report a little typo:

![image](https://user-images.githubusercontent.com/69006279/146699122-579b60ab-45fe-48cc-b042-2481aff28c87.png)

and the folder path truncation at the end of the window:

![image](https://user-images.githubusercontent.com/69006279/146699157-5bb966f8-122a-4562-9e9b-9ebb2a45c838.png)
(there is a lot of unused space on the right to show it completely)

Thanks
Daniele

**Comment by Aboghazala** [comment]
@jdaniele71 
thanks for reporting

**Comment by jdaniele71** [comment]
You are welcome and thank you as well.
