### ISSUE TITLE
Playlist download window - Video quality selection per video disappeared

### ISSUE THREAD

**Issue by jdaniele71** [firedm/FireDM#403]
Hi, 
In the previous version we could check at what resolution any single video will be downloaded.
For example, if i selected 480p in the master selection and one of the video did not have it, FireDM would choose a different resolution and i was able to check it before download.

Now, I cannot see the final resolution anymore beside the video name, so it not possible to check if, for few any video, the resolution selected is not available and what resolution has been chosen by FireDM instead.

Even after download, there is no info about resolution in the download window!

![image](https://user-images.githubusercontent.com/69006279/146700134-3f5f4d39-6f85-40e9-95e0-1446c69496ba.png)

So I will be able to check only by windows Explorer, after having lost much time to download.

That's not good.

How to solve it?
Did I miss any hidden feature about "reporting" the final resolution?
Thanks
Daniele

**Comment by Aboghazala** [comment]
@jdaniele71 
you can check video resolution from downloads window by right click the item and select properties

here is an example of what you can see
![image](https://user-images.githubusercontent.com/37757246/146772413-a7c5f365-7f03-44fe-a0ee-79478ec130ed.png)

regarding playlist window:
the new playlist window designed to fix the issues of the previous one, so to speed up operation and make playlist faster and light, only names of playlist videos are available in this stage, and no video metadata is fetched

**Comment by jdaniele71** [comment]
> @jdaniele71 you can check video resolution from downloads window by right click the item and select properties

ok, thanks.

> regarding playlist window: the new playlist window designed to fix the issues of the previous one, so to speed up operation and make playlist faster and light, only names of playlist videos are available in this stage, and no video metadata is fetched

So how to check which resolution will be downloaded **BEFORE** starting the playlist download?
As you know, not all videos have all resolution available.
Thanks

**Comment by Aboghazala** [comment]
> So how to check which resolution will be downloaded **BEFORE** starting the playlist download?
> As you know, not all videos have all resolution available.
> Thanks

there is no way to check in playlist window, because there is no metadata available
but the nearest resolution value will be chosen, e.g if you select 720p and video file has only (480p and 1080p) it will do some math to check lowest difference
abs(720 - 480) = 240
abs(720 - 1080) = 360

so it will pick 480p
