### ISSUE TITLE
Manifest V3 and extension

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#405]
Assalam alaykoum, many peopole sais that manifest 3 which will go into effect in January apparently is Deceitful and Threatening, have many negative effects and  it brings ruin to browser extensions....i dont' know if this is true but i knwo that FireDM team is developing an extension, will firedm extension be negatively impacted with manifest 3? I even read a discussion on the github page of tampermonkey that tampermonkey will be impacted and scripts may not work properly apparently .....

 mozilla says it will also apply manifest v3 for compatibility but give the developers time and money to make the changes, but brave browser says it will keep manifest 2 for its ad blocker. ...

so how is FireDM going to adapt to manifest v3? can firedm still extend with manifest 2 so the extension will be more efficient? in this case, the extension will no longer be in the chrome and firefox store, so I suggest to the FireDM team to make a crx o xpi extension in manifest v2 and make it available outside the official chrome and firefox stores and we the users we install it manually in sha Allah because we have confidence !

Thank you so much!

**Comment by trimechee** [comment]
Articles on the effects of the manifest v3 : 

https://www.eff.org/deeplinks/2021/12/chrome-users-beware-manifest-v3-deceitful-and-threatening



https://www.eff.org/deeplinks/2021/12/googles-manifest-v3-still-hurts-privacy-security-innovation



https://www.reddit.com/r/Adguard/comments/rgdk61/manifest_v3_is_coming_in_two_weeks_and_it_brings/

**Comment by Aboghazala** [comment]
@trimechee 
thanks for your follow up
will consider these points

**Comment by trimechee** [comment]
Excellent ! Thank you so much :)
