### ISSUE TITLE
Download books 

### ISSUE THREAD

**Issue by trimechee** [firedm/FireDM#406]
Assalam alaykoum wa rahmatou Allah wa barakatouh, i found alhamdoulilAllah a many huge gigantic online libraries like pdfdrive, z-lib, libgen ..... and many muslim religious books pdf  and audio in islamland librarary online .......and even audiobooks like on librivox .....

many books are free public domain so we have the right to download them, for example if I type the name of an author on pdfdrive or z-lib, I would have a hundred books displayed, and I would like to download them from one shot in one process without clicking hundreds of links, so I'm wondering if FireDM can download this kind of book with one click by scanning the page and download with one click these pdf books ?

Thank you very much, of course we have to buy books to support the authors but sometimes we can't buy all the books and some books are copyright free because the authors are dead .....

**Comment by Aboghazala** [comment]
@trimechee 
please provide an example link

**Comment by Aboghazala** [comment]
@trimechee 
unfortunately, these are not direct links
every book entry has to be opened in new page to show download button
you better use a dedicated application for this, which is specialized in downloading books
we try to keep FireDM as simple as possible to focus on video files downloading

**Comment by trimechee** [comment]
Ahh I understand :) that was just a suggestion and we can download with traditonal way , thera is no problem, thank you very much 👍

**Comment by trimechee** [comment]
And I see the changelog of  the new version, there is many new amazing features and options, wa are so grateful and we thank very much all the developers and FireDM awesome team :)
