### ISSUE TITLE
Site support request

### ISSUE THREAD

**Issue by Mr-Personality** [firedm/FireDM#407]
Please could you support this site?
https://www.channel5.com/show/filthy-garden-sos/season-1/episode-1

**Comment by Aboghazala** [comment]
@Mr-Personality 
currently FireDM depends on both youtube-dl and yt-dlp to extract video info

it is better to submit this request at both youtube-dl and yt-dlp repo
or if you can make a custom youtube-dl extractor you can add this script file to FireDM's settings folder under folder named extractors

on other hand we are working on a dynamic link extractor application to extract download links easily, will let you know once it gets ready
