### ISSUE TITLE
Still unable to download any subtitles, saying "No subtitle available"

### ISSUE THREAD

**Issue by Enrico9431** [firedm/FireDM#408]
Even though #399 has been closed I still am unable to download any subtitles as it shows none.

I have the latest version of everything.

**Comment by Aboghazala** [comment]
@Enrico9431 
the fix will be shipped with coming FireDM release,
but if you need this fix now, you can install this fix manually
are you running FireDM on windows?

**Comment by Enrico9431** [comment]
Am running it on windows yes.

**Comment by Aboghazala** [comment]
@Enrico9431 
you can download this file https://github.com/firedm/FireDM/raw/master/firedm/utils.py save it as utils.py and replace the old file at FireDM/lib/firedm folder
and it should fix subtitles

**Comment by Enrico9431** [comment]
Great, it works. Thanks!

**Comment by Aboghazala** [comment]
> Great, it works. Thanks!

wonderful

**Comment by joshatt** [comment]
Great, utils.py works like a charm!
