### ISSUE TITLE
FFmpeg path for FireDM version 2021.12.23

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#409]
why isn't this in the FFmpeg path?
![b](https://user-images.githubusercontent.com/36833664/147301385-6a070ce1-19d2-42bc-a5fa-6cf708fabace.PNG)
![a](https://user-images.githubusercontent.com/36833664/147301358-bbd54528-39ff-43d4-9bef-b227f753ae2c.PNG)

if you can add this
![c](https://user-images.githubusercontent.com/36833664/147301485-cdf53a14-a26b-4992-91e6-80ce2da997cd.png)

**Comment by Aboghazala** [comment]
@candrapersada 
No problem, will add browse button for easier selection
