### ISSUE TITLE
FireDM - buttons, tool tips and context menu entries case inconsistencies

### ISSUE THREAD

**Issue by smaragdus** [firedm/FireDM#410]
I notice that the buttons and tool tips in **Home** panel have different styling as different cases are used:

- **lower case:**
  - clear and paste [Ctrl-Shift-V] (tool tip)
  - clear (tool tip)
  - audio quality (tool tip)
  - change folder (tool tip)
  

- **UPPER CASE:**
   - DOWNLOAD (button)
   - LTR (button)

-  **Title Case:**
   - Retry (tool tip)
   - Download Playlist (tool tip)
   - Download Subtitle (tool tip)
   - About (tool tip)
   - Download Later (tool tip)

 - **Sentence case:**
   - Batch download (tool tip)
  
The same applies for **Downloads** panel for buttons, tool tips and context menu entries:

- **lower case:**
   - select (tool tip)
   - view (tool tip)
   - filter (tool tip)
   - copy webpage url (context menu)
   - copy direct url (context menu)
   - copy playlist url (context menu)

-  **Title Case:**
   - Resume All (button)
   - Open File (Enter) (context menu)
   - Open File Location (context menu)
   - Delete (Del) (context menu)
   - Properties (context menu)
  
I think that the buttons, tool tips and context menu entries would look better if unified styling is chosen- either **Title Case**, or **Sentence case**, or **lower case** or **UPPER CASE**. I prefer **Title Case**.

Several notes:

- I think that **[Ctrl+Shift+V]** is better than **[Ctrl-Shift-V]**.
- I think that **URL** should always be in **UPPER CASE**.
- If **Title Case** is chosen for all buttons, tool tips and context menu entries, **DOWNLOAD** button may be also styled in **Title Case**- **Download**.
- **LTR** button might be made a little bigger so that It can contain the whole word **Later**.
- **DOWNLOAD** and **LTR** buttons may have the same size for even more unified looks.

All this is of no importance yet unified text styling would make the GUI look better and more consistent,

**Comment by Aboghazala** [comment]
@smaragdus 
thanks for this great feedback
will consider these recommendations for GUI to look consistent

**Comment by Aboghazala** [comment]
@smaragdus 
i did some play around, with 2 buttons have same size
not sure  which is the proper position of the buttons 
![image](https://user-images.githubusercontent.com/37757246/147397979-c4d60f44-1dd8-4f3f-a6ef-028de1378d3a.png)

or bith at the end
![image](https://user-images.githubusercontent.com/37757246/147398034-67fe2483-1ef3-42d5-897f-88737f59e985.png)

i feel that both positions are not right
maybe at the very bottom right corner
or maybe later button should be underneath download button!!

**Comment by Aboghazala** [comment]
this is another set
![image](https://user-images.githubusercontent.com/37757246/147398204-7abf5086-8ff7-43a7-bb35-98ac6cdb0a4c.png)

![image](https://user-images.githubusercontent.com/37757246/147398227-5b04d189-4028-4564-a3f6-b44f2be0d09d.png)

![image](https://user-images.githubusercontent.com/37757246/147398238-8b229280-b237-4102-b987-82996c7d5f3d.png)

**Comment by smaragdus** [comment]
@Aboghazala 

Hello again and thanks for the quick response as usual.

If you don't mind radical GUI change you may consider centered position of the download buttons, screen:

![FireDM 2021 12 26 - 2021-12-26 - 002](https://user-images.githubusercontent.com/9025757/147419967-da99b69b-884d-4467-8dac-a2ac36e0db39.png)

Such centered position will however require rearranging of all other elements in the main panel. What do you think?

**Comment by Aboghazala** [comment]
> Such centered position will however require rearranging of all other elements in the main panel. What do you think?

@smaragdus 
thanks for this work
i see download button as a main thing, in my opinion it shouldn't be in between things
as you said it will require a lot of re-arranging 

anyhow i will check more positions and see if it looks acceptable

**Comment by smaragdus** [comment]
@Aboghazala 

I agree that the last screen looks best (I mean [this one](https://user-images.githubusercontent.com/37757246/147398238-8b229280-b237-4102-b987-82996c7d5f3d.png)).

**Comment by Aboghazala** [comment]
> I agree that the last screen looks best (I mean [this one](https://user-images.githubusercontent.com/37757246/147398238-8b229280-b237-4102-b987-82996c7d5f3d.png)).

great!
will go for this option

**Comment by smaragdus** [comment]
@Aboghazala 

It seems that this issue is fully resolved in version [2022.2.5](https://github.com/firedm/FireDM/releases/tag/2022.2.5) so I will close it. I am glad that you chose Title Case for buttons, tool tips and context menu commands as it (at least for me) looks best. If it happens that I notice something I will report here.

Thanks!
