### ISSUE TITLE
error when downloading video of streamtape.com

### ISSUE THREAD

**Issue by phucbaodao** [firedm/FireDM#411]
I tried downloading the video on "streamtape.com" but it gives an error while on youtube-dl and yt-dlp it works fine.I use FireDM as Appimage

**Comment by Aboghazala** [comment]
@phucbaodao 

i googled to find a random video link on streamtape and tried both youtube-dl and yt-dlp and link is not supported
as shown below:
![image](https://user-images.githubusercontent.com/37757246/147420606-22a3ba2a-0be1-4916-88db-e97c3d2094dc.png)

please submit an example link that do work with youtube-dl or yt-dlp

**Comment by phucbaodao** [comment]
@Aboghazala yours seems to be just the url of a page and mine is a video
this is my example
![Screenshot from 2021-12-27 11-56-57](https://user-images.githubusercontent.com/77871763/147436333-ca04bf5b-ca06-495c-9b74-1d32d5127cc8.png)

https://user-images.githubusercontent.com/77871763/147436338-f21e2311-c0bf-451d-936a-0dbe3d68425e.mp4

**Comment by Aboghazala** [comment]
> your url seems to be just the url of a page and mine is the url of a video
this is my example

to enable testing, 
please submit an example url page and how to get the video url from it 
i can't copy the link from the screenshot

**Comment by phucbaodao** [comment]
i use this function of firefox to get the link i don't know what to call it but i usually use it but about the link this is it: https://streamtape.com/get_video?id=qOADaDDyjzTzQ67&expires=1640727227&ip=FROOD0xESHSNFt&token=ngmKjYc6mHiL&stream=1
![Screenshot from 2021-12-28 09-08-31](https://user-images.githubusercontent.com/77871763/147520225-62288094-11a5-43dd-b28b-79fc8ab910f1.png)

**Comment by firedm** [comment]
@phucbaodao 

please be noted that these kind of videos are not allowed to be downloaded with FireDM
as quoted from LICENSE file:

```
# This application is free for use, in hope to be useful for someone.                                               #
# Conditions and usage restrictions:                                                                                #
# - videos / streams / contents that are not allowed to be downloaded using this application are:                   #
#     - DRM "Digital rights management", protected videos / streams or Copyright materials.                         #
#     - Porn videos/streams or any pornography materials.                                                           #
#     - Illegal contents.                                                                                           #
#     - Any contents that encourage/promote violence or criminal/illegal behaviours 
```

Appreciate your understanding, 
kindly refer to [license](https://github.com/firedm/FireDM/blob/master/LICENSE) for more info
