### ISSUE TITLE
Why Firedm doesn't work for manjaro-kde-minimal

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#412]
![image](https://user-images.githubusercontent.com/36833664/147422876-8364c4ca-a0a0-4189-8e32-16d1867a9f6c.png)
FireDM-2021.12.26-x86_64.AppImage
https://sourceforge.net/projects/manjarolinux/files/kde/21.0.7/manjaro-kde-21.0.7-minimal-210614-linux54.iso/download

**Comment by Aboghazala** [comment]
might be related to .Xresources file
https://stackoverflow.com/questions/53459224/cant-use-pyplot-due-to-tkinter-tclerror-unknown-color-name

will continue investigate the problem

**Comment by Aboghazala** [comment]
@candrapersada 
please submit the result of this command in terminal

` xrdb -query`

**Comment by Aboghazala** [comment]
similiar isuue https://github.com/mate-desktop/mate-desktop/issues/134

**Comment by candrapersada** [comment]
now it works but the problem is why use `zenity` not `dialog`
![image](https://user-images.githubusercontent.com/36833664/147485353-b3cee10a-2721-4e07-b175-f4e77af37b79.png)

**Comment by Aboghazala** [comment]
> now it works but the problem is why use `zenity` not `kdialog` for Manjaro KDE

i believe it will use kdialog if installed, i will check the code again, but make sure kdialog is available from terminal

**Comment by Aboghazala** [comment]
@candrapersada 
restart FireDM again it should work and pick kdialog if available, otherwise it will show native tkinter dialog

**Comment by candrapersada** [comment]
> restart FireDM again it should work and pick kdialog if available

how to select kdialog?

**Comment by Aboghazala** [comment]
FireDM will first look for zenity if installed will use it, if not will use kdialog "if installed",  otherwise it will use built-in tkinter dialog

there is no option currently to select a specific dialog type

**Comment by candrapersada** [comment]
![a](https://user-images.githubusercontent.com/36833664/147513015-548c56e9-7696-4236-a56a-0a016ec5c8f5.PNG)
![b](https://user-images.githubusercontent.com/36833664/147513016-9b6224be-dffb-471b-8241-f1bc61a9db7d.PNG)

**Comment by Aboghazala** [comment]
i think something is not right here
can you post the output of this command
`which zenity`

**Comment by candrapersada** [comment]
```
$ which zenity

which: no zenity in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
$ which kdialog
/usr/bin/kdialog
$ 
```

**Comment by Aboghazala** [comment]
@candrapersada 
thanks for reporting
this is a bug in FireDM since it didn't expect any output from which command if zenity is not available
will fix it and let you know how to do a quick fix of your AppImage version

**Comment by Aboghazala** [comment]
@candrapersada 
issue has been fixed
to install this fix, you can download this file https://github.com/firedm/FireDM/raw/master/firedm/tkview.py and save it as tkview.py
to replace the same file in /home/candra/.config/FireDM/appimage-update-folder/firedm/

let me know if this fixed your issue

**Comment by candrapersada** [comment]
yes it works

**Comment by Aboghazala** [comment]
> yes it works

Great!
