### ISSUE TITLE
Can not download Youtube playlist on terminal

### ISSUE THREAD

**Issue by afzl-wtu** [firedm/FireDM#421]
Youtube playlist donwload by command, only downloads first item of playlist.

2nd: Firedm doest not run in interactive mode:
![image](https://user-images.githubusercontent.com/64379149/149809447-9e9737f5-213b-4a09-9543-84f7e4e6c08b.png)

**Comment by firedm** [comment]
@afzl-wtu 
there is "--nogui" option

to start firedm in interactive mode use "--interactive" flag for example:
`firedm "https://youtube.com/someplaylisturl" --interactive`

note you can download only one video at a time 
there is no option yet in cmdline to download full playlist, maybe this will be added in the future releases

**Comment by afzl-wtu** [comment]
> @afzl-wtu there is "--nogui" option
> 
> to start firedm in interactive mode use "--interactive" flag for example: `firedm "https://youtube.com/someplaylisturl" --interactive`
> 
> note you can download only one video at a time there is no option yet in cmdline to download full playlist, maybe this will be added in the future releases

Thanks. I understand now
