### ISSUE TITLE
Meta Data in URL

### ISSUE THREAD

**Issue by matthiscock** [firedm/FireDM#424]
Hi

When scraping certain sites you might (and I have) information which you would like FireDm to use.

For example you could have something like

www.url.com/video/123.whatever

However it would be nice if you could append the url with more information if you have it...

www.url.com/video/123.whatever?title=The Wonderful Wizard of Oz&filename=WonderfulWizardOfOz 

and so on

Would this be possible (or similar method) - this is mostly more useful when doing a batch, so you can deal with this in one hit

**Comment by firedm** [comment]
hello @matthiscock 
FireDM uses youtube-dl and yt-dlp to get video metadata, and doesn't have a separate mechanism to fetch video file info
