### ISSUE TITLE
merging video and audio Invalid NAL unit size with missing picture in access

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#430]
>> merging video and audio
>> frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=0.0236x
>> [NULL @ 000000000051e100] Invalid NAL unit size (47579137 > 88).
>> [NULL @ 000000000051e100] missing picture in access unit with size 92
>> [NULL @ 000000000051e100] Invalid NAL unit size (0 > 457).
>> [NULL @ 000000000051e100] missing picture in access unit with size 461
>> [NULL @ 000000000051e100] Invalid NAL unit size (-1258290944 > 1819).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1823
>> [NULL @ 000000000051e100] Invalid NAL unit size (-67311938 > 154).
>> [NULL @ 000000000051e100] missing picture in access unit with size 158
>> [NULL @ 000000000051e100] Invalid NAL unit size (27096866 > 1792).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1796
>> [NULL @ 000000000051e100] Invalid NAL unit size (1285411430 > 141).
>> [NULL @ 000000000051e100] missing picture in access unit with size 145
>> [NULL @ 000000000051e100] Invalid NAL unit size (1272528671 > 876).
>> [NULL @ 000000000051e100] missing picture in access unit with size 880
>> [NULL @ 000000000051e100] Invalid NAL unit size (268435456 > 1693).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1697
>> [NULL @ 000000000051e100] Invalid NAL unit size (2101347006 > 113).
>> [NULL @ 000000000051e100] missing picture in access unit with size 117
>> [NULL @ 000000000051e100] Invalid NAL unit size (498523739 > 1638).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1642
>> [NULL @ 000000000051e100] Invalid NAL unit size (1327726498 > 73).
>> [NULL @ 000000000051e100] missing picture in access unit with size 77
>> [NULL @ 000000000051e100] Invalid NAL unit size (770302093 > 859).
>> [NULL @ 000000000051e100] missing picture in access unit with size 863
>> [NULL @ 000000000051e100] Invalid NAL unit size (1902214345 > 1442).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1446
>> [NULL @ 000000000051e100] Invalid NAL unit size (-996819667 > 109).
>> [NULL @ 000000000051e100] missing picture in access unit with size 113
>> [NULL @ 000000000051e100] Invalid NAL unit size (2012968090 > 1555).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1559
>> [NULL @ 000000000051e100] Invalid NAL unit size (2014396421 > 151).
>> [NULL @ 000000000051e100] missing picture in access unit with size 155
>> [NULL @ 000000000051e100] Invalid NAL unit size (115745638 > 1538).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1542
>> [NULL @ 000000000051e100] Invalid NAL unit size (-437471593 > 125).
>> [NULL @ 000000000051e100] missing picture in access unit with size 129
>> [NULL @ 000000000051e100] Invalid NAL unit size (818427347 > 1630).
>> [NULL @ 000000000051e100] missing picture in access unit with size 1634
>> [NULL @ 000000000051e100] Invalid NAL unit size (189940522 > 93).
>> [NULL @ 000000000051e100] missing picture in access unit with size 97
>> [NULL @ 000000000051e100] Invalid NAL unit size (937652476 > 631).
>> [NULL @ 000000000051e100] missing picture in access unit with size 635
>> frame=  152 fps=0.0 q=-1.0 Lsize=    8148kB time=00:22:31.54 bitrate=  49.4kbits/s speed=3.88e+03x
>> File: 新サクラ大戦 Part.16 第四話 追跡、望月あざみ SakuraWars.mp4, saved at: D:\i新サクラ大戦 NewSakuraWars
>> 

This is an example of a broken video that I sent

https://user-images.githubusercontent.com/36833664/152954236-0d35ece1-fba1-4f88-af90-df5e610fc2d0.mp4

**Comment by firedm** [comment]
@candrapersada 
this is an ffmpeg error, if you're on Linux, i think ffmpeg on your system needs to be updated
see more details on this bug at https://trac.ffmpeg.org/ticket/4011#no1

if updating ffmpeg doesn't solve the problem you can try modifying FireDM files as follows:
in file named "video.py", you should add "-nostdin", to line [628](https://github.com/firedm/FireDM/blob/c58daac210f80f8c26733fcadda26c7c9d723773/firedm/video.py#L628)
after edit the line will be:

`cmd1 = f'"{ffmpeg}" -loglevel error -stats -y -nostdin -i "{video}" -i "{audio}" -c copy "{output}"'` 

save the file and try again and let me know  if problem gets solved

**Comment by candrapersada** [comment]
problem not solved
>> run_command()> cancelled ['D:/FFmpeg and yt-dlp/ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-nostdin', '-i', 'D:/FireDM\\firedm_uid_94ad4289837ef97c52539e4f49ad7188\\_temp_新サクラ大戦_Part.13_第四話_疑いの影、忍び寄る_SakuraWars.mp4', '-i', 'D:/FireDM\\firedm_uid_94ad4289837ef97c52539e4f49ad7188\\audio_for_新サクラ大戦_Part.13_第四話_疑いの影、忍び寄る_SakuraWars.mp4', '-c', 'copy', 'D:\\FireDM\\a\\新サクラ大戦 Part.13 第四話 疑いの影、忍び寄る SakuraWars.mp4']
>> merging video and audio
>> frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=0.0509x
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1254112705 > 28).
>> [NULL @ 000000000011e040] missing picture in access unit with size 32
>> [NULL @ 000000000011e040] Invalid NAL unit size (142893464 > 1110).
>> [NULL @ 000000000011e040] missing picture in access unit with size 1114
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1537836443 > 75).
>> [NULL @ 000000000011e040] missing picture in access unit with size 79
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1502923715 > 228).
>> [NULL @ 000000000011e040] missing picture in access unit with size 232
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1159392026 > 296).
>> [NULL @ 000000000011e040] missing picture in access unit with size 300
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1678189311 > 139).
>> [NULL @ 000000000011e040] missing picture in access unit with size 143
>> [NULL @ 000000000011e040] Invalid NAL unit size (559723457 > 270).
>> [NULL @ 000000000011e040] missing picture in access unit with size 274
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1842237892 > 161).
>> [NULL @ 000000000011e040] missing picture in access unit with size 165
>> [NULL @ 000000000011e040] Invalid NAL unit size (1093579900 > 336).
>> [NULL @ 000000000011e040] missing picture in access unit with size 340
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1505071248 > 125).
>> [NULL @ 000000000011e040] missing picture in access unit with size 129
>> [NULL @ 000000000011e040] Invalid NAL unit size (1835951551 > 179).
>> [NULL @ 000000000011e040] missing picture in access unit with size 183
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1726067901 > 230).
>> [NULL @ 000000000011e040] missing picture in access unit with size 234
>> [NULL @ 000000000011e040] Invalid NAL unit size (-831865502 > 366).
>> [NULL @ 000000000011e040] missing picture in access unit with size 370
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1823917137 > 226).
>> [NULL @ 000000000011e040] missing picture in access unit with size 230
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1255308883 > 852).
>> [NULL @ 000000000011e040] missing picture in access unit with size 856
>> [NULL @ 000000000011e040] Invalid NAL unit size (362760770 > 326).
>> [NULL @ 000000000011e040] missing picture in access unit with size 330
>> [NULL @ 000000000011e040] Invalid NAL unit size (2005385317 > 247).
>> [NULL @ 000000000011e040] missing picture in access unit with size 251
>> [NULL @ 000000000011e040] Invalid NAL unit size (1916811838 > 152).
>> [NULL @ 000000000011e040] missing picture in access unit with size 156
>> [NULL @ 000000000011e040] Invalid NAL unit size (1944667362 > 185).
>> [NULL @ 000000000011e040] missing picture in access unit with size 189
>> [NULL @ 000000000011e040] Invalid NAL unit size (1623074951 > 219).
>> [NULL @ 000000000011e040] missing picture in access unit with size 223
>> [NULL @ 000000000011e040] Invalid NAL unit size (650512120 > 411).
>> [NULL @ 000000000011e040] missing picture in access unit with size 415
>> [NULL @ 000000000011e040] Invalid NAL unit size (521148423 > 279).
>> [NULL @ 000000000011e040] missing picture in access unit with size 283
>> [NULL @ 000000000011e040] Invalid NAL unit size (330025265 > 209).
>> [NULL @ 000000000011e040] missing picture in access unit with size 213
>> [NULL @ 000000000011e040] Invalid NAL unit size (-2116909238 > 231).
>> [NULL @ 000000000011e040] missing picture in access unit with size 235
>> [NULL @ 000000000011e040] Invalid NAL unit size (1259763344 > 451).
>> [NULL @ 000000000011e040] missing picture in access unit with size 455
>> [NULL @ 000000000011e040] Invalid NAL unit size (-559479013 > 328).
>> [NULL @ 000000000011e040] missing picture in access unit with size 332
>> [NULL @ 000000000011e040] Invalid NAL unit size (-405748456 > 243).
>> [NULL @ 000000000011e040] missing picture in access unit with size 247
>> [NULL @ 000000000011e040] Invalid NAL unit size (-144664931 > 484).
>> [NULL @ 000000000011e040] missing picture in access unit with size 488
>> [NULL @ 000000000011e040] Invalid NAL unit size (-843922059 > 317).
>> [NULL @ 000000000011e040] missing picture in access unit with size 321
>> [NULL @ 000000000011e040] Invalid NAL unit size (1708979602 > 1649).
>> [NULL @ 000000000011e040] missing picture in access unit with size 1653
>> [NULL @ 000000000011e040] Invalid NAL unit size (1152526179 > 132).
>> [NULL @ 000000000011e040] missing picture in access unit with size 136
>> [NULL @ 000000000011e040] Invalid NAL unit size (-533096471 > 559).
>> [NULL @ 000000000011e040] missing picture in access unit with size 563
>> [NULL @ 000000000011e040] Invalid NAL unit size (-388584280 > 172).
>> [NULL @ 000000000011e040] missing picture in access unit with size 176
>> [NULL @ 000000000011e040] Invalid NAL unit size (-2066256840 > 423).
>> [NULL @ 000000000011e040] missing picture in access unit with size 427
>> [NULL @ 000000000011e040] Invalid NAL unit size (-515393377 > 666).
>> [NULL @ 000000000011e040] missing picture in access unit with size 670
>> [NULL @ 000000000011e040] Invalid NAL unit size (25930563 > 161).
>> [NULL @ 000000000011e040] missing picture in access unit with size 165
>> [NULL @ 000000000011e040] Invalid NAL unit size (399440866 > 352).
>> [NULL @ 000000000011e040] missing picture in access unit with size 356
>> [NULL @ 000000000011e040] Invalid NAL unit size (1176352486 > 217).
>> [NULL @ 000000000011e040] missing picture in access unit with size 221
>> [NULL @ 000000000011e040] Invalid NAL unit size (-1630434364 > 180).
>> [NULL @ 000000000011e040] missing picture in access unit with size 184
>> [NULL @ 000000000011e040] Invalid NAL unit size (2033745974 > 185).
>> [NULL @ 000000000011e040] missing picture in access unit with size 189

FireDM version: 2022.2.5
ffmpeg version: N-105336-g7247a6fed8-20220122
yt_dlp: 2022.02.04
Type: video, dash, fragmented

**Comment by candrapersada** [comment]
> looking at the above command, i see both video file and audio file not under same folder, which is weird

![image](https://user-images.githubusercontent.com/36833664/153213943-b1da9b76-d6b0-4ce5-9a31-6e579a0f9e54.png)

> anyhow, post the download link to try to reproduce the problem

https://www.youtube.com/watch?v=2oeaHrN7ZgM
Type: video, dash, fragmented

**Comment by firedm** [comment]
@candrapersada 
just tested the link, dash fragmented and no errors found

i think this might be a problem of mixing backslash `\` with forward slash `/` in path
can you replace the empty line number [629](https://github.com/firedm/FireDM/blob/c58daac210f80f8c26733fcadda26c7c9d723773/firedm/video.py#L629) in "video.py" file with the following
`cmd1 = cmd1.replace('\\', '/')`

**Comment by candrapersada** [comment]
>> merging video and audio
>> frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=0.0438x
>> [NULL @ 00230100] Invalid NAL unit size (4212 > 169).
>> [NULL @ 00230100] missing picture in access unit with size 173
>> [NULL @ 00230100] Invalid NAL unit size (14024705 > 81).
>> [NULL @ 00230100] missing picture in access unit with size 85
>> [NULL @ 00230100] non-existing PPS 11 referenced
>> [NULL @ 00230100] Invalid NAL unit size (369 > 312).
>> [NULL @ 00230100] missing picture in access unit with size 316
>> [NULL @ 00230100] Invalid NAL unit size (65536 > 38).
>> [NULL @ 00230100] missing picture in access unit with size 42
>> [NULL @ 00230100] Invalid NAL unit size (0 > 551).
>> [NULL @ 00230100] missing picture in access unit with size 555
>> [NULL @ 00230100] Invalid NAL unit size (-439995143 > 529).
>> [NULL @ 00230100] missing picture in access unit with size 533
>> [NULL @ 00230100] Invalid NAL unit size (977720743 > 18).
>> [NULL @ 00230100] missing picture in access unit with size 22
>> [NULL @ 00230100] Invalid NAL unit size (1888485571 > 119).
>> [NULL @ 00230100] missing picture in access unit with size 123
>> [NULL @ 00230100] Invalid NAL unit size (932419184 > 47).
>> [NULL @ 00230100] missing picture in access unit with size 51
>> [NULL @ 00230100] Invalid NAL unit size (-729789369 > 37).
>> [NULL @ 00230100] missing picture in access unit with size 41
>> [NULL @ 00230100] Invalid NAL unit size (1998022895 > 13).
>> [NULL @ 00230100] missing picture in access unit with size 17
>> [NULL @ 00230100] Invalid NAL unit size (-1539373511 > 534).
>> [NULL @ 00230100] missing picture in access unit with size 538
>> [NULL @ 00230100] Invalid NAL unit size (-930286671 > 21).
>> [NULL @ 00230100] missing picture in access unit with size 25
>> [NULL @ 00230100] Invalid NAL unit size (297708089 > 24).
>> [NULL @ 00230100] missing picture in access unit with size 28
>> [NULL @ 00230100] Invalid NAL unit size (-240235466 > 81).
>> [NULL @ 00230100] missing picture in access unit with size 85
>> [NULL @ 00230100] Invalid NAL unit size (348671751 > 321).
>> [NULL @ 00230100] missing picture in access unit with size 325
>> [NULL @ 00230100] Invalid NAL unit size (631128491 > 900).
>> [NULL @ 00230100] missing picture in access unit with size 904
>> [NULL @ 00230100] Invalid NAL unit size (1629697099 > 9).
>> [NULL @ 00230100] missing picture in access unit with size 13
>> [NULL @ 00230100] Invalid NAL unit size (-21368895 > 152).
>> [NULL @ 00230100] missing picture in access unit with size 156
>> [NULL @ 00230100] Invalid NAL unit size (-1064976704 > 30).
>> [NULL @ 00230100] missing picture in access unit with size 34
>> [NULL @ 00230100] Invalid NAL unit size (1775904724 > 30).
>> [NULL @ 00230100] missing picture in access unit with size 34
>> [NULL @ 00230100] Invalid NAL unit size (-1468410530 > 267).
>> [NULL @ 00230100] missing picture in access unit with size 271
>> [NULL @ 00230100] Invalid NAL unit size (1655477166 > 84).
>> [NULL @ 00230100] missing picture in access unit with size 88
>> [NULL @ 00230100] Invalid NAL unit size (-91818160 > 174).
>> [NULL @ 00230100] missing picture in access unit with size 178
>> [NULL @ 00230100] Invalid NAL unit size (1288605135 > 117).
>> [NULL @ 00230100] missing picture in access unit with size 121
>> [NULL @ 00230100] Invalid NAL unit size (1390354628 > 72).
>> [NULL @ 00230100] missing picture in access unit with size 76
>> [NULL @ 00230100] Invalid NAL unit size (-1119331711 > 113).
>> [NULL @ 00230100] missing picture in access unit with size 117
>> [NULL @ 00230100] Invalid NAL unit size (-1223377939 > 1363).
>> [NULL @ 00230100] missing picture in access unit with size 1367
>> [NULL @ 00230100] Invalid NAL unit size (-54938256 > 50).
>> [NULL @ 00230100] missing picture in access unit with size 54
>> [NULL @ 00230100] Invalid NAL unit size (-1881834507 > 70).
>> [NULL @ 00230100] missing picture in access unit with size 74
>> [NULL @ 00230100] Invalid NAL unit size (1703467567 > 152).
>> [NULL @ 00230100] missing picture in access unit with size 156
>> [NULL @ 00230100] Invalid NAL unit size (114877994 > 1757).
>> [NULL @ 00230100] missing picture in access unit with size 1761
>> [NULL @ 00230100] Invalid NAL unit size (-11630448 > 49).
>> [NULL @ 00230100] missing picture in access unit with size 53
>> [NULL @ 00230100] Invalid NAL unit size (-1315726938 > 46).
>> [NULL @ 00230100] missing picture in access unit with size 50
>> [NULL @ 00230100] Invalid NAL unit size (-1492985450 > 278).
>> [NULL @ 00230100] missing picture in access unit with size 282
>> [NULL @ 00230100] Invalid NAL unit size (-1296583830 > 646).
>> [NULL @ 00230100] missing picture in access unit with size 650
>> [NULL @ 00230100] Invalid NAL unit size (804148746 > 61).
>> [NULL @ 00230100] missing picture in access unit with size 65
>> [NULL @ 00230100] Invalid NAL unit size (1556730843 > 161).
>> [NULL @ 00230100] missing picture in access unit with size 165
>> [NULL @ 00230100] Invalid NAL unit size (-346960881 > 120).
>> [NULL @ 00230100] missing picture in access unit with size 124
>> [NULL @ 00230100] Invalid NAL unit size (-271279171 > 139).
>> [NULL @ 00230100] missing picture in access unit with size 143
>> [NULL @ 00230100] Invalid NAL unit size (-832563988 > 300).
>> [NULL @ 00230100] missing picture in access unit with size 304
>> [NULL @ 00230100] Invalid NAL unit size (-10828110 > 501).
>> [NULL @ 00230100] missing picture in access unit with size 505
>> [NULL @ 00230100] Invalid NAL unit size (567340075 > 225).
>> [NULL @ 00230100] missing picture in access unit with size 229
>> [NULL @ 00230100] Invalid NAL unit size (-512373712 > 595).
>> [NULL @ 00230100] missing picture in access unit with size 599
>> [NULL @ 00230100] Invalid NAL unit size (420939825 > 103).
>> [NULL @ 00230100] missing picture in access unit with size 107
>> [NULL @ 00230100] Invalid NAL unit size (-259602928 > 321).
>> [NULL @ 00230100] missing picture in access unit with size 325
>> [NULL @ 00230100] Invalid NAL unit size (982780749 > 639).
>> [NULL @ 00230100] missing picture in access unit with size 643
>> [NULL @ 00230100] Invalid NAL unit size (-581240368 > 136).
>> [NULL @ 00230100] missing picture in access unit with size 140
>> [NULL @ 00230100] Invalid NAL unit size (1992981306 > 343).
>> [NULL @ 00230100] missing picture in access unit with size 347
>> [NULL @ 00230100] Invalid NAL unit size (-618299131 > 801).
>> [NULL @ 00230100] missing picture in access unit with size 805
>> [NULL @ 00230100] Invalid NAL unit size (-948181501 > 103).
>> [NULL @ 00230100] missing picture in access unit with size 107
>> [NULL @ 00230100] Invalid NAL unit size (1251204001 > 288).
>> [NULL @ 00230100] missing picture in access unit with size 292
>> [NULL @ 00230100] Invalid NAL unit size (1642041010 > 357).
>> [NULL @ 00230100] missing picture in access unit with size 361
>> [NULL @ 00230100] Invalid NAL unit size (-1451179560 > 112).
>> [NULL @ 00230100] missing picture in access unit with size 116
>> [NULL @ 00230100] Invalid NAL unit size (87841385 > 2071).
>> [NULL @ 00230100] missing picture in access unit with size 2075
>> [NULL @ 00230100] Invalid NAL unit size (1315533659 > 56).
>> [NULL @ 00230100] missing picture in access unit with size 60
>> [NULL @ 00230100] Invalid NAL unit size (1611942818 > 181).
>> [NULL @ 00230100] missing picture in access unit with size 185
>> [NULL @ 00230100] Invalid NAL unit size (-1971882592 > 283).
>> [NULL @ 00230100] missing picture in access unit with size 287
>> [NULL @ 00230100] Invalid NAL unit size (1420963168 > 357).
>> [NULL @ 00230100] missing picture in access unit with size 361
>> [NULL @ 00230100] Invalid NAL unit size (-1961995646 > 227).
>> [NULL @ 00230100] missing picture in access unit with size 231
>> [NULL @ 00230100] Invalid NAL unit size (-142060464 > 613).
>> [NULL @ 00230100] missing picture in access unit with size 617
>> [NULL @ 00230100] Invalid NAL unit size (459400565 > 272).
>> [NULL @ 00230100] missing picture in access unit with size 276
>> [NULL @ 00230100] Invalid NAL unit size (339162722 > 2704).
>> [NULL @ 00230100] missing picture in access unit with size 2708
>> [NULL @ 00230100] Invalid NAL unit size (1192862028 > 29).
>> [NULL @ 00230100] missing picture in access unit with size 33
>> [NULL @ 00230100] Invalid NAL unit size (-2055568080 > 138).
>> [NULL @ 00230100] missing picture in access unit with size 142
>> [NULL @ 00230100] Invalid NAL unit size (-1950648405 > 2384).
>> [NULL @ 00230100] missing picture in access unit with size 2388
>> [NULL @ 00230100] Invalid NAL unit size (-1417800940 > 60).
>> [NULL @ 00230100] missing picture in access unit with size 64
>> [NULL @ 00230100] Invalid NAL unit size (61534813 > 1002).
>> [NULL @ 00230100] missing picture in access unit with size 1006
>> [NULL @ 00230100] Invalid NAL unit size (-1331782785 > 83).
>> [NULL @ 00230100] missing picture in access unit with size 87
>> [NULL @ 00230100] Invalid NAL unit size (2001906407 > 1128).
>> [NULL @ 00230100] missing picture in access unit with size 1132
>> [NULL @ 00230100] Invalid NAL unit size (44379686 > 69).
>> [NULL @ 00230100] missing picture in access unit with size 73
>> [NULL @ 00230100] Invalid NAL unit size (135713 > 232).
>> [NULL @ 00230100] missing picture in access unit with size 236
>> [NULL @ 00230100] Invalid NAL unit size (740852122 > 285).
>> [NULL @ 00230100] missing picture in access unit with size 289
>> [NULL @ 00230100] Invalid NAL unit size (903149787 > 769).
>> [NULL @ 00230100] missing picture in access unit with size 773
>> [NULL @ 00230100] Invalid NAL unit size (630440246 > 130).
>> [NULL @ 00230100] missing picture in access unit with size 134
>> frame=28863 fps=0.0 q=-1.0 size=   18944kB time=00:16:03.07 bitrate= 161.1kbits/s speed=1.85e+03x
>> [NULL @ 00230100] Invalid NAL unit size (1727449470 > 672).
>> [NULL @ 00230100] missing picture in access unit with size 676
>> [NULL @ 00230100] Invalid NAL unit size (869746373 > 74).
>> [NULL @ 00230100] missing picture in access unit with size 78
>> [NULL @ 00230100] Invalid NAL unit size (768915549 > 1595).
>> [NULL @ 00230100] missing picture in access unit with size 1599
>> [NULL @ 00230100] Invalid NAL unit size (-1871581764 > 50).
>> [NULL @ 00230100] missing picture in access unit with size 54
>> [NULL @ 00230100] Invalid NAL unit size (565795610 > 120).
>> [NULL @ 00230100] missing picture in access unit with size 124
>> [NULL @ 00230100] Invalid NAL unit size (-89399772 > 450).
>> [NULL @ 00230100] missing picture in access unit with size 454
>> [NULL @ 00230100] Invalid NAL unit size (1419438012 > 349).
>> [NULL @ 00230100] missing picture in access unit with size 353
>> [NULL @ 00230100] Invalid NAL unit size (-127432752 > 514).
>> [NULL @ 00230100] missing picture in access unit with size 518
>> frame=28880 fps=0.0 q=-1.0 Lsize=   23770kB time=00:27:44.77 bitrate= 117.0kbits/s speed=2.35e+03x
>> File: 創の軌跡 Part.12 Lloyd-2 亡失われた魂 The Legend of Heroes Hajimari no Kiseki.mp4, saved at: H:\Video
>>

**Comment by firedm** [comment]
what about run_command()> part like below does it changed?

`run_command()> cancelled ['D:/FFmpeg and yt-dlp/ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-nostdin', '-i', 'D:/FireDM\firedm_uid_94ad4289837ef97c52539e4f49ad7188\_temp_新サクラ大戦_Part.13_第四話_疑いの影、忍び寄る_SakuraWars.mp4', '-i', 'D:/FireDM\firedm_uid_94ad4289837ef97c52539e4f49ad7188\audio_for_新サクラ大戦_Part.13_第四話_疑いの影、忍び寄る_SakuraWars.mp4', '-c', 'copy', 'D:\FireDM\a\新サクラ大戦 Part.13 第四話 疑いの影、忍び寄る SakuraWars.mp4']

`

**Comment by candrapersada** [comment]
ya
![image](https://user-images.githubusercontent.com/36833664/153296460-db5dd420-1c8c-4ac0-84e5-269e2e24f2dc.png)

![image](https://user-images.githubusercontent.com/36833664/153296348-881b67b6-7933-4a61-b24f-b16d2963a47c.png)

**Comment by firedm** [comment]
@candrapersada 
will try to test again on windows machine maybe we can reproduce this problem

meanwhile, can you test with any earlier FireDM version and see if problem persist

**Comment by candrapersada** [comment]
> meanwhile, can you test with any earlier FireDM version and see if problem persist

- FireDM version: 2021.12.26

>> merging video and audio
>> frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=34909.1kbits/s speed=0.046x
>> [NULL @ 04d9d940] Invalid NAL unit size (65536 > 1073).
>> [NULL @ 04d9d940] missing picture in access unit with size 1077
>> [NULL @ 04d9d940] Invalid NAL unit size (63232 > 1166).
>> [NULL @ 04d9d940] missing picture in access unit with size 1170
>> [NULL @ 04d9d940] Invalid NAL unit size (392885338 > 1152).
>> [NULL @ 04d9d940] missing picture in access unit with size 1156
>> [NULL @ 04d9d940] Invalid NAL unit size (-31190605 > 1504).
>> [NULL @ 04d9d940] missing picture in access unit with size 1508
>> [NULL @ 04d9d940] Invalid NAL unit size (-217502887 > 1584).
>> [NULL @ 04d9d940] missing picture in access unit with size 1588
>> [NULL @ 04d9d940] Invalid NAL unit size (-699870674 > 831).
>> [NULL @ 04d9d940] missing picture in access unit with size 835
>> [NULL @ 04d9d940] Invalid NAL unit size (-384055933 > 1641).
>> [NULL @ 04d9d940] missing picture in access unit with size 1645
>> [NULL @ 04d9d940] Invalid NAL unit size (1452084481 > 1166).
>> [NULL @ 04d9d940] missing picture in access unit with size 1170
>> [NULL @ 04d9d940] Invalid NAL unit size (1489428945 > 341).
>> [NULL @ 04d9d940] missing picture in access unit with size 345
>> [NULL @ 04d9d940] Invalid NAL unit size (-227222079 > 1089).
>> [NULL @ 04d9d940] missing picture in access unit with size 1093
>> [NULL @ 04d9d940] Invalid NAL unit size (-1983718807 > 1049).
>> [NULL @ 04d9d940] missing picture in access unit with size 1053
>> [NULL @ 04d9d940] Invalid NAL unit size (1074712509 > 969).
>> [NULL @ 04d9d940] missing picture in access unit with size 973
>> [NULL @ 04d9d940] Invalid NAL unit size (-1015391509 > 1694).
>> [NULL @ 04d9d940] missing picture in access unit with size 1698
>> [NULL @ 04d9d940] Invalid NAL unit size (-343477387 > 929).
>> [NULL @ 04d9d940] missing picture in access unit with size 933
>> [NULL @ 04d9d940] Invalid NAL unit size (1018315164 > 919).
>> [NULL @ 04d9d940] missing picture in access unit with size 923
>> [NULL @ 04d9d940] Invalid NAL unit size (-400428132 > 1247).
>> [NULL @ 04d9d940] missing picture in access unit with size 1251
>> [NULL @ 04d9d940] Invalid NAL unit size (1700015060 > 462).
>> [NULL @ 04d9d940] missing picture in access unit with size 466
>> [NULL @ 04d9d940] Invalid NAL unit size (-319421704 > 493).
>> [NULL @ 04d9d940] missing picture in access unit with size 497
>> [NULL @ 04d9d940] Invalid NAL unit size (620007839 > 652).
>> [NULL @ 04d9d940] missing picture in access unit with size 656
>> [NULL @ 04d9d940] Invalid NAL unit size (-265663813 > 973).
>> [NULL @ 04d9d940] missing picture in access unit with size 977
>> [NULL @ 04d9d940] Invalid NAL unit size (-1891253163 > 585).
>> [NULL @ 04d9d940] missing picture in access unit with size 589
>> [NULL @ 04d9d940] Invalid NAL unit size (470089927 > 783).
>> [NULL @ 04d9d940] missing picture in access unit with size 787
>> [NULL @ 04d9d940] Invalid NAL unit size (-1837518572 > 859).
>> [NULL @ 04d9d940] missing picture in access unit with size 863
>> [NULL @ 04d9d940] Invalid NAL unit size (706853679 > 902).
>> [NULL @ 04d9d940] missing picture in access unit with size 906
>> [NULL @ 04d9d940] Invalid NAL unit size (143899 > 509).
>> [NULL @ 04d9d940] missing picture in access unit with size 513
>> [NULL @ 04d9d940] Invalid NAL unit size (129399474 > 679).
>> [NULL @ 04d9d940] missing picture in access unit with size 683
>> [NULL @ 04d9d940] Invalid NAL unit size (-1795744220 > 1171).
>> [NULL @ 04d9d940] missing picture in access unit with size 1175
>> [NULL @ 04d9d940] Invalid NAL unit size (-928465121 > 845).
>> [NULL @ 04d9d940] missing picture in access unit with size 849
>> [NULL @ 04d9d940] Invalid NAL unit size (186850063 > 626).
>> [NULL @ 04d9d940] missing picture in access unit with size 630
>> [NULL @ 04d9d940] Invalid NAL unit size (941993482 > 720).
>> [NULL @ 04d9d940] missing picture in access unit with size 724
>> [NULL @ 04d9d940] Invalid NAL unit size (295779888 > 606).
>> [NULL @ 04d9d940] missing picture in access unit with size 610
>> [NULL @ 04d9d940] Invalid NAL unit size (-1420904211 > 1594).
>> [NULL @ 04d9d940] missing picture in access unit with size 1598
>> [NULL @ 04d9d940] Invalid NAL unit size (-1527828752 > 583).
>> [NULL @ 04d9d940] missing picture in access unit with size 587
>> frame=28728 fps=0.0 q=-1.0 size=   18944kB time=00:16:22.71 bitrate= 157.9kbits/s speed=1.96e+03x
>> frame=28728 fps=0.0 q=-1.0 Lsize=   26437kB time=00:35:07.48 bitrate= 102.8kbits/s speed=2.78e+03x
>> File: 新サクラ大戦 Part.1 第一話 新たなる風 SakuraWars.mp4, saved at: H:\Video
>>

**Comment by shoklan14** [comment]
I had the same problem. Solved it by reducing the number of connections. That way there are fewer corruptions. I set the number of connections to 5 and there was no reduction in download speed.
Reducing number of concurrent downloads also helps to share bandwidth equally

**Comment by candrapersada** [comment]
will there be a notification feature in the future if video corruptions without manually checking in the log tab

**Comment by firedm** [comment]
@candrapersada 
added a fix for this issue and added a re-download option in right click menu 

you can try the new additions by downloading FireDM's files from github source files or wait for coming release

**Comment by candrapersada** [comment]
> added a fix for this issue and added a re-download option in right click menu

why does the video name change when i start re-downloading for example `xxx.mp4` becomes `xxx_2.mp4`
