### ISSUE TITLE
Twitch download of previous streams (VOD) fails

### ISSUE THREAD

**Issue by sKGu8gxV** [firedm/FireDM#432]
First thanks so much for your hard work! I'm so happy to finally have found a dler that works!

I'm attempting to download https://www.twitch.tv/videos/1282527638, but I've tried it with several other streams as well. 
https://i.imgur.com/M4HFRng.png is the error message. 

Downloads from YT and other places work without an issue.

**Comment by sKGu8gxV** [comment]
Ps. Here's the log: 

>> start downloading file: "Hi__2.mp4", size: 0 B, to: D:\TwitchStreams
>> url: "https://www.twitch.tv/videos/1282527638" 

>> pre_process_hls()> start processing Hi__2.mp4
>> master manifest:    https://usher.ttvnw.net/vod/1282527638.m3u8?allow_source=true&allow_audio_only=true&allow_spectre=true&player=twitchweb&playlist_include_framerate=true&nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1644907849%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1282527638%7D&nauthsig=37d7f18591781155b040afc7c35d57f959598e1a
>> video m3u8:         https://dgeft87wbj63p.cloudfront.net/8604d693ab2087f2a3c8_jfk_pain_44561863964_1643656266/chunked/index-dvr.m3u8
>> ['normal', 'hls']
>> pre_process_hls()> done processing Hi__2.mp4
>> handling hls videos
>> post_process_hls()> start processing Hi__2.mp4
>> [hls @ 06793ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'
>> F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> [hls @ 068c3ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'
>> F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> post_process_hls()> ffmpeg failed: [hls @ 068c3ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> run_command()> cancelled ['F:\\Progs\\FireDM\\ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-protocol_whitelist', 'file,http,https,tcp,tls,crypto', '-allowed_extensions', 'ALL', '-i', 'F:/Temp\\firedm_uid_40f8c4869da4ea162053dbc42926cade\\local_video.m3u8', 'file:F:/Temp\\firedm_uid_40f8c4869da4ea162053dbc42926cade\\_temp_Hi__2.mp4']
>> file_manager()>  post_process_hls() failed, file: 
 Hi__2.mp4
>> auto refresh url for: Hi__2.mp4
>> [twitch:vod] 1282527638: Downloading stream metadata GraphQL
>> [twitch:vod] 1282527638: Downloading video access token GraphQL
>> [twitch:vod] 1282527638: Downloading m3u8 information
>> selected stream:         mp4 - 1080-HD - 1920x1080 - 0 B - id:1080p60 - 119.786 fps
>> New selected stream:     mp4 - 1080-HD - 1920x1080 - 0 B - id:1080p60 - 119.786 fps
>> 

>> --------------------------------------------------
>> start downloading file: "Hi__2.mp4", size: 0 B, to: D:\TwitchStreams
>> url: "https://www.twitch.tv/videos/1282527638" 

>> pre_process_hls()> start processing Hi__2.mp4
>> master manifest:    https://usher.ttvnw.net/vod/1282527638.m3u8?allow_source=true&allow_audio_only=true&allow_spectre=true&player=twitchweb&playlist_include_framerate=true&nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1644907999%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1282527638%7D&nauthsig=5804f08da9432fc9520d0ab83f14076f50a5f456
>> video m3u8:         https://dgeft87wbj63p.cloudfront.net/8604d693ab2087f2a3c8_jfk_pain_44561863964_1643656266/chunked/index-dvr.m3u8
>> ['normal', 'hls']
>> pre_process_hls()> done processing Hi__2.mp4
>> load_progress_info()> updated current segments for: Hi__2.mp4
>> handling hls videos
>> post_process_hls()> start processing Hi__2.mp4
>> [hls @ 06863ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'
>> F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> [hls @ 06743ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'
>> F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> post_process_hls()> ffmpeg failed: [hls @ 06743ac0] Error when loading first segment 'F:/F:/Temp/firedm_uid_40f8c4869da4ea162053dbc42926cade/video_seg_1.ts'F:/Temp\firedm_uid_40f8c4869da4ea162053dbc42926cade\local_video.m3u8: Invalid data found when processing input
>> run_command()> cancelled ['F:\\Progs\\FireDM\\ffmpeg.exe', '-loglevel', 'error', '-stats', '-y', '-protocol_whitelist', 'file,http,https,tcp,tls,crypto', '-allowed_extensions', 'ALL', '-i', 'F:/Temp\\firedm_uid_40f8c4869da4ea162053dbc42926cade\\local_video.m3u8', 'file:F:/Temp\\firedm_uid_40f8c4869da4ea162053dbc42926cade\\_temp_Hi__2.mp4']
>> file_manager()>  post_process_hls() failed, file: 
 Hi__2.mp4
>> controller: too many connection errors maybe network problem or expired link

**Comment by firedm** [comment]
@sKGu8gxV 
thanks for reporting, will investigate this problem

**Comment by sKGu8gxV** [comment]
> @sKGu8gxV thanks for reporting, will investigate this problem

Thanks!

**Comment by shakakibara12** [comment]
Hey i think the video is removed can you check the link?
![image](https://user-images.githubusercontent.com/75451009/154520945-f277b9f4-d899-41bd-ba19-2f87bc97a500.png)

**Comment by firedm** [comment]
@sKGu8gxV 
I already tested another twitch "offline video" and downloaded with no problem

can you retry downloading with one connection
goto "Settings>Downloader option>connections per download" and set it to 1 connection

**Comment by sKGu8gxV** [comment]
> @sKGu8gxV I already tested another twitch "offline video" and downloaded with no problem
> 
> can you retry downloading with one connection goto "Settings>Downloader option>connections per download" and set it to 1 connection

Ok  I've tried this now along with:
Disabling proxy
Disabling custom user agent
Putting 1 concurrent download / download (instead of the 3 I had set)

Trying to delete settings.cfg now, will report back.

**Comment by sKGu8gxV** [comment]
Ok so what I did was find a tiny vid, and start putting my settings again one by one. Bit unfortunate but this error only happened as the download was almost complete. Anyways, it seems like when I put the bandwidthlimiter on (7mb/s) it starts getting slightly wonky. Proxy and the default # of downloads / download and concurrent downloads are all fine.

**Comment by firedm** [comment]
> Yea, I've been playing with the settings to and fro and everything seems to work now even though, as far as I can tell, the settings are exactly the same.
> 
> Ps. Thanks for the assistance and thanks again for firedm!

Great it works now for you
