### ISSUE TITLE
Manjaro - Clicking on Download Button opens Download section but no downloads

### ISSUE THREAD

**Issue by afzl-wtu** [firedm/FireDM#435]
I do not want to use portable version becuase python is already installed in my system. So I do not want another python package in AppImage. But Portable version works flawlessly out of the box, no any issue.
So I followed:
Manually installing FireDM with pip (Linux) Method.
I am running latest Manjaro with KDE.
Python version: 3.10
also installed sudo pacman -S tk and python-awesometinker in appstore.
Also there is no documentation for installing packages and fonts in Manjaro.
I see,
When Installing:

>  python3 -m pip install firedm --user --upgrade --no-cache                                      ✔ 
> Collecting firedm
>   Downloading FireDM-2022.2.5-py3-none-any.whl (180 kB)
>      |████████████████████████████████| 180 kB 637 kB/s            
> Requirement already satisfied: pystray in ./.local/lib/python3.10/site-packages (from firedm) (0.19.2)
> Requirement already satisfied: yt-dlp in ./.local/lib/python3.10/site-packages (from firedm) (2022.2.4)
> Requirement already satisfied: plyer in ./.local/lib/python3.10/site-packages (from firedm) (2.0.0)
> Requirement already satisfied: certifi in /usr/lib/python3.10/site-packages (from firedm) (2021.10.8)
> Requirement already satisfied: youtube-dl in ./.local/lib/python3.10/site-packages (from firedm) (2021.12.17)
> Requirement already satisfied: awesometkinter>=2021.6.4 in ./.local/lib/python3.10/site-packages (from firedm) (2021.11.8)
> Requirement already satisfied: distro in /usr/lib/python3.10/site-packages (from firedm) (1.6.0)
> Requirement already satisfied: packaging in /usr/lib/python3.10/site-packages (from firedm) (20.9)
> Requirement already satisfied: Pillow>=6.0.0 in ./.local/lib/python3.10/site-packages (from firedm) (9.0.1)
> Requirement already satisfied: pycurl in ./.local/lib/python3.10/site-packages (from firedm) (7.44.1)
> Requirement already satisfied: python-bidi in ./.local/lib/python3.10/site-packages (from awesometkinter>=2021.6.4->firedm) (0.4.2)
> Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging->firedm) (2.4.7)
> Requirement already satisfied: python-xlib>=0.17 in ./.local/lib/python3.10/site-packages (from pystray->firedm) (0.31)
> Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from pystray->firedm) (1.16.0)
> Requirement already satisfied: mutagen in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (1.45.1)
> Requirement already satisfied: pycryptodomex in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (3.14.1)
> Requirement already satisfied: websockets in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (10.2)
> Installing collected packages: firedm
> Successfully installed firedm-2022.2.5

when I open it:

```
firedm                                                                                         ✔ 

>> Load previous download items from /home/afzl/.config/FireDM/
>> load_progress_info()> rebuild segments from previous download for: KDE Plasma with Fluent Design Theme _Shorts.flac
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: /usr/bin/ffmpeg, version: n4.4.1
>> yt_dlp version: 2022.02.04, load_time= 0 seconds
>> set default extractor engine to: yt_dlp <module 'yt_dlp' from '/home/afzl/.local/lib/python3.10/site-packages/yt_dlp/__init__.py'>
>> youtube_dl version: 2021.12.17, load_time= 0 seconds
>> -------------------- FireDM --------------------
>> Starting FireDM version: 2022.2.5 Non-Frozen
>> operating system: Os: Linux - Platform: Linux-5.15.21-1-MANJARO-x86_64-with-glibc2.33 - Machine: x86_64
Distribution: ('Manjaro Linux', '21.2.3', 'Qonos')
>> Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
>> current working directory: /home/afzl/.local/lib/python3.10/site-packages/firedm
>> FFMPEG: /usr/bin/ffmpeg, version: n4.4.1
>> Tkinter version: 8.6.12
>> AwesomeTkinter version: 2021.11.8
>> Pillow version: 9.0.1
>> PyCUrl version: PycURL/7.44.1 libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0
>> 
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> systray disabled in settings ...
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4539, in update_view_handler
    self._update_view(**kwargs)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4568, in _update_view
    self.create_ditem(**item, focus=False)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4273, in create_ditem
    d_item = DItem(self.d_tab, uid, status, on_toggle_callback=self.update_stat_lbl, mode=mode, bg=bg,
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1567, in __init__
    self.view(mode=mode)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1801, in view
    self.view_compact()
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1782, in view_compact
    self.bar = tk.IntVar(0)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'
```

When I paste a link and click on Download:

```
url_watchdog, new url:  https://www.youtube.com/watch?v=-4dtjKFqEEE
>> creating video playlist
>> [youtube] -4dtjKFqEEE: Downloading webpage
>> [youtube] -4dtjKFqEEE: Downloading android player API JSON
>> downloading Thumbnail
>> controller> playlist ready
>> check ffmpeg availability?
>> ffmpeg checked ok! - at: /usr/bin/ffmpeg, version: n4.4.1
>> downloads items list saved in: /home/afzl/.config/FireDM/downloads.dat
>> 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4539, in update_view_handler
    self._update_view(**kwargs)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4619, in _update_view
    self.create_ditem(**kwargs)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 4273, in create_ditem
    d_item = DItem(self.d_tab, uid, status, on_toggle_callback=self.update_stat_lbl, mode=mode, bg=bg,
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1567, in __init__
    self.view(mode=mode)
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1801, in view
    self.view_compact()
  File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1782, in view_compact
    self.bar = tk.IntVar(0)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'
>> --------------------------------------------------
>> start downloading file: "Kusu Kusu Full Video Song _Ft Nora Fatehi _ Satyameva Jayate 2 _ John A_ Divya K _ Tanishk.mp3", size: 3.21 MB, to: /home/afzl/Downloads
>> url: "https://www.youtube.com/watch?v=-4dtjKFqEEE" 

>> Seg 0 start, size: 164.33 KB - range: [0, 168273]  - worker 4
>> Seg 1 start, size: 328.66 KB - range: [168274, 504822]  - worker 5
>> Seg 2 start, size: 492.99 KB - range: [504823, 1009646]- minimum speed= 20480, timeout=10  - worker 6
>> downloaded segment:  0 [0, 168273] 164.33 KB - worker 4
>> Seg 3 start, size: 657.32 KB - range: [1009647, 1682745]- minimum speed= 20480, timeout=10  - worker 7
>> downloaded segment:  1 [168274, 504822] 328.66 KB - worker 5
>> Seg 4 start, size: 1.6 MB - range: [1682746, 3365498]- minimum speed= 20480, timeout=10  - worker 8
>> Seg 5 start, size: 813.66 KB - range: [2532315, 3365498]- minimum speed= 20480, timeout=10  - worker 9
>> Seg 6 start, size: 406.83 KB - range: [2948908, 3365498]- minimum speed= 20480, timeout=10  - worker 0
>> Seg 7 start, size: 294.83 KB - range: [2230411, 2532314]- minimum speed= 20480, timeout=10  - worker 1
>> downloaded segment:  3 [1009647, 1682745] 657.32 KB - worker 7
>> downloaded segment:  4 [1682746, 2230410] 534.83 KB - worker 8
>> downloaded segment:  6 [2948908, 3365498] 406.83 KB - worker 0
>> downloaded segment:  7 [2230411, 2532314] 294.83 KB - worker 1
>> downloaded segment:  5 [2532315, 2948907] 406.83 KB - worker 9
>> downloaded segment:  2 [504823, 1009646] 492.99 KB - worker 6
>> thread_manager uid_e6a1cf8e4b02e7f0c881132b9c03606e: quitting
>> handling audio streams
>> running command: "/usr/bin/ffmpeg" -loglevel error -stats -y -i "/home/afzl/Downloads/firedm_uid_e6a1cf8e4b02e7f0c881132b9c03606e/_temp_Kusu_Kusu_Full_Video_Song__Ft_Nora_Fatehi___Satyameva_Jayate_2___John_A__Divya_K___Tanishk.mp3" -acodec copy "/home/afzl/Downloads/Kusu Kusu Full Video Song _Ft Nora Fatehi _ Satyameva Jayate 2 _ John A_ Divya K _ Tanishk.mp3"
>> [mp3 @ 0x563bfe444e00] Invalid audio stream. Exactly one MP3 audio stream is required.
>> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
>> Error initializing output stream 0:0 --
>> 
>> running command: "/usr/bin/ffmpeg" -loglevel error -stats -y -i "/home/afzl/Downloads/firedm_uid_e6a1cf8e4b02e7f0c881132b9c03606e/_temp_Kusu_Kusu_Full_Video_Song__Ft_Nora_Fatehi___Satyameva_Jayate_2___John_A__Divya_K___Tanishk.mp3" "/home/afzl/Downloads/Kusu Kusu Full Video Song _Ft Nora Fatehi _ Satyameva Jayate 2 _ John A_ Divya K _ Tanishk.mp3"
>> size=       0kB time=00:00:00.00 bitrate=N/A speed=N/A
>> size=     256kB time=00:00:19.85 bitrate= 105.6kbits/s speed=39.7x
>> size=     512kB time=00:00:38.50 bitrate= 108.9kbits/s speed=38.5x
>> size=     768kB time=00:00:58.77 bitrate= 107.0kbits/s speed=39.2x
>> size=    1024kB time=00:01:18.55 bitrate= 106.8kbits/s speed=39.2x
>> size=    1280kB time=00:01:37.75 bitrate= 107.3kbits/s speed=39.1x
>> size=    1792kB time=00:01:58.07 bitrate= 124.3kbits/s speed=39.3x
>> size=    2048kB time=00:02:18.16 bitrate= 121.4kbits/s speed=39.4x
>> size=    2304kB time=00:02:37.85 bitrate= 119.6kbits/s speed=39.4x
>> size=    2560kB time=00:02:57.68 bitrate= 118.0kbits/s speed=39.5x
>> size=    3072kB time=00:03:18.27 bitrate= 126.9kbits/s speed=39.6x
>> size=    3250kB time=00:03:27.90 bitrate= 128.0kbits/s speed=39.8x
>> file_manager uid_e6a1cf8e4b02e7f0c881132b9c03606e: quitting
>> File Completed.
>> brain uid_e6a1cf8e4b02e7f0c881132b9c03606e: quitting
>> -------------------------------------------------- 

>> File: Kusu Kusu Full Video Song _Ft Nora Fatehi _ Satyameva Jayate 2 _ John A_ Divya K _ Tanishk.mp3, saved at: /home/afzl/Downloads
```

But In Download Section I do not see anything (even not progress):
![image](https://user-images.githubusercontent.com/64379149/155006297-bbbfd9a4-4fb7-4fe2-81de-59616777adb1.png)

**Comment by afzl-wtu** [comment]
Also AUR behaves the same even it is not updated.. Only portable version works.

**Comment by firedm** [comment]
@afzl-wtu 
will investigate the problem and see what we can do

**Comment by slumbergod** [comment]
I can also confirm this strange behaviour. I did a Manjaro stable update a few days ago which I am confident is responsible. I am using the standard XFCE environment with Manjaro.

I can confirm that the files are indeed downloading. Both srt subtitles and the video itself. But the download window is showing no files at all. Also on the left bottom of the main interface where it shows the speed it remains at 0 for me.

**Comment by firedm** [comment]
@afzl-wtu 

from the traceback you posted i can see the error in` tkview.py` file

> File "/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py", line 1782, in view_compact
    self.bar = tk.IntVar(0)

can you modify this file at `"/home/afzl/.local/lib/python3.10/site-packages/firedm/tkview.py"` 
line 1782
change `self.bar = tk.IntVar(0)`  to `self.bar = tk.IntVar(value=0)`

and see if this fix the problem

**Comment by slumbergod** [comment]
@firedm

I tested the change you suggested and it corrected the problem for me. The Downloads page now shows all of the files that I downloaded when the page was not displaying anything. The speed indicator is also working. Thank you!

**Comment by slumbergod** [comment]
Another behaviour which I have noticed since the time the download page became blank is the dumping of directories in the download location, in my case Desktop. The folders are named like this "firedm_uid_296db419db1711a1e02076068ac340df" and contain stream rips and other related files. Is it possible that another code tweak is needed to automatically delete them after the download is complete?

**Comment by firedm** [comment]
> @firedm
> 
> I tested the change you suggested and it corrected the problem for me. The Downloads page now shows all of the files that I downloaded when the page was not displaying anything. The speed indicator is also working. Thank you!

Great! will add this fix to main branch

**Comment by firedm** [comment]
> Another behaviour which I have noticed since the time the download page became blank is the dumping of directories in the download location, in my case Desktop. The folders are named like this "firedm_uid_296db419db1711a1e02076068ac340df" and contain stream rips and other related files. Is it possible that another code tweak is needed to automatically delete them after the download is complete?

Not sure why temp folders stay behind, it should be automatically deleted when download completed
if you run FireDM from terminal, please report any error you see when an item completed download, "but make sure log level set to 3 in FireDM's log tab

**Comment by afzl-wtu** [comment]
Sorry for long time. I am glad that issue is fixed but I can not test it on manjaro, Becuase I have uninstalled Manjaro and shifted to Wndows 11. I hate linux. They do not fix issues in linux. Sometime Phone does not connect to Manjaro via cable. Linux is also very bad when trasnferring data to slow [flash drives](https://archived.forum.manjaro.org/t/decrease-dirty-bytes-for-more-reliable-usb-transfer/62513). But no one listens. and many other issues comes with time.

**Comment by firedm** [comment]
@afzl-wtu 

>  I hate linux. They do not fix issues in linux

in my opinion, the best operating system is the one that gives you less troubles and do your jobs easily
personally, i switched from ubuntu to Manjaro to pop-os, then currently to linux mint which is doing my tasks with no problem in same time, still dual boot with windows 10 

the main reason i prefer linux is there no junk "background processes" like windows do, which is running continuously, bleeding your cpu, hard-disk and network resources

good luck

**Comment by afzl-wtu** [comment]
> @afzl-wtu
> 
> > I hate linux. They do not fix issues in linux
> 
> in my opinion, the best operating system is the one that gives you less troubles and do your jobs easily personally, i switched from ubuntu to Manjaro to pop-os, then currently to linux mint which is doing my tasks with no problem in same time, still dual boot with windows 10
> 
> the main reason i prefer linux is there no junk "background processes" like windows do, which is running continuously, bleeding your cpu, hard-disk and network resources
> 
> good luck

I also hate windows to keep running background processes. Also Thanks for the suggestion I will try Mint too. But I do not want to dual boot. I want to shift everything to one OS.

**Comment by slumbergod** [comment]
@afzl-wtu

I understand how you feel. I feel the same way about windows, microsoft in general, and google, though it's more about how they want to monetize everything these days. My friends running windows 10 have just as many issues as I have with Manjaro. In fact the irony of it all is that I switched to Manjaro's rolling release because I hoped it would fix the bugs faster!

Anyway, I appreciate your effort with FireDM. It's an essential application for me and I am quite amazed you managed to build such a good GUI using tkinter! Thanks for your hard work!

**Comment by afzl-wtu** [comment]
> @afzl-wtu
> 
> I understand how you feel. I feel the same way about windows, microsoft in general, and google, though it's more about how they want to monetize everything these days. My friends running windows 10 have just as many issues as I have with Manjaro. In fact the irony of it all is that I switched to Manjaro's rolling release because I hoped it would fix the bugs faster!
> 
> Anyway, I appreciate your effort with FireDM. It's an essential application for me and I am quite amazed you managed to build such a good GUI using tkinter! Thanks for your hard work!

hahahhaha. Bro I am author of only this issue not FireDM app. Obviously Firedm is a great app. I even use it for downloading large files too. Further it will be good if it supports link expiry for direct downloads too.

**Comment by afzl-wtu** [comment]
MacOS is best. if it works perfectly on your Hackintosh.
