### ISSUE TITLE
Downloading IPTV streams.

### ISSUE THREAD

**Issue by oldgitimh** [firedm/FireDM#48]
Thanks for providing such an awesome utility.
I am trying to download/save  IPTV streams such as:-   https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8

After 10 or so seconds an ffmpeg.exe window opens and the program seems to hang while attempting to merge audio. 

I realise this may be outside the scope of pyIDM but for me it would be great if it could handle this type of download perhaps with an "stop recording" time option as clearly with a 24/7 stream the download will go on forever!

**Comment by pyIDM** [comment]
@oldgitimh 
Thanks for your feedback,
I will work on this feature "support for live stream" and let you know once done

**Comment by oldgitimh** [comment]
Thank you !

**Comment by firedm** [comment]
sorry, there is no current plans to support live streams
closing issue
