### ISSUE TITLE
Right-To-Left languages doesn't get displayed correctly by Tkinter on  Linux

### ISSUE THREAD

**Issue by firedm** [firedm/FireDM#88]
Right-To-Left (RTL) languages doesn't show correctly on Linux
the most widespread RTL are Arabic, Hebrew, Persian, and Urdu, more details: https://en.wikipedia.org/wiki/Right-to-left

It is a well known bug and it affect applications made by tkinter on Linux only "well not sure about mac", but on windows there is no problem at all, since tkinter do display RTL languages correctly.

there is some buggy workarounds to this problem but i couldn't find a proper and reliable solution to this,

**Any help will be appreciated**

example of bad Arabic rendering on linux
correct title: البلاتفورم - كيف بدأت كرة القدم
![image](https://user-images.githubusercontent.com/58998813/86530761-d7636a80-bebb-11ea-9258-2b2d8387741b.png)

**Comment by pyIDM** [comment]
some links related to this issue:
https://wiki.tcl-lang.org/page/bidi+rendering
https://wiki.tcl-lang.org/page/Arabic+Character+Renderer+For+Readability+In+TCL%2FTk
https://wiki.tcl-lang.org/page/A+Quick+Fix+To+Typing+In+Widget+%5Btext%5D+In+Arabic+Language+On+Linux.

**Comment by pyIDM** [comment]
Partially fixed Arabic rendering on Linux 
this how this title will be displayed البلاتفورم - كيف بدأت كرة القدم

![image](https://user-images.githubusercontent.com/58998813/86530846-843de780-bebc-11ea-979d-9c728f1960e5.png)

**Comment by ahmed-tasaly** [comment]
@firedm 
**السلام عليكم**
ممكن تجرب ده 
https://www.arabic-keyboard.org/photoshop-arabic/

**Comment by firedm** [comment]
> @firedm
> **السلام عليكم**
> ممكن تجرب ده
> https://www.arabic-keyboard.org/photoshop-arabic/

وعليكم السلام 
شكرا وجارى التجربه
